### ISSUE TITLE
If disabling one Transport other transports are also not working

### ISSUE THREAD

**Issue by dbelz** [megahertz/electron-log#10]
Hello,

if i disable the console transport and only allow the transport to file the file transport is also not working. I have located the "bug" in the log method of your library.

```
var transports = module.exports.transports;
  for (var i in transports) {
    // jshint -W089
    if (!transports.hasOwnProperty(i) || typeof transports[i] !== 'function') {
      return;
    }
    if (!compareLevels(transports[i].level, level)) {
      return;
    }
    transports[i].call(module.exports, msg);
  }
```

This is the part where the logic error lays. If the first transport is not a function the for loop will be canceled because of the return statement. And if i disable the console transport the typeof the console transport is boolean. So nothing will be logged.

My 'patch' is the following code:

```
var transports = module.exports.transports;
  for (var i in transports) {
    // jshint -W089
    if (transports.hasOwnProperty(i) && typeof transports[i] == 'function') {

      if (!compareLevels(transports[i].level, level)) {
        return;
      }
      transports[i].call(module.exports, msg);
    }
  }
```

**Comment by megahertz** [comment]
Hi Daniel. It seems that you're using an old version. Just update to the latest.

**Comment by dbelz** [comment]
Im very sorry :D. Have not checked this before. Thank you for the fast reply! :)
