### ISSUE TITLE
log.transports is always undefined

### ISSUE THREAD

**Issue by kalehv** [megahertz/electron-log#100]
I am using it as follows in rendered (typescript)
``` typescript
import * as Log from 'electron-log'

export default class Logger {
  constructor() {
    Log.transports.file.level = 'info'
  }
}
```

It errors out saying `Uncaught TypeError: Cannot read property 'file' of undefined.` Am I using it wrong?

**Comment by megahertz** [comment]
You should configure transports in the main process only.
