### ISSUE TITLE
[Question] Is it possible to create a custom transport?

### ISSUE THREAD

**Issue by buddythumbs** [megahertz/electron-log#103]
Hi,

Thanks for this repo - it has proven extremely useful!

I am wondering if there is a way to setup a custom transport so that I can send logging to remote server?

Something like:

```
log.transports.remote = function(msg) {
  var text = util.format.apply(util, msg.data);
  axios.post('www.remote-server/api',`[${msg.date.toLocaleTimeString()} ${msg.level}] ${text}`)
  ...
};
```

Or should I just add this to my file transport?

**Comment by megahertz** [comment]
Hi. Yes, you can define your transport by this way. Don't forget to set log.transports.remote.level. Also, you can take a look at logS transport (it's renamed to remote in v3.0.0-beta).

**Comment by megahertz** [comment]
Feel free to reopen if you still have a questions about a custom transport.

**Comment by buddythumbs** [comment]
No problem - I have it working!! Thanks!
