### ISSUE TITLE
Is there a possible way to change the default log.old.log file path and number of log files?

### ISSUE THREAD

**Issue by Oliverq755** [megahertz/electron-log#104]
I was working on the project recently where I came in need of **provide a manual path for a log.old.log file**. I couldn't get anywhere in the documentation for doing so. 

Along with this, is there any possible way to manage the **number of log.old.log files** which is being created once the log file exceeds the **maxsize**?

Conclusion: 
Requirement: 
1. maxlogfile: number
2. log.old.log manual path

**Comment by megahertz** [comment]
I'm not going to implement a complex log rotation scenario, but I can add an option which allows to override the current behavior.

**Comment by Oliverq755** [comment]
can you elaborate on the option and their behavior?

**Comment by megahertz** [comment]
ok, I'm going to publish a new beta on the next week.
