### ISSUE TITLE
File not generated

### ISSUE THREAD

**Issue by MehediH** [megahertz/electron-log#105]
Hi, for some reason the module is not even generating a logs file for me. I haven't changed any of the default settings, simply imported the library and did `log.info("hi");` 

However, that is not generating a log file and there is no file under AppData/Roaming/app. 

I tried deleting my node_modules folder and doing npm install again, but that didn't help.  Any ideas?

**Comment by megahertz** [comment]
Hi @MehediH . Set file log level to info.
