### ISSUE TITLE
Prepend source of log entry?

### ISSUE THREAD

**Issue by Slapbox** [megahertz/electron-log#106]
In a multi-window setup it would be great to be able to prepend the source window's name to the log entry. I have a feeling this is already possible and I'm just overlooking how to do it.

@megahertz do you have any advice on this? Thanks for sharing this great project!

**Comment by megahertz** [comment]
You can use v3 beta and a custom variable

```js
log.variables.process = 'win1';
log.transports.file.format = '[{h}:{i}:{s}.{ms}] [{process}] {text}';
```

**Comment by Slapbox** [comment]
@megahertz thanks so much for taking the time to clarify that!
