### ISSUE TITLE
Log show twice and missing debug log

### ISSUE THREAD

**Issue by kenhuang** [megahertz/electron-log#107]
I have the following code in my renderer process, any reason why the log show twice? Also why debug log is missing? The project was setup mostly via `electron-react-boilerplate`, really appreciate your help in advance.

```
    Logger.info('onNetworkStatusClick info');
    Logger.debug('onNetworkStatusClick debug');
    console.debug('onNetworkStatusClick debug');
    Logger.warn('onNetworkStatusClick warn');
    Logger.error('onNetworkStatusClick error');
````
<img width="821" alt="screen shot 2019-01-23 at 10 19 58 pm" src="https://user-images.githubusercontent.com/205194/51596341-9db7d180-1f5d-11e9-8289-4beee6023ced.png">

**Comment by megahertz** [comment]
Try to install electron-log@beta. Does it solve your problem?

**Comment by megahertz** [comment]
Feel free to reopen if v3 doesn't solve this problem.
