### ISSUE TITLE
Version 3.0.0-beta2: error thrown when logging `undefined` - TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by aguynamedben** [megahertz/electron-log#110]
Thanks for this great library. I think I may have found a bug in 3.0.0-beta2.

When I run
```js
log.debug(undefined);
```

I get the following error
![image](https://user-images.githubusercontent.com/107841/52023358-a35b6d00-24b1-11e9-9abb-84c5253287eb.png)

It looks like this line of code has some assumptions I wouldn't expect:
https://github.com/megahertz/electron-log/blob/master/lib/log.js#L14

Version: 3.0.0-beta2

FWIW, `console.log(undefined)` doesn't throw an error. I'd not expect electron-log to throw an error when logging undefined.

**Comment by megahertz** [comment]
Thank you, will fix today.

**Comment by megahertz** [comment]
Fixed in 3.0.0-beta4

**Comment by aguynamedben** [comment]
@megahertz you da bomb... thanks for the time you put into this project, we love it.
