### ISSUE TITLE
findLogPath returns false

### ISSUE THREAD

**Issue by samsamm777** [megahertz/electron-log#113]
I need to be able to find the path where the logs are created. findLogPath always returns false. Any help?

`const path = log.transports.file.findLogPath();`

**Comment by megahertz** [comment]
Which OS? Does `log.transports.file.findLogPath(yourAppName)` return false?

**Comment by samsamm777** [comment]
OSX. And yes, passing the app name also yields false.

**Comment by megahertz** [comment]
What is the output of  `ls -l ~/Library/Logs`?

**Comment by samsamm777** [comment]
I upgraded to to the last version, and its now working. Thanks.
