### ISSUE TITLE
findLogPath returns wrong path

### ISSUE THREAD

**Issue by samsamm777** [megahertz/electron-log#114]
Version: "electron-log": "3.0.1"

When calling `findLogPath` it returns the application support directory and not the logs directory path.

`const p = log.transports.file.findLogPath('appname');`
returns:
/Users/username/Library/Application Support/appname/log.log
should be:
/Users/username/Library/Logs/appname/log.log

**Comment by megahertz** [comment]
What is the output of `ls -l ~/Library/Logs`?

**Comment by samsamm777** [comment]
It outputs my logs directory. There is a directory in there which is my app name, which contains the logfile im looking for.

**Comment by megahertz** [comment]
It's strange things. I'll try to reproduce the bug on this week. Which Electron version do you use?

**Comment by samsamm777** [comment]
@megahertz Any luck reproing this?

**Comment by megahertz** [comment]
@samsamm777 I can't reproduce this problem. I'll try to investigate this problem later, since I have no time for it now. You could create a simple project which reproduce the problem, it allows me to fix it much faster.

**Comment by megahertz** [comment]
Fixed in v4
