### ISSUE TITLE
Electron -log after packing problem

### ISSUE THREAD

**Issue by Lesliegc** [megahertz/electron-log#115]
The electron-log plug-in is installed in the file. After being packaged into an exe file, an error cannot be found. However, log dependencies can be used for local operation？ @

**Comment by megahertz** [comment]
Please provide more information

**Comment by Lesliegc** [comment]
- [ [
![image](https://user-images.githubusercontent.com/34731633/53865057-10ba6a80-4029-11e9-9970-d04819700ce9.png)
](url)

**Comment by Lesliegc** [comment]
Launching locally without an error log plug-in, packaged in exe format, will tell you that the module is not found, and in fact the electron-log is installed

**Comment by megahertz** [comment]
It's something wrong in your build process. Check if 'electron-log' exists in dependencies section of package.json.

**Comment by Lesliegc** [comment]
[
![image](https://user-images.githubusercontent.com/34731633/53867157-31d18a00-402e-11e9-948a-816c72984bac.png)
](url)

**Comment by Lesliegc** [comment]
Yes，Now this project is a electron project that I made and packaged by myself. When I want to package it into an exe file, I can still check the log. But the above error is reported.

**Comment by megahertz** [comment]
You have either wrong build configuration or wrong webpack config.

**Comment by Lesliegc** [comment]
[
![image](https://user-images.githubusercontent.com/34731633/53869902-17021400-4034-11e9-877d-1d354149a29a.png)
](url)

**Comment by Lesliegc** [comment]
Can I show you my main process configuration for electron-log? Since I have a package. Json file locally, I can run the log. I also have a package

**Comment by Lesliegc** [comment]
Is there a build configuration error？

**Comment by H3llsing** [comment]
make sure that you have run npm install after adding it to the package.json.
otherwise the node_modules folder does not contain the dependency and will not be copied to your dist folder

**Comment by megahertz** [comment]
@Lesliegc I can't recommend you to use multiple package.json. Electron-builder used a similar approach a few years ago. But now it's deprecated since it leads to thousands issues like this.

**Comment by Lesliegc** [comment]
The current situation is that the electron-log module can be viewed by the local environment, but the module was not introduced after packaging. May I ask if you have encountered similar situation or the solution

**Comment by H3llsing** [comment]
> The current situation is that the electron-log module can be viewed by the local environment, but the module was not introduced after packaging. May I ask if you have encountered similar situation or the solution

yes i use also two `package.json` and `electron-packager`. 
When you package everything together i encountered similar problems, because i forgot to copy the node_modules into the `app_name/resources/app/node_modules`
the main.js which must be palced into `app_name/resources/app/` requires the node_modules you are using inside the main.js.

i guess if you run now an `npm install` in your build folder the app.exe can find every module

**Comment by Lesliegc** [comment]
Thank you, I will try to see tomorrow, I hope to get good results

**Comment by Lesliegc** [comment]
I wrote the electron on react. Now the situation is that the electron-log has been installed. I want to check the local log in the packaged file, but there is no error report of the electron-log module after being packaged

**Comment by megahertz** [comment]
So, is you problem solved?

**Comment by Lesliegc** [comment]
Yes, this is fixed. Add this line of code --asar --ingore=./node_modules/electron-log --extra-resource=./node_modules/electron-log -- into the packaging command to force the third-party dependencies into resources
