### ISSUE TITLE
Loop when using log.info in combination with foo.webContents.on event 'console-message'

### ISSUE THREAD

**Issue by joost-albers** [megahertz/electron-log#116]
In my app i start a browserWindow that loads a url, 
I do not control the contents of the web page hosted at this url 
The people hosting the contents would like to see the console log which they generate in their js scripts by running console.log(whatever they find important)

For the sake of simplicity lets call the website that is being loaded webcontents X

I wanted to use electron-log for this but i ran into some issues. I am probably doing something wrong but could use some pointers.

At first i tried loading electron-log in the renderer.js expecting all 'console.log' operations in webcontents X to be logged to file and console.

This however did not plan out as expected. I have tried several methods for loading the electron-log module into the renderer.
allthough it does not throw any errors it also does not log.

I then added in main, a callback on the webcontents X by calling.

```
fg.webContents.on('console-message', (event, level, message, line, sourceId) => {
  log.info(message)
})
```

this somewhat works but it ends in a loop and keeps on logging the same message over and over again running at 100% cpu.

I mitigated this by adding an if statement that only calls log.info when the sourceId equals or contains the loaded url.

```
fg.webContents.on('console-message', (event, level, message, line, sourceId) => {
  log.info(message)
  if (sourceId.indexOf('http://thaturl') > -1)
  {
    log.info(message)
  }
})
```

Although it works I would prefer to avoid these kind of specifics.

Can you tell me if i am doing something wrong , there is a potential bug or there is a better way.

Most important thing to note is that webcontents X is out of my control and hosted by another company.

thanks.

**Comment by megahertz** [comment]
By default the lib repeated messages from the main process in a renderer when application is not packaged. To disable this feature, set in the main process `log.transports.rendererConsole.level = false`.

**Comment by joost-albers** [comment]
Thanks for the response
I am seeing this in the unpackaged version also in log.log.

i am now running something like the below.
```
    if (sourceId.indexOf('console.js') < 1)
    {
      log.warn(message)
    }
```
which seems to be a bit hacky. Perhaps i am not understanding the global concept.

if i load a web page (public website) into a browserWindow
And that webpage's js calls console.log()
How would i ensure these particular console.logs end up in the log.log file.
can this be done without adding the webContents.on('console-message',....  event listener?

**Comment by megahertz** [comment]
There are two ways of logging such a messages:
- subscribe to 'console-message' (as in your code). 
- patch console.log `console.log = log.log` in preload script.

I think patching is much more dirty solution. So in your situation it's pretty good approach listening 'console-message'. Just disable rendererConsole transport to have no problem with infinite loop as described above.

**Comment by joost-albers** [comment]
Thanks for the awesome module and quick responses. I will close the issue.
