### ISSUE TITLE
Issues logging objects

### ISSUE THREAD

**Issue by sloantash** [megahertz/electron-log#117]
I'm having an issue logging objects. At first I thought it was jQuery objects only, but it seems to be something else. On logging certain (but not all) objects, the app completely locks up and cannot be quit. The console shows a log of the object and this warning - 
node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/ipc-renderer.js:10 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

At this point, the app becomes completely non-responsive. I'm guessing it has to do with complexity of the object, maybe? 
Any helpful ideas would be greatly appreciated.

**Comment by megahertz** [comment]
Try `log.transports.mainConsole.level = false`

**Comment by sloantash** [comment]
That worked great! Thank you so much. Would you mind explaining what was happening?

**Comment by megahertz** [comment]
mainConsole transport uses IPC. IPC in electron is good for transporting simple objects between processes. But when such objects become too large/complex or IPC is called too frequently it can lead to such a problem.
