### ISSUE TITLE
Enabling main and rendered console logging

### ISSUE THREAD

**Issue by pleinonen** [megahertz/electron-log#119]
Newbie question: From the docs I understand that mainConsole and rendererConsole transports are disabled by default due to performance issues. Docs also tell me how to disable existing transport by setting level to false but I cannot find information I can enable these transports? Setting level to true or some other level does not work as these seem to be null. Did I miss something from the docs?

**Comment by megahertz** [comment]
rendererConsole transport is not available in renderer process, so you are able to change its value only in main. The same for mainConsole and main process.
