### ISSUE TITLE
Webpack friendliness

### ISSUE THREAD

**Issue by mbaer3000** [megahertz/electron-log#12]
When using electron-log as a dependency in a renderer app to be served from a non-file URL, it is not possible to exempt it from webpack's bundling (using: externals: { 'electron-log': 'commonjs electron-log'}). However, the dynamic require in the loadAppPackage function complicates the bundling a lot, requiring one to use "exprContextRegExp: /$^/, exprContextCritical: false" in the webpack config.

When setting the appName property, the whole function becomes redundant - in the findLogPath function there is a line: "appName = appName || findAppName()", so loadAppPackage() is never called when the appName property is set.

Could we get electron-log to be more webpack friendly in this respect? I'd figure that pulling the offending code out, possibly doing something like a require('./findAppName') would simplify things for webpack, which could then use some ignore or noop plugin or whatever to patch the function.

**Comment by megahertz** [comment]
I'm going to make a separated package like electron-log-renderer which sends log messages to original electron-log through ipc, but I don't know when I'll start.

**Comment by mbaer3000** [comment]
Really, I don't take issue with there being a fully-fledged electron-log in the renderer app. The problem is the dynamic require() in the loadAppPackage function, which trips up webpack. The webpack problem is the same, no matter whether bundling for main or for (non-file URL) renderer -- the only difference being that for the main build one can put the electron log package in a folder along with the main-bundle.js which node then (along with downstream dynamic require() imports) happily resolves at runtime.

**Comment by megahertz** [comment]
Is it possible to solve this problem by replacing require to fs.readFileSync inside loadAppPackage()?

**Comment by mbaer3000** [comment]
That sounds like it would indeed solve the issue, yes!

**Comment by megahertz** [comment]
I'll try to make it in a few days.

**Comment by megahertz** [comment]
@mbaer3000 try a new version

**Comment by mbaer3000** [comment]
Looks good. Webpack now runs through without hiccups. A final thing, though: If one doesn't set the appName, the loadAppPackage function throws an Error. Which can be prevented by replacing:

`var packageFile = find(path.dirname(require.main.filename)) || find(process.cwd());`

with

`var appEntryPoint = (require.main && require.main.filename && path.dirname(require.main.filename)) || process.cwd();
var packageFile = find(appEntryPoint);`

I'd appreciate your consideration.

**Comment by megahertz** [comment]
try v1.1.1

**Comment by mbaer3000** [comment]
Works just fine for me. Thank you sir!

**Comment by megahertz** [comment]
You're welcome!
