### ISSUE TITLE
multiple log files with different log levels

### ISSUE THREAD

**Issue by gozzoo** [megahertz/electron-log#120]
Is it possible for a log message to appear in multiple log files with depending on their configurations?

For example I'd like all log messages to go to my main log file `myapp.log` and only the error messages to go to `error.log`?

Can I specify multiple file transports, like this?

```
log.transports.file1
log.transports.file2
```
or
```
log.transports.file.1
log.transports.file.2
```

**Comment by megahertz** [comment]
There is no straightforward way. You can write a custom hook which changes log.transports.file.file depending on a message level.

**Comment by megahertz** [comment]
Fixed in v4 (use resolvePath function)

**Comment by gozzoo** [comment]
That's great news, but I don't see v4 to be released yet. When is this supposed to happen?

**Comment by megahertz** [comment]
Beta is available, I'm going to publish a release in the beginning of December.

**Comment by gozzoo** [comment]
OK, great. Thanks for creating, maintaining and improving this project.
