### ISSUE TITLE
Colors not working when using Electron

### ISSUE THREAD

**Issue by MrAmericanMike** [megahertz/electron-log#121]
I'm experiencing some issues with the outputs. I can see the colored outputs without any problem when I run a .js file with node, however when I run it as electron I don't see colors but instead weird characters.

What am I missing?

![logs](https://i.imgur.com/LkWJzsD.png)

**Comment by megahertz** [comment]
Which OS and electron versions?

**Comment by MrAmericanMike** [comment]
This is on Windows 7
Electron version is 4.1.1 
Electron-Log version is 3.0.1

Happens on Visual Studio Code Terminal, and also when using Cmder.
Sorry not sure what you mean about the Shell itself.

PS: The problem is the same with Electron-Log / Winston / Electron-Timber

**Comment by megahertz** [comment]
It seems that it's not possible to fix this problem completely, so now it disables colors when a program isn't attached to TTY.
