### ISSUE TITLE
initialize the logger

### ISSUE THREAD

**Issue by gozzoo** [megahertz/electron-log#124]
This is a feature request.

I'd like to be able to specify and configure only the transports that I need.

Here is what it might look like:

```
log.init({
  transports: [
    new transports.Console({format: '{text}'}),
    new transports.File({ fileName: 'error.log', level: 'error' }),
    new transports.File({ fileName: 'combined.log' })
  ]
});
```

**Comment by megahertz** [comment]
I've thought about this feature earlier and decided to keep the module as singleton. But if you really need this feature, you can copy code of index.js, it allows to make a new instance.

**Comment by gozzoo** [comment]
I also mean for the logger to be a singleton. It can work like this: if on the furst call of `log.log(...)` there is no configuration the default configuration wiil be used.

**Comment by megahertz** [comment]
I meant, you can just create a function like
`function createCustomLogger() {
// here is a code similar to index.js
}`
So you don't need to make a fork. Actually index.js is just a facade which creates such a singleton. 

I thought about create() function, but there are a few reasons why I decided not to implement it in this version. At least, renderConsole and mainConsole can't work correctly when there are a few instances. Maybe I'll add such a function in v4, but I have no exact plans for this version yet.
