### ISSUE TITLE
Excessive data volume leads to process stuck

### ISSUE THREAD

**Issue by mtrucc** [megahertz/electron-log#127]
```
// IN RENDERER PROCESS
import log from 'electron-log'
log.transports.file.sync = false
console.log = log.info
```

But excessive data volume leads to process stuck

I use 

`var log4js = require('log4js');`

There will be no such problem, I guess it may be that IPC does not allow too much data to be sent.
I set "sync" is "false" but no effect

**Comment by mtrucc** [comment]
I just tested it again, the data can be recorded in the log file, but the program will get stuck later.

**Comment by megahertz** [comment]
1. Don't use async mode when heavy load, it requires a few improvement for such a case.
2. Disable rendererConsole and mainConsole transports.

**Comment by mtrucc** [comment]
To this end, I read your code, I found that most of the logs will be sent through IPC, I commented on the file read and write part, found that it is not caused by file reading and writing, the specific reason I am not sure. I will try the method you said.

**Comment by mtrucc** [comment]
```
log.transports.file.level = false;
log.transports.console.level = false;
```
Unfortunately, I just experimented, plus the above two lines of code, but no effect, and I looked at the documentation, mainConsole will send data to renConsole, but I press F12 to bring up DevTool, did not see mainConsole

**Comment by megahertz** [comment]
https://github.com/megahertz/electron-log/issues/122

**Comment by mtrucc** [comment]
```
log.transports.file.level = false;
log.transports.console.level = false;
```
I have used the above code, but it has no effect and will still be stuck.

**Comment by megahertz** [comment]
Read my suggestion in #122 again.

**Comment by mtrucc** [comment]
Unfortunately, I can't find the reason, and I can't give a sample program that can be reproduced.
I only know that in the lib\log.js file, comments
```
function log(electronLog, level) {
  var transports = filterTransportsByLevel(electronLog, level);

  for (var i in transports) {
    if (!transports.hasOwnProperty(i) || typeof transports[i] !== 'function') {
      continue;
    }

    var data = splitMessagesAndStyles(Array.prototype.slice.call(arguments, 2));

    var msg = runHooks(electronLog.hooks, transports[i], {
      data: data.messages,
      date: new Date(),
      level: level,
      variables: electronLog.variables,
      styles: data.styles
    });

    if (msg) {
      transports[i](msg);
    }
  }
}
```
`transports[i](msg);` Is unreasonable

I load electron-log in preload.js
```
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false,
      preload: path.join(__dirname, 'preload.js')
    }
  })
```
preload.js
```
const log = require('electron-log');
log.transports.file.level = false;
log.transports.console.level = false;
window.Electron.log = log
```
index.html
`window.console.log = Electron.log.info`

I use

`var log4js = require('log4js');`

There will be no such problem
I can't find a reason, in the end I can only use log4js

**Comment by megahertz** [comment]
You don't need to disable file and console transport. You need to disable rendererConsole and rendererMain transports.

**Comment by megahertz** [comment]
In v4 you only need to disable `ipc` transport in both processes.
