### ISSUE TITLE
Error in renderer process: statSync is not a function

### ISSUE THREAD

**Issue by Yudikubota** [megahertz/electron-log#129]
Hi,

When I try to log in the renderer process, I get the following error:

![Captura de tela de 2019-04-01 09-12-56](https://user-images.githubusercontent.com/22172999/55326560-71896700-545e-11e9-8f16-515c749b6aaa.png)

Then, if I set the _appName_

`ELogger.transports.file.appName = 'Foo'`

it delivers another error:

![Captura de tela de 2019-04-01 09-13-24](https://user-images.githubusercontent.com/22172999/55326562-71896700-545e-11e9-9154-27e9ddbdbf8f.png)

**Versions**
"electron": "^3.0.10",
"electron-log": "^3.0.4",

**Comment by Yudikubota** [comment]
Solved by importing _electron-log_ with `window.require`

Changed from

`import ELogger from 'electron-log'`

to

`const ELogger = window.require('electron-log')`

**Comment by megahertz** [comment]
Hm... Glad you've solved the problem. Do you use webpack?

**Comment by Yudikubota** [comment]
Yeah
