### ISSUE TITLE
Video asset loading error

### ISSUE THREAD

**Issue by 1inarow** [megahertz/electron-log#131]
When playing a video that isn't there I have to turn off catchErrors because I get a subsequently logged error afterwards in the console.js file. I can disable when the error object gets renamed, but they i just get an `undefined` in the output file.

`reason.name = 'UnhandledRejection ' + reason.name;`

`GET file:///C:/Users/user/Documents/GitHub/video-player/assets/video/video.mp4 net::ERR_FILE_NOT_FOUND`

`C:\Users\user\Documents\GitHub\video-player\node_modules\electron-log\lib\transports\console.js:72 
12:33:10 TypeError: Cannot assign to read only property 'name' of object ''
    at onRejection (C:\Users\user\Documents\GitHub\video-player\node_modules\electron-log\lib\catchErrors.js:49:19)
    at onRendererRejection (C:\Users\user\Documents\GitHub\video-player\node_modules\electron-log\lib\catchErrors.js:66:5)`

**Comment by megahertz** [comment]
Thanks for the report, will fix soon.
