### ISSUE TITLE
file.clear() method not working

### ISSUE THREAD

**Issue by fjrial** [megahertz/electron-log#132]
Hi megahertz: 

Today I started to use your library in an Electron app which I am building (Windows 64 bit)

The logging functionality to a file is awesome, but I was trying to clear the log file every time the app starts, but it didn't clear the log file.

So looked at the source code and saw the clear() method defined like this:
`function clear() {
    try {
      fs.unlinkSync(transport.file);
    } catch (e) {
      logConsole('Could not clear log', e);
    }
  }`

I'm using your library like this (in renderer/main.js):
`const log = require('electron-log');
//disable the logging to the console
log.transports.console.level = false;
//only file (log.log) allowed right now
//empty the log file before starting to write 
log.transports.file.clear();
//enable log
console.log = log.info;`

And, debugging your clear method, saw that the transport.file value is "null". Because I didn´t define the log file (used default one "log.log")

So, changed the clear method to this
`function clear() {
    try {
      fs.unlinkSync(findCurrentLogPath(transport));
    } catch (e) {
      logConsole('Could not clear log', e);
    }
  }
`

and it worked fine.

Thanks for your library.

**Comment by megahertz** [comment]
Thank you, will fix soon.
