### ISSUE TITLE
file not generated when application is installed by appx

### ISSUE THREAD

**Issue by cargreg** [megahertz/electron-log#133]
When i start the application with npm start the file will be created , but after the installation by the appx, the log file will not be generated, the path is correct and the application works fine

**Comment by megahertz** [comment]
Appx application is run in isolated environment, so it has no real access to filesystem. You can try to experiment with a manifest to get the corresponding permissions. I'm not familiar with it so I can't give you an advice.

**Comment by megahertz** [comment]
I think you're able to read a log file from your application. Maybe it's enough for your purposes.
