### ISSUE TITLE
Elaborate on v3 changes

### ISSUE THREAD

**Issue by pronebird** [megahertz/electron-log#135]
Hi,

Could you please elaborate on the v3 changes regarding the transport configuration.

I used to configure the file log in the main process and then both renderer and main logs end up in the same file. How do you achieve the same in electron-log v3?

**Comment by megahertz** [comment]
In v3 logger in main process and in all renderer are configured separately.

**Comment by pronebird** [comment]
So there is no way to save all logs into one file anymore?

**Comment by megahertz** [comment]
Why not? It's default behavior.

**Comment by pronebird** [comment]
Ok cool, I had impression that "configured separately" means that I have to set up the file transport twice for two different file targets. 👍

**Comment by pronebird** [comment]
I've spent some time playing with the logging and I still don't understand how it works.

In the main process I do this:

```ts
import log from 'electron-log';

const format = '[{y}-{m}-{d} {h}:{i}:{s}.{ms}][{level}] {text}';

log.transports.console.level = 'debug';
log.transports.console.format = format;
log.transports.file.level = 'debug';
log.transports.file.format = format;
log.transports.file.file = '/Users/tiger/test.log';
```

renderer:

```
import log from 'electron-log';

const format = '[{y}-{m}-{d} {h}:{i}:{s}.{ms}][{level}] {text}';

log.transports.console.format = format;
log.transports.console.level = 'debug';
```

But the stuff logged in renderer never appears in the log file.

It would be great to improve the documentation.

**Comment by megahertz** [comment]
The both logger are independent. So if you change file location in the main process, you also need to change it in a renderer

**Comment by pronebird** [comment]
I see, but that means there will be two independent writers into the same file or am I missing something? I think this will eventually lead to the same file being overwritten by one file logger or the other.

**Comment by megahertz** [comment]
Theoretically, yes, but in my previous test I have no such a problem. Anyway, I'm going to create a test for such a case in April to check how the the module on high load.

**Comment by pronebird** [comment]
I just skimmed through the source code and it seems that the file logger uses `fs.writeSync` to append a single line to file.

https://github.com/megahertz/electron-log/blob/master/lib/transports/file/index.js#L74

I am mildly surprised because I thought the file logger would maintain the open file and maybe "flush" stuff on disk from time to time to ensure that the data is written on disk. 

I am not entirely sure, but I think doing logging this way is quite expensive, because each `fs.writeSync` would open file in "append" mode, then write in it, then close it. Having an open descriptor to file must be cheaper since the file would always be open.

**Comment by megahertz** [comment]
Theoretically it's ineffective. But in a real situation, there is no big difference since any modern OS does it for you. It doesn't write the data to a disk immediately. So in my tests it was 0 to 20% slower. The same for async writing.

**Comment by pronebird** [comment]
Of course there is some buffering going on before the data hits the disk, but that's why we have a `flush` functionality to ensure that its written if we want such guarantees. 

I guess the more major problem that I see is when both renderer and main processes attempt to write into the same file, I just don't believe that Node.js is going to arbitrate the file access at this point.

**Comment by megahertz** [comment]
Yes, you're right. That's why I'm going to dive into it later.

**Comment by pronebird** [comment]
Thanks man 👍

**Comment by grantcv1** [comment]
So if the main process and the renderers are all configured separately, what happens if I don't configure the file maxSize the same in all my renderers and the main process?

**Comment by megahertz** [comment]
@grantcv1 both configs are independent. So it maxSize of main is 1mb  and maxSize of renderer is 2mb, the main process rotates log when it exceeds 1mb, despite to renderer settings.

**Comment by avner-hoffmann** [comment]
@megahertz - Can you shed more details on what exactly is configured separately?
If I set a different log file name on the main and renderer process - will 2 log files be created?
What about level, format, maxSize. The documentation is not so clear about it...

Another question - when setting nodeIntegration to false, you can require electron-log from the renderer process. If one wants to use it in the renderer process the package needs to be exposed through a preload script and a bridge object. 
In that case the separate configurations for the main and renderer process isn't relevant?

**Comment by megahertz** [comment]
@avner-hoffmann Each electron process has its own independent electron-log instance, that's why all options should be configured in each process. There is no difference between configuring electron-log in renderer process (when nodeIntegration is enabled) and in preload script.

**Comment by megahertz** [comment]
Closed since in v4 the different processes uses different files. For issues with simultaneous file access I keep #126 opened.
