### ISSUE TITLE
Console level does not affect mainConsole / rendererConsole

### ISSUE THREAD

**Issue by pronebird** [megahertz/electron-log#138]
Hi,

I am not able to disable the logging to console by resetting the `console.level` to `false`:

```ts
import log from 'electron-log';

log.transports.console.level = false;
log.transports.file.level = false;
```

However resetting the `mainConsole` or `rendererConsole` does the trick.

```ts
// renderer.ts
log.transports.mainConsole = null;

// main.ts
log.transports.rendererConsole = null;
```

Is there any correlation between the `mainConsole`, `rendererConsole` and the `console` transport itself. I think it would be logical if `main` and `renderer` consoles obeyed the `console` settings.

**Comment by megahertz** [comment]
Hi, It'll be fixed in v4
