### ISSUE TITLE
it cant log to file in middleware of redux

### ISSUE THREAD

**Issue by Hybueno09** [megahertz/electron-log#140]
my app is based in [https://github.com/electron-react-boilerplate/electron-react-boilerplate](url).But in redux middleware created by web worker(e.g. socket server connect middleware), it cant log to file,otherwise it can log to console conrrectly.
Why, thx

**Comment by megahertz** [comment]
Could you give me a code sample to repriduce the problem?

**Comment by megahertz** [comment]
Try v4. Please let me know if it doesn't solve your problem.
