### ISSUE TITLE
If archiveLog fails, log size continues to grow.

### ISSUE THREAD

**Issue by pattrickrice** [megahertz/electron-log#145]
Say that we've changed the file path to something in /var/log/ and the application doesn't have root permission. The log will attempt to archiveLog when hitting the max filesize, but then fail on rename:
` electron-log.transports.file: Could not rotate log Error: EACCES: permission denied, `

The log will then continue to write to the file, blowing the limit we've set.

**Comment by megahertz** [comment]
What is expected behavior?

**Comment by pattrickrice** [comment]
I think I would expect the log size to not exceed it's maxSize. Additionally, this exception should be re-thrown: 
https://github.com/megahertz/electron-log/blob/5c51ec518358a0ec2c533e5b62f024d48acdd60b/lib/transports/file/index.js#L97

**Comment by megahertz** [comment]
Currently, log file is rewritten (keeping some amount of old records) when log rotation is failed.
