### ISSUE TITLE
file size grows infinitely if the log file extension is not ".log"

### ISSUE THREAD

**Issue by syonip** [megahertz/electron-log#146]
I think the culprit is this line in `archiveLog` function:
```
fs.renameSync(stream.path, stream.path.replace(/log$/, 'old.log'));
```
If you set the log file name to `logfile.txt` it grows forever.

I think the suffix `.old` should just be added to the end of the filename, whatever it is.
I'm happy to open a PR

**Comment by megahertz** [comment]
It seems that you use some old version.

**Comment by syonip** [comment]
yes you're right, I was stuck in version 2. Thanks :)
