### ISSUE TITLE
Log files inside `log` directory, with multiple files of different names.

### ISSUE THREAD

**Issue by ll931217** [megahertz/electron-log#147]
Hello megahertz,

I want to put all of my log files inside the `%APPDATA%/<AppName>/logs` folder, and also have each log file name changed to something else. How would I go about doing that?

The only solution I can think of is just setting the entire `log.transports.file.file`, but is there a better method of doing it? I think it would be a good idea to set the log directory ourselves and the log file name, making the plugin more flexible.

log.transports.file.file = path.join(process.env.APPDATA, 'erack/logs/mes.log')

**Comment by megahertz** [comment]
Hi. At this moment, I'm not going to add a new option which changes log directory name. But there are a few workarounds:
 - set file.appName to `path.join('erac', 'logs')`
 - set file.file to `path.join(app.getPath('logs'), 'logs')` - in this case you should create logs folder manually

**Comment by ll931217** [comment]
Okay thank you!
