### ISSUE TITLE
disable log rotation and keep updating the default log file

### ISSUE THREAD

**Issue by avner-hoffmann** [megahertz/electron-log#150]
Hi, this is a feature request.

Is it possible to implement a different behavior for when the log file exceeds its size?
Instead of log rotation (or in addition), to keep updating the same log.log file in a way that for each new line that needs to be added, the oldest line will be deleted and the file will keep a persistent "maxSize" size.
We find this feature highly needed instead of handling two files (cause you can never know when a log rotation happened and if the log.log file contains enough data or you have to open the log.old file as well).

Thanks

**Comment by megahertz** [comment]
You could override transports.file.archiveLog function to implement custom behavior.

**Comment by avner-hoffmann** [comment]
@megahertz - How? Do you have any documentation on this? When is it gets called, what should it do?
This feature requires not only a change to the archive log function but also for the default behavior of the main log function...
