### ISSUE TITLE
Log file not generated on macOS in packaged app

### ISSUE THREAD

**Issue by sibljon** [megahertz/electron-log#152]
As soon as I run my packaged app, the directory `~/Library/Logs/myapp/` is created, but no log file is ever created. However, the log file gets created when I run from source. My app is code signed (not that I think that that matters, though).

I'm running the following code from my entry file (`package.json.main`):

```
const log = require("electron-log");
log.transports.file.level = "silly";

// I've tried it with and without this line:
log.transports.file.file = "~/Library/Logs/my app/log3.log";

// I see plenty of logs when I run the app from source (not the packaged, distributed form)
log.transports.console.level = "silly";

// I also don't see logs in the chrome dev tools console when I open them in my packaged app
log.transports.rendererConsole.level = "silly";

log.info("can you see me?")
```

Any ideas? I've looked through every Github issue in this project that seems even remotely related, so I'm out of ideas.

**Comment by megahertz** [comment]
Run your packaged application from command line and check the console output.  At least, "~/Library/Logs/my app/log3.log" will not work since ~ is not resolved automatically.

**Comment by sibljon** [comment]
Thank you for your response, @megahertz 

> Run your packaged application from command line and check the console output.

Could you be more specific? Are you talking about `open /path/to/app.app` ?

Or are you talking about running the app from source with `electron .`? When running this way, I'm able to observe console output.

The reason I need to print to file, actually, is that I don't know any other way to read logging (print statements) to debug what I'm currently working on: autoUpdate functionality, which can only be done completely on the packaged app.

**Comment by megahertz** [comment]
@sibljon I mean `App.app/Contents/MacOS/App`

**Comment by sibljon** [comment]
Oh, very cool! I didn't know that you could get console output that way. Thank you!

Here's what I see:

```
$ /Users/me/code/app/dist/App.app/Contents/MacOS/App
2019-08-01 08:51:56.382 Spruce Health[38935:3629593] *** WARNING: Textured window <AtomNSWindow: 0x7fa597608bd0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

... and I don't see any of my `console.log()` or `log.info()` statements statements. The only thing printed to the terminal is `*** WARNING: Textured window...`, and that's also printed when I run from source with `electron .`.

**Comment by sibljon** [comment]
Update: after adding `--enable-logging` (so: running from terminal as `/Users/me/code/app/dist/App.app/Contents/MacOS/App --enable-logging`), I now see parity with what I see in the Chrome DevTools; however, I'm not able to see any `console.log()` or `log.info()` or `log.error()` still.

**Comment by megahertz** [comment]
do you run console.log in the main process?

**Comment by sibljon** [comment]
Yes, I'm running `console.log` from the main process, I believe. Here's more detail, since I'm new to Electron and might not know what I'm talking about 😆:

`package.json.main` is a file called `electron.js` In that file, I call both `log.error` and `console.log` pretty much right away: after the `import` statements at the top of the file:

```
const { app, BrowserWindow, Menu } = require("electron");
const path = require("path");
const isDev = require("electron-is-dev");
const { autoUpdater } = require("electron-updater");

var log = require("electron-log");
log.transports.file.level = "silly";
log.transports.console.level = "silly";
log.transports.rendererConsole.level = "silly";
autoUpdater.logger = log;
```

And later on in the same file:

```
app.on("ready", () => {
  log.info("App ready...");
  console.log("App ready...");
});
```

None of the logging statements show up except for when I run from source via `electron .`. In other words, it doesn't show up in the terminal when I run the app with `/Users/me/code/app/dist/App.app/Contents/MacOS/App --enable-logging`

**Comment by megahertz** [comment]
Sorry, I have no idea why it doesn't work. It seems that your packaged application contains some old code without your latest changes, but I'm not sure.

**Comment by sibljon** [comment]
@megahertz thanks a lot for your time. Your last comment tipped me off to investigating to make sure that my entry file was being updated, and sure enough, it wasn't. So that was the issue. Thanks a lot for your help and I apologize for the noise!
