### ISSUE TITLE
Trying to change default log file location, but can't change default

### ISSUE THREAD

**Issue by bloodyIan** [megahertz/electron-log#153]
In the main.js
log.transports.file.fileName = __dirname + '/app.log';
Expected behavior is the app generating app.log file under app root folder, but error below happened 

16:42:31.100 > electron-log.transports.file: Couldn't write to C:\Users\v-yanjl\AppData\Roaming\ThirdParty\C:\Users\v-yanjl\repos\ThirdParty\app.log Error: ENOENT: no such file or directory, open 'C:\Users\v-yanjl\AppData\Roaming\ThirdParty\C:\Users\v-yanjl\repos\ThirdParty\app.log'

it seems it's writing to __dirname + '/app.log' under AppData\Roaming, how can I define the default or absolute path where I write my log to?

**Comment by megahertz** [comment]
you should use `file` property instead of `fileName`.

**Comment by bloodyIan** [comment]
My bad I actually used file instead of fileName, still not working

**Comment by bloodyIan** [comment]
OK thx
