### ISSUE TITLE
Not seeing log output except from Main process

### ISSUE THREAD

**Issue by Slapbox** [megahertz/electron-log#156]
~~I haven't tested 3.0.7, but I was pulling my hair out on 3.0.8. I glanced at the commit history and saw nothing suspect, but it's definitely an issue for me in my webpack environment.~~

**Comment by megahertz** [comment]
Could you provide more information?

**Comment by Slapbox** [comment]
Actually somehow AFTER rolling back to `"3.0.6"` and running `yarn`, now I (wrongly) have `3.0.8`, which is what I had had, but NOW it works... I'm absolutely baffled. I'm going to try to recreate my issue and I'll update with a suspected cause if I can.

Thanks for the CRAZY FAST reply @megahertz and for your great work!
