### ISSUE TITLE
Setting transport levels in Main Process has no effect on renderers

### ISSUE THREAD

**Issue by Slapbox** [megahertz/electron-log#157]
**Configuration in Main Process:**

![image](https://user-images.githubusercontent.com/6835891/65395747-12514300-dd6d-11e9-9ab5-1a863deb89e2.png)

**Outcome in Renderer Process**

![image](https://user-images.githubusercontent.com/6835891/65395748-14b39d00-dd6d-11e9-8235-599ac6c81841.png)

This is in a Webpack environment using `ProvidePlugin` to provide `log` across all files in all entry points for the project. This approach used to have no issues, but I just upgraded a bunch of things (methodically to try and and avoid hitting something like this, but, oops.) 

It doesn't seem like two separate instances based on what @megahertz [wrote here](https://github.com/megahertz/electron-log/issues/124#issuecomment-476681033) - and that matches my prior experience with accidental multiple instances.

Any idea what might be going on here? Also I saw some comments you made about things that would be improved in v4. Any idea when that's planned for around yet, or is it still too early to have a guesstimate?

Thanks again @megahertz !

**Comment by megahertz** [comment]
The main and the renderer processes are independent of each other. So logger should be configured both in main and renderer processes. It seems that I need to update documentation to make this this thing more clear enough.

**Comment by Slapbox** [comment]
Ah well, that explains that. I guess I'm still thinking in terms of version 2.

Thank you!

**Comment by megahertz** [comment]
I prefer to keep this issue opened as a reminder to update the part of documentation in v4.

**Comment by Slapbox** [comment]
I think it's actually pretty clear now, but maybe just needs to be bolded since it's a change from V2. I thought I was fully clear on the changes, but my bad assumptions led me to this, not bad docs.

Maybe just bolding this in the docs:

> If you change some transport options, make sure you apply the changes both in main and renderer processes.

**Comment by megahertz** [comment]
Yes, I'm going to add something like that.
