### ISSUE TITLE
electron-log.transports.file: Couldn't write to `file.log` fs.writeFileSync is not a function

### ISSUE THREAD

**Issue by ccostel** [megahertz/electron-log#159]
So I am using react as my frontend lib for the electron windows.

I am having troubles though with trying to write from within the render windows to the file with the following error:
```
 electron-log.transports.file: Couldn't write to /Users/$USER/Library/Application Support/nottr-dev/logs/rend_log.log TypeError: fs.writeFileSync is not a function
```

`Here's how I configure logger on react`
```

import React from 'react';
import ReactDOM from 'react-dom';

import './index.css';
import * as serviceWorker from './serviceWorker';
import "antd/dist/antd.css";

import ViewManager from './ViewManager.js';


// electron 
const electron = window.require('electron');

// Logger
const log = require('electron-log');

// Grab log settings for current window
var wind = electron.remote.getCurrentWindow();

// log.transports.file.file = "/Users/$USER/Library/Logs/nottr/rend.log";
log.transports.file.file = wind._log_settings.file;
log.transports.file.level = wind._log_settings.level;
console.log("Log file is set to:", log.transports.file.findLogPath());  


ReactDOM.render(<ViewManager />, document.getElementById('root'));


// ReactDOM.render(<App />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

```

Am I doing something wrong?

**Comment by megahertz** [comment]
It seems that nodeIntegration is disabled in your app, so node.js API is unavailable on a renderer side. As a workaround, you can load electron log in [preload](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) script and export all necessary methods. Sure, you can enable nodeIntergarion instead, but I don't think it's necessary in your app.

**Comment by ccostel** [comment]
> It seems that nodeIntegration is disabled in your app, so node.js API is unavailable on a renderer side. As a workaround, you can load electron log in [preload](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) script and export all necessary methods. Sure, you can enable nodeIntergarion instead, but I don't think it's necessary in your app.

Hey! Thanks for clarifying this for me. I am kind of new to electron and this was an eye opener for me. I will give it a shot tonight. 

Thanks again for this and the electron-log project!

**Comment by megahertz** [comment]
It seems in your case that you use browserify. In this case you need to use `window.require('electron-log');` instead of `require('electron-log');`
