### ISSUE TITLE
Add changelogs for 3.0.8, 3.0.9, ...

### ISSUE THREAD

**Issue by popod** [megahertz/electron-log#161]
Hi,

Could you please provide changelogs for versions ..., 3.0.8, 3.0.9, ... ? Or where are they ? The changelog.md file only show changes for versions up to 3.0.0.

Thanks

**Comment by megahertz** [comment]
Hi. 

I update changelog only between major/minor version changes. But thank you for reminding, I'm going to add v3 release to changelog soon.

To view difference between two patch releases you can use [github compare tool](https://github.com/megahertz/electron-log/compare/v3.0.0...v3.0.9)
