### ISSUE TITLE
Trap network errors on remote transport

### ISSUE THREAD

**Issue by florianperrot44** [megahertz/electron-log#164]
The **remote** transport is usefull to give feedback on a remote url.
But in case of logger server is unreachable or in timeout for any reason, an error is sended at the top level of application (ex : EDTIMEOUT).
That cause electron application to close...

Code that can  be replace remote.js code  :  

`function post(serverUrl, data) {
  var urlObject = url.parse(serverUrl);
  var htTransport = urlObject.protocol === 'https:' ? https : http;

  var body = JSON.stringify(data);

  var options = {
    hostname: urlObject.hostname,
    port:     urlObject.port,
    path:     urlObject.path,
    method:   'POST',
    headers:  {
      'Content-Length': body.length,
      'Content-Type':   'application/json'
    }
  };

  Object.assign(options, transport.requestOptions);

  var request = htTransport.request(options);
  request.write(body);
  request.end();
  // trap error in case of remote no/bad response to avoid electron app crash
  request.on('error', (err) => {
     console.log ("electron-log remote url=" + transport.url + " in ERROR : " + err.toString ());
  }) 
}`

**Comment by megahertz** [comment]
Thank you, I'll publish a fix on the next week.
