### ISSUE TITLE
doesn't work in web-worker

### ISSUE THREAD

**Issue by daniuting** [megahertz/electron-log#165]
i used electron-log in web-worker,no error throw,but the file log.log don't change,i don't know why,maybe cannot use fs module in web-worker?

**Comment by megahertz** [comment]
Is nodeIntegrationInWorker enabled?

**Comment by daniuting** [comment]
@megahertz yes,i enabled nodeIntegrationInWorker,it doesn't alert can't find module fs,and i made a breakpoint on fs.writeFileSync, it worked,but the file log.log didn't changed, i used webpack and worker-loader

**Comment by megahertz** [comment]
@daniuting Have you tried v4?

**Comment by daniuting** [comment]
@megahertz no, i used v3.0.9,should i change to v4?

**Comment by megahertz** [comment]
@daniuting Yes. Please let me know if it has the same problem.

**Comment by daniuting** [comment]
@megahertz wow!  it worked!  thank you very much!  it confused so mucn time,. now the log has two file, renderer and main, is this mean main process log and renderer process log? the worker log is print in the main process file~

**Comment by megahertz** [comment]
Thanks for your feedback. It's strange for me that worker thread writes logs to the main log instead of a renderer. I'm going to investigate this moment. But I'm glad v4 solves your problem.
