### ISSUE TITLE
writeFileSync works slow on windows.

### ISSUE THREAD

**Issue by lonelam** [megahertz/electron-log#166]
hi, I noticed that electron-log works rather slow on window because every log would call writeFileSync, can I just add an option and write file asynchronously?

**Comment by megahertz** [comment]
Yes, there is such an option. But I recommend to wait until v4 release, I'm going to change async write behavior in it.

**Comment by lonelam** [comment]
@megahertz thanks. On currently latest release I'm going to switch transport.sync to false.

**Comment by megahertz** [comment]
In 4.0.0-beta.8 it should works fine

**Comment by yebrahim** [comment]
This is also happening for me, with the latest version (4.1.2). It's also not just the file transport, also console. Works pretty fast on Ubuntu and Mac, but on Windows it freezes the UI thread until it finishes writing a bunch of log messages.

Separately, is there a way I can have only one way log communication, renderer->main but not the other way around? It seems like the renderer thread gets stuck waiting on these log messages from the main process.

**Comment by megahertz** [comment]
@yebrahim Just disable ipc transport for the main process. In most cases, the ipc transport has impact on performance, not file writing. And the transport is disabled for a packaged app by default.
