### ISSUE TITLE
when params contains undefined, it will throw error

### ISSUE THREAD

**Issue by daniuting** [megahertz/electron-log#167]
hey,first thank you for last time you resolved my problem of web-worker.  Now i found the a new problem of version v4, when i use params which contains undefined, it will throw error in transform/object/toString/JSON.parse(undefined), is it normal? Now my way is to handle the params before i use log.info,
the version which i use is 4.0.0-beta.6

**Comment by megahertz** [comment]
Hi. Thank you for the report. Will fix ASAP.
