### ISSUE TITLE
Update documentation for Hooks

### ISSUE THREAD

**Issue by Treverix** [megahertz/electron-log#169]
The hooks section should also explain, that we have to push hooks both on the main and on (all) render processes - just like transport modifications.

I've added a hook to put the `browserWindowId` on `message.variables` and the hook, that I pushed on the main process only, wasn't called for log messages on the renderer. Doing it on the renderer like so worked like a charm (typescript version):

```
  log.hooks.push((message; LogMessage): LogMessage => {
    message.variables.browserWindowId = remote.getCurrentWindow().id;
    return message;
  })
```

So later, on the formatter, I can add `[{processType}:{browserWindowId}]` to see which of my windows actually logged.

Maybe that's also worth a paragraph on the documentation to show, how we can use hooks to add more data to the message and use it on the formatter.

**Comment by megahertz** [comment]
Thank you for the feedback, I'll think about it.

It seems I also need to describe log.variables property. It's much better to modify this object in your situation.

**Comment by Treverix** [comment]
Does each render process have its own log instance which is different from the log instance on the main process? Then I really could update `log.variables` on the preload and remove the hook :) That would be much easier.

**Comment by megahertz** [comment]
> Does each render process have its own log instance which is different from the log instance on the main process
sure
