### ISSUE TITLE
Rewriting console.log does not take effect

### ISSUE THREAD

**Issue by awesomepeng** [megahertz/electron-log#171]
@ggozad

**Comment by megahertz** [comment]
@awesomepeng More details please

**Comment by awesomepeng** [comment]
![image](https://user-images.githubusercontent.com/20448089/70989944-834f8f00-20ff-11ea-9d13-fb947edbc749.png)

**Comment by awesomepeng** [comment]
![image](https://user-images.githubusercontent.com/20448089/70989998-9febc700-20ff-11ea-99ba-85edc7fdd5eb.png)

**Comment by awesomepeng** [comment]
@megahertz

**Comment by awesomepeng** [comment]
![image](https://user-images.githubusercontent.com/20448089/70990394-649dc800-2100-11ea-9168-1cf61621906b.png)

**Comment by megahertz** [comment]
Just set `console.log = log.log`. Anyway, if you need more complex solution, there is an error in `logCenter` function.

**Comment by awesomepeng** [comment]
is ok
