### ISSUE TITLE
Using electron-log from child process

### ISSUE THREAD

**Issue by fricci** [megahertz/electron-log#173]
I would like to use electron-log in my electron project. This project starts some child process, and I would like to forward logs from this child processes to main process (to write out to file) and to render process (to write out to developer console log).

Is this possible? If so, how should I configure the electron-log?

**Comment by megahertz** [comment]
Currently it doesn't support streaming. But you can subscribe to data event of stdout, something like:
```js
child.stdout.on('data', log.info);
child.stderr.on('data', log.error);
```

**Comment by fricci** [comment]
Thank you, I closing this issue.
