### ISSUE TITLE
can't log null object in remote transport due to data.push in maxDepth 

### ISSUE THREAD

**Issue by psiservices-ccounterman** [megahertz/electron-log#174]
In 4.0.0 logging null throws error:
Cannot read property 'push' of null
at the line
  if (data.push) {
in maxDepth in src/transform/object.js

In 3.0.9 the comparable code has
if (Array.isArray(json)) {

Both have a check for data === null later in the function.

**Comment by megahertz** [comment]
Thank you for the report. Will check soon.
