### ISSUE TITLE
TypeError: data.map is not a function

### ISSUE THREAD

**Issue by dsafreno** [megahertz/electron-log#176]
Hello,

I'm attempting to integrate electron-log with my electron application and am seeing the following exception:
```
Uncaught (in promise) TypeError: data.map is not a function
at maxDepth (.../node_modules/electron-log/src/transform/object.js:26)
```
This is on version 4.0.2

I believe it's occurring because I am logging a non-array that has a .push() method, which is what object.js appears to use to check if it's an array (FWIW, in my case, the object is a snapshot from Google's Firebase). Maybe just checking from the presence of .map() as well on object.js:24 would resolve?

**Comment by megahertz** [comment]
Thank you for the report

**Comment by dsafreno** [comment]
Thanks for the quick fix! 👏
