### ISSUE TITLE
DeprecationWarning with Electron 8.0.0

### ISSUE THREAD

**Issue by jruuska** [megahertz/electron-log#180]
Hi, 

a deprecation warning is being shown when electron-log is used with Electron 8.0.0 and
`webPreferences: {
      nodeIntegration: true
    }` is set.

```(node:69267) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.```

The problem seems to be these 2 lines
https://github.com/megahertz/electron-log/blob/master/src/transports/ipc.js#L28
https://github.com/megahertz/electron-log/blob/master/src/electronApi.js#L123
related to this change https://github.com/electron/electron/pull/20214

### Steps to reproduce
```
node@12.14.1
electron@8.0.0
electron-log@4.0.5
```

```
$ npx electron ./tests/test.js
08:40:02.497 › App ready!
(node:69513) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:69513) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
```

test.js
```js
const path = require('path')
const electron = require('electron')
const { app, BrowserWindow } = electron
const logger = require('electron-log')

app.allowRendererProcessReuse = true

app.once('ready', () => {
  logger.info('App ready!')

  const win = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true
    }
  })

  win.loadURL(`file://${path.resolve(__dirname, 'index.html')}`)
})
```

index.html
```html
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <title>Test</title>
</head>
<body>
  <h1>Hello</h1>
</body>
```

**Comment by megahertz** [comment]
Thank you for the detailed report, I'll investigate it a bit later.

**Comment by BVSPHari** [comment]
`DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.`

getting same error when used local html file path to `loadURL` method.

**Comment by megahertz** [comment]
@BVSPHari Could you provide a code example which produces such a warning?

**Comment by raphinesse** [comment]
This still happens with `electron-log@4.1.0` when using scopes:

test.js
```js
const { app, BrowserWindow } = require('electron');
const log = require('electron-log').scope('main');

let win;
app.once('ready', () => {
    win = new BrowserWindow({
        webPreferences: {
            nodeIntegration: true,
        },
    });

    log.info('Created window!');

    win.loadURL(`file:///${__dirname}/index.html`);
});
```

index.html
```html
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <title>Test</title>
</head>
<body>
  <h1>Hello</h1>
  <script>
    require('electron-log').scope('renderer').info('Hello!');
  </script>
</body>
```

**Comment by megahertz** [comment]
Thank you for the example @raphinesse, I'll try to fix that on this week.

**Comment by raphinesse** [comment]
Thanks for your quick fix. Works great for me! :medal_sports:
