### ISSUE TITLE
String substitutions support

### ISSUE THREAD

**Issue by vyunikov** [megahertz/electron-log#181]
Code:
```
log.info('number: %d', 10);
```

Produces log output as:
```
number: %d 10
```

Does `electron-log` support string substitutions? 
Based on the information that it can replace traditional `console`, I guess it should.
Tested against version 4.0.6.

**Comment by megahertz** [comment]
I'm going to fix the issues a bit later.

**Comment by megahertz** [comment]
It will require some time to fix the issue. I'll try to publish a fix in the beginning of March.

**Comment by vyunikov** [comment]
Ok, thanks for the update

**Comment by megahertz** [comment]
It will be released a bit later
