### ISSUE TITLE
OOM due to React Event Circular Object

### ISSUE THREAD

**Issue by dsafreno** [megahertz/electron-log#182]
I have a log statement of an event coming from React div.onKeyDown that is causing an OOM crash. 

Here's the crash:
```
<--- Last few GCs --->

[74698:0x106d78000]   108926 ms: Mark-sweep 2023.7 (2050.1) -> 2023.0 (2050.6) MB, 708.2 / 0.1 ms  (average mu = 0.203, current mu = 0.021) allocation failure scavenge might not succeed
[74698:0x106d78000]   109559 ms: Mark-sweep 2023.8 (2050.6) -> 2023.1 (2050.1) MB, 627.9 / 0.1 ms  (average mu = 0.115, current mu = 0.009) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x10910bd0b]
Security context: 0x0043bc241f29 <String[#21]: http://localhost:3000>
    1: maxDepth(aka maxDepth) [0x4377df0161] [/Users/dsafreno/Developer/always-on/node_modules/electron-log/src/transform/object.js:~12] [pc=0x2559176da3](this=0x0043eff004d1 <undefined>,0x004359343ff1 <ApplicationCache map = 0x4386675fc9>,2)
    2: maxDepth(aka maxDepth) [0x4377df0161] [/Users/dsafreno/Developer/always-on/node_modules...
```

I can't Stringify the object to show you here. Stringify complains with `Uncaught TypeError: Converting circular structure to JSON`

Here's the usage:
```
<div className="..." tabIndex="1"
    onKeyPress={...}
    onKeyDown={e => {
        console.log(e)
    }}
    />
```

If I have the console open, it auto-pauses the app before the crash with the following information:
<img width="654" alt="Screen Shot 2020-02-11 at 5 17 23 PM" src="https://user-images.githubusercontent.com/2432101/74294339-6516a180-4cf2-11ea-87b2-b3d7e63c5a13.png">

I solved for now by removing the log statement, but it would be good to fix this so we don't run into it again on accident. How can I help?

**Comment by dsafreno** [comment]
(This is on latest electron-log 4.0.6)

**Comment by megahertz** [comment]
Thank you for the report. I'll investigate it soon.
