### ISSUE TITLE
log.catchErrors(options?) doesn't work in my app

### ISSUE THREAD

**Issue by cyrilfr** [megahertz/electron-log#184]
I'm running an Angular app with Electron and I added those lines to the main.ts file of my app:

```
import * as log from 'electron-log';
log.transports.file.resolvePath = () => '/var/log/myApp.log';
log.catchErrors();
```

Unfortunately, this doesn't catch uncaught exceptions such as `NullInjectorError` if I add a dependency injection without a provider for example.

**Comment by megahertz** [comment]
It doesn't handle errors in a renderer process. You should call the code there.

**Comment by cyrilfr** [comment]
I call it in the main.ts of the app:

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

// touch events support
import 'hammerjs';

// configure electron logging
import * as log from 'electron-log';
log.transports.file.resolvePath = () => '/var/log/vesta.log';
log.catchErrors();

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => log.error(err));
```

**Comment by megahertz** [comment]
Try to move log.catchErrors() in the top of the file.

**Comment by cyrilfr** [comment]
That changes nothing.

**Comment by megahertz** [comment]
If you just run `Promise.reject()` after calling `catchErrors()`, does it processed by electron-log?

**Comment by cyrilfr** [comment]
It works, i get an `UnhandledRejection` error.

**Comment by megahertz** [comment]
Example?

**Comment by megahertz** [comment]
Closed because of inactive. Will reopen If you could provide more information to reproduce the issue.

**Comment by cyrilfr** [comment]
Sorry for my inactivity.
You can easily reproduce a JS error in TypeScript with something like:

```
const bug: any = null;
bug.test();
```

It will throw an exception:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'test' of null
TypeError: Cannot read property 'test' of null
```
This exception cannot be seen in logs (I check both console and file transports).

**Comment by megahertz** [comment]
@cyrilfr Accotding to the exception text, it's handled somewhere else in your code.

**Comment by cyrilfr** [comment]
From the Angular template I guess...

**Comment by megahertz** [comment]
So it can't be handled by electron-log

**Comment by cyrilfr** [comment]
There is a way to log it:

    console.error = log.error;

**Comment by megahertz** [comment]
If you use Angular you need to use its built-in tools for error handling instead, at least on renderer side.
