### ISSUE TITLE
Log level doesn't do anything (version 4.0.7)

### ISSUE THREAD

**Issue by zNoobs** [megahertz/electron-log#185]
Hi,
Whatever I set in the log.level variable, it displays all the logs, I have the last version (4.0.7).

Example:

```
const log = require('electron-log');
log.level = "error";

Class Test {
    constructor(){
        log.debug("test log");
    }
}

new Test();

```
The console will get the "test log"...

**Comment by megahertz** [comment]
There is no such a property. You need to set the level option for a desired transport instead.
