### ISSUE TITLE
Uncaught TypeError: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by Yuliang-Lee** [megahertz/electron-log#187]
electron: 8.0.0
node: 12.10.0
electron-builder  version=21.2.0
electron-log: 4.1.0

I use electron-log in my web-worker and use web-worker according to https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/486#issuecomment-534968789 but has a little different

```js
<script>
import Worker1 from './workers/worker1'
let worker = new Worker1()
...
```

vue.config.js
```js
module.exports = {
  configureWebpack: config => {
    //   config.devtool = 'source-map'
    config.module.rules.unshift({
      test: /\.worker\.js$/,
      use: {
        loader: 'worker-loader',
        options: { inline: true }
      },
    })
}
    ...

```

It's all be fine when in development, but after build the worker can't find electorn.app

**Comment by megahertz** [comment]
Do you mean the error occurs only for a packaged application? Could you provide the exact error message?

**Comment by Yuliang-Lee** [comment]
Yes, only happened in packaged application. I got this error message in 
```
worker.onerror = (evt) => {
        log.error(evt.message)
}
```
I don't know how to get the error stack. the attachment is the bundled worker file
[5568f8bfd0a2a02216f8.worker.js.txt](https://github.com/megahertz/electron-log/files/4406901/5568f8bfd0a2a02216f8.worker.js.txt)

**Comment by megahertz** [comment]
Thank you. Will try to reproduce in a few days.

**Comment by megahertz** [comment]
Do you enabled nodeIntegrationInWorker?

**Comment by Yuliang-Lee** [comment]
> Have you enabled nodeIntegrationInWorker?

yes, 
![image](https://user-images.githubusercontent.com/6936358/78621925-51348980-78b6-11ea-9772-891dfb720e68.png)

**Comment by megahertz** [comment]
I can't reproduce the issue. I created a test app using [electron-vue](https://github.com/SimulatedGREG/electron-vue) with worker-loader and built the app as AppImage, it works fine. I haven't tried your bundle since it's pretty hard to debug such a large bundle without source.

I can try to solve the issue, if you could create a test project which reproduces the issue.

**Comment by Yuliang-Lee** [comment]
I'm use https://github.com/nklayman/vue-cli-plugin-electron-builder not the [electron-vue](https://github.com/SimulatedGREG/electron-vue),
here is the demo project
https://github.com/Yuliang-Lee/electron-vue-log-debug

**Comment by megahertz** [comment]
Thanks for the demo project. It's not an electron-log bug.

The following code of electron-log
```js
transport.useStyles = process.env.FORCE_STYLES;
```
is transpilled to
```js
 t.useStyles = Object({
                NODE_ENV: "production",
                BASE_URL: require("electron").remote.app.getAppPath(),
                IS_ELECTRON: !0
            }).FORCE_STYLES,
```

The error occurs on line `BASE_URL: require("electron").remote.app.getAppPath(),` which is generated by [vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/lib/webpackConfig.js#L34). So you could submit the issue to vue-cli-plugin-electron-builder
