### ISSUE TITLE
appName does not get updated 

### ISSUE THREAD

**Issue by shivarkarimi** [megahertz/electron-log#188]
I'm on "electron-log": "4.1.1" and macOS. After I upgraded from version 3.0.2 `appName` does not get updated: 

I configure the log before any logging. I have Angular-electron app. I configure it both in angular and electron. 

```
    log.transports.file.appName = LOG_NAMINGS.APP_NAME;
    log.transports.file.fileName = LOG_NAMINGS.FILE_NAME;
```

only updates `filename` but not `appName`

so I had to do something like below to fix my problem:

```
log.transports.file.resolvePath = (variables) => {
const s = variables.libraryTemplate.replace('{appName}', LOG_NAMINGS.APP_NAME);
return path.join(s, LOG_NAMINGS.FILE_NAME);
```
note: I cannot change name in package.json for some other reasons

**Comment by megahertz** [comment]
`appName` property is deprecated, that's why only `resolvePath` solves your problem

**Comment by shivarkarimi** [comment]
Thanks for the quick response.
