### ISSUE TITLE
Question: Logging renderer to file and devTools - but not to terminal

### ISSUE THREAD

**Issue by yafp** [megahertz/electron-log#189]
I am using electron log in my electron application. First of all, thanks for this project.
My application supports a commandline-parameter (`--verbose`) for optional enabling verbose mode.

**The idea is:** 

* If the application is started with `--verbose` from a terminal - the terminal AND the devtools should both show all the logging output from my renderer process. 
* If the application is started without `--verbose` it should just write the renderer logging to the DevTools but NOT to the terminal

Right now i tried reaching this using `log.transports.console.level`.
If my app is started using `--verbose` i set `log.transports.console.level = true`, otherwise to `log.transports.console.level = false`.

But this effects both:
* logging to terminal
* logging to devtools

Is there an option to control devtools vs terminal output?

Best regards

**Comment by megahertz** [comment]
You should set console.level to false on both main and renderer processes

**Comment by yafp** [comment]
Hi @megahertz 
i now do set `log.transports.console.level = false` in both main and renderer if my app is started without the `--verbose` option. 

As a result the logging does
* not appear in DevTools
* not appear in Terminal

My question is: 
Does electron-log support a mode where the logging
* appears in DevTools BUT
* NOT appear in Terminal
?

> Also, be aware that true is not a correct value for level.

Thanks for pointing that out - i assumed whatever can be false can be true as well - based on the readme ;)

**Comment by megahertz** [comment]
> My question is:
> Does electron-log support a mode where the logging appears in DevTools BUT NOT appear in Terminal

In this case, you can disable console transport only in main process.

**Comment by yafp** [comment]
> In this case, you can disable console transport only in main process.

Thanks - that was the magic hint i needed.

**Comment by megahertz** [comment]
@yafp Do you mean it's not obvious that disabling logging in a renderer prevents logging in DevTools? It's standard behaviour for electron: each renderer has its own DevTools instance.

**Comment by yafp** [comment]
>> Does electron-log support a mode where the logging appears in DevTools BUT NOT appear in Terminal

> In this case, you can disable console transport only in main process.

that part wasn't obvious for me.
