### ISSUE TITLE
[feature request] Extending remote transport

### ISSUE THREAD

**Issue by ozooner** [megahertz/electron-log#190]
Hi!

Having used electron-log since version 2, I have been sending the logs to a Graylog server in the renderer process (hooking into the IPC messages). I noticed that a new transport has been added, but unfortunately it's a bit limited in it's configuration.

Namely graylog accepts GELF formatted logs where the request payload has to be in a specific format and it can also be extended with additional parameters. Currently however the request payload is somewhat set in stone. I would propose a function where it's possible to transform the remote transport payload before it's sent out. There is already logic in place for overriding the http request configuration, pretty much same approach. My proposal would make the remote logger much more agile than it currently is.

Thank for listening :)

P.S - now that both main and renderer process have to be configured separately, is it possible to configure another process logger (i.e renderer process modifies the log level of main process) or should it be done over custom IPC message?

**Comment by ozooner** [comment]
GELF format: https://docs.graylog.org/en/3.2/pages/gelf.html

**Comment by megahertz** [comment]
Hi @ozooner. Yes, it's a nice idea to add a custom http payload transformer, I'll try to add the feature in April.

Currently both processes are configured separately and the ipc transport is used mostly for debugging, it's disabled by default in a packaged application. So, both loggers should be configured independently.

**Comment by ozooner** [comment]
Awesome, thanks @megahertz!

**Comment by ozooner** [comment]
@megahertz  - is it by design that remote transport messages are not formatted? 
(The customFormatterFactory transform is not executed on the remote transport messages)

**Comment by megahertz** [comment]
@ozooner I thought about just the same format option for remote transport, but it has a bit different responsibility and implementation details. First of all, it was introduced mostly for string templates, callbacks are less frequently used. String templates for remote transport make sense only when user wants to send data in form-urlencoded format, but I don't think the current templete syntax is good enough for that purposes.

So, I decided the format option for remote transport may confuse some users and it's better to use another option.
