### ISSUE TITLE
a few hours away from the local time

### ISSUE THREAD

**Issue by joeyer** [megahertz/electron-log#191]
The printed time will be a few hours away from the local time, it is not clear how this time is calculated

local time：2020-05-06 16:05
log time：2020-05-06 14:05

**Comment by megahertz** [comment]
What's the result of `log.info(new Date())`?

**Comment by joeyer** [comment]
estimated to be a time zone issue, the customer is in Tanzania

**Comment by megahertz** [comment]
So, closed since it's not related directly to the library.
