### ISSUE TITLE
A single file for all processes [help wanted]

### ISSUE THREAD

**Issue by ajmasia** [megahertz/electron-log#194]
Hi @megahertz,

Is there a way for all logs to go to a single file instead of separate files for each process?

It would be nice to be able to do this: '[{y}-{m}-{d} {h}:{i}:{s}.{ms}] [{process}] [{level}] {text}'

Thanks!

**Comment by megahertz** [comment]
You can set log.transports.file.fileName to the same value for all processes. Instead of {proceess} you need to use {processType}.

**Comment by ajmasia** [comment]
Thanks @megahertz 😄
