### ISSUE TITLE
No colors in the main console [help wanted]

### ISSUE THREAD

**Issue by ajmasia** [megahertz/electron-log#195]
Hi @megahertz again 😄 

How can I use colors in the main console? I'm using electron with vue and the logs always are shown in white color:

<img width="778" alt="Screen Shot 2020-05-15 at 13 19 51" src="https://user-images.githubusercontent.com/23419327/82045126-d9286300-96ae-11ea-8de1-85a745653f55.png">

`log.info('%cRed text. %cGreen text', 'color: red', 'color: green')` only works in the browser devtools 

Thanks!

**Comment by megahertz** [comment]
It depends on your dev environment. If `process.stdout.isTTY` is false, you can't use colors. You can force electron-log to use colors by setting `process.env.FORCE_STYLES` to true, but make sure it's set only for development environment.

**Comment by ajmasia** [comment]
@megahertz, my process.stdout.isTTY is true and I use `process.env.FORCE_STYLES = true` but don't work!

**Comment by megahertz** [comment]
Try to set `log.transports.console.useStyles = true`

**Comment by ajmasia** [comment]
Hi @megahertz, it seems work fine but only with the main process:

<img width="555" alt="Screen Shot 2020-05-18 at 16 16 22" src="https://user-images.githubusercontent.com/23419327/82223515-0c732800-9923-11ea-86d4-f57ee03105b9.png">

The last two logs are from the renderer process 😄 

![Screen Shot 2020-05-18 at 16 18 44](https://user-images.githubusercontent.com/23419327/82223680-404e4d80-9923-11ea-943e-ab4978880ea5.png)

In the browser console they look good, any solution for this?

Thanks for your support!

**Comment by megahertz** [comment]
Could you share code which prints these lines?

**Comment by ajmasia** [comment]
@megahertz here is my code
```js
import log from 'electron-log'
import config from '@/config/logger'

const isStyled = process.env.VUE_APP_LOGGER_STYLES

log.variables.appName = process.env.VUE_APP_REF
log.transports.file.level = Boolean(process.env.VUE_APP_FILE_LOGGER)
log.transports.file.format = config.format
log.transports.file.fileName = process.env.VUE_APP_FILE_LOGGER_NAME_NAME
log.transports.console.useStyles = Boolean(isStyled)
log.transports.console.level = Boolean(process.env.VUE_APP_CONSOLE_LOGGER)
log.transports.console.format = config.format

export const logger = (level, message) => {
  const loggerConfig = config.styles.filter(item => item.level === level)

  return isStyled
    ? log[`${level}`](`%c${message}`, `color: ${loggerConfig[0].color}`)
    : log[`${level}`](message)
}
```

**Comment by megahertz** [comment]
Thank you for your feedback. Does the latest version solve the issue?

**Comment by ajmasia** [comment]
Hi @megahertz, great work! Now works fine!

<img width="806" alt="Screen Shot 2020-05-20 at 15 44 16" src="https://user-images.githubusercontent.com/23419327/82453481-dcf22600-9ab0-11ea-8748-00a6fbed1e6c.png">

Thanks!
