### ISSUE TITLE
Can't resolve 'fs' 

### ISSUE THREAD

**Issue by fricci** [megahertz/electron-log#196]
With Angular 9 I get the following error:

```
ERROR in ../node_modules/electron/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\feren\Projects\[projectname]\node_modules\electron'
ERROR in ../node_modules/electron-log/src/transports/file/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\feren\Projects\[projectname]\node_modules\electron-log\src\transports\file'
ERROR in ../node_modules/electron-log/src/transports/file/file.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\feren\Projects\[projectname]\node_modules\electron-log\src\transports\file'
ERROR in ../node_modules/electron-log/src/transports/file/packageJson.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\feren\Projects\[projectname]\node_modules\electron-log\src\transports\file'
```

relevant part of app.module.ts:

```
import * as log from 'electron-log';

log.transports.file.level = false;
log.transports.ipc.level = 'info';
console.log = log.log;
```

**Comment by megahertz** [comment]
It requires nodeIntegration to be enabled

**Comment by fricci** [comment]
thank you your answer, the relevant browser config:
```

        webPreferences: {
            nodeIntegration: true,
            webviewTag: true,
            webSecurity: false
        }
```

**Comment by megahertz** [comment]
It may also occurs when you run your code as a web worker or webpack target is not set to electron-renderer

**Comment by fricci** [comment]
I cannot modify the webpack config because it's hidden by electron-cli. I do not think it's ran as web worker... it's standard andular app without any webworker.

**Comment by megahertz** [comment]
Sorry, I'm not familiar with Angular, so I can't help you since the issue is related to your project build configuration. As a workaround, you can export electron-log interface in preload script but I think there is a better solution.

**Comment by megahertz** [comment]
Closed since the issue is not related to the library directly. But if someone finds a solution for Angular project and post it here I'd be really grateful.

**Comment by bno1** [comment]
I found a solution, follow this guide: https://developer.okta.com/blog/2019/12/09/angular-webpack, and in your `custom-webpack.config.js` set the target to `electron-renderer`, like so:
```
module.exports = {
    target: 'electron-renderer',
};
```

**Comment by greg9504** [comment]
If you get the "Error: Can't resolve 'fs' in ... " in your Angular application after adding Electron-log try this:

In the renderer (a component) use code like this (note the window.require):
```
import { Component } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import log from 'electron-log';  //<--

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  private elog: typeof log; //<--

  constructor(
    private electronService: ElectronService,
    private translate: TranslateService
  ) {
    this.translate.setDefaultLang('en');
    
    this.elog = window.require('electron-log');  //<--
    this.elog.info('Hello, log'); // use it

  }
}

```
If using the maximegris/angular-electron starter you would probably want to put the instance of log in the ElectronService and access it through that, so you don't have to write the window.require everywhere.

More info
https://github.com/maximegris/angular-electron/issues/632#issuecomment-898484389
and 
https://github.com/maximegris/angular-electron#how-to-import-3rd-party-libraries

In main process just use call instantiate it normally and make sure to set nodeIntegration: true, and contextIsolation: false if you want to use Electron-log in renderer process.

/app/main.ts
```
import { app, BrowserWindow, screen } from 'electron';
import log from 'electron-log';

log.info('In main process');

....

win = new BrowserWindow({
    x: 0,
    y: 0,
    width: size.width,
    height: size.height,
    webPreferences: {
      nodeIntegration: true,
      allowRunningInsecureContent: (serve) ? true : false,
      contextIsolation: false,  
    },
  });
```
