### ISSUE TITLE
Feature request - Retrieve log file easily 

### ISSUE THREAD

**Issue by yonlif** [megahertz/electron-log#197]
Could you please add a function that retrieve the log file content? The return type can be String, list of lines or maybe json.
If this is too much - even a simple function to retrieve the path the specific logger is going to write to will be good.
I just want to retrieve the file automatically in case something goes wrong.

**Comment by megahertz** [comment]
I've thought about the feature before. There is a problem, when the custom `resolvePath` option is set it's not possible to detect used log files exactly. I'll think on it later.

**Comment by yonlif** [comment]
Okay.
If I know I am not using this flag can I use `log.transports.file.getFile().path;` and `fs` to do it by myself?

**Comment by megahertz** [comment]
@yonlif yes

**Comment by jjhbw** [comment]
```typescript
import logger from 'electron-log'
const getLogFilePath = () => logger.transports.file.getFile().path
```
Does the trick for me.

I would like to urge against overengineering this fantastic and lean library, but I assume I'm preaching to the choir here ;).
