### ISSUE TITLE
macOS: can't find log file

### ISSUE THREAD

**Issue by komplexb** [megahertz/electron-log#20]
App logs to console, but I don't see any file at the default path `~/Library/Logs/<app name>/log.log`. I've checked both `~/Library/Logs/` and `~/Users/username/Library/Logs/`.

Please advise.

```
const log = require('electron-log')
log.transports.file.format = '{h}:{i}:{s}:{ms} {text}'
log.transports.file.maxSize = 5 * 1024 * 1024

function scheduleRandomNote () {
  let rule

  return schedule.scheduleJob(rule, function () {
    log.info('triggered-random-note')
    mainWindow.webContents.send('trigger-random-note')
  })
}
```

**Comment by megahertz** [comment]
log.transports.file.level = 'info';

**Comment by komplexb** [comment]
Ok, i'll try that. I assumed that it could run without config as seen here: https://www.npmjs.com/package/electron-log#usage

**Comment by megahertz** [comment]
Yes, but by default it writes all messages only to console. I'm planning to update documentation.

**Comment by komplexb** [comment]
O ok, i got the opposite impression from: "By default, two transports are active: console and file".
This https://github.com/megahertz/electron-log/issues/20#issuecomment-269257719 worked though, thanks.

**Comment by dustinsoftware** [comment]
Thanks, I was also thrown off that the default file log verbosity is not `info`.
