### ISSUE TITLE
Updating the log file path - Usage query

### ISSUE THREAD

**Issue by alishaz-polymath** [megahertz/electron-log#202]
Hi,
I am trying to update the log file's default path and I can't seem to understand how to do it exactly. The docs in the :
https://github.com/megahertz/electron-log/blob/master/docs/file.md
suggest that I can achieve it by using the **resolvePath(variables)** function but I am not sure how to go about it. If I have a directory constant DIR, and the file name constant FILE, how do I set the path for the logger to use DIR + FILE as the logging directory+path?

Kind regards,
Syed Shahbaz

**Comment by megahertz** [comment]
Hi @alishaz-polymath. Do you mean something like that?

```js
log.transports.file.resolvePath  = () => path.join(DIR, FILE)
```

**Comment by alishaz-polymath** [comment]
Hi @megahertz, Thanks for getting back. Yes, this is exactly what I meant. Thank you!
