### ISSUE TITLE
Attempting to log data that has a `map` function defined can cause errors

### ISSUE THREAD

**Issue by UberMouse** [megahertz/electron-log#204]
Internally the transforms inspect logged data and check if an object has a `map` method attached to it. In the event that it does, it calls this method to accomplish something. This is causing me problems because I am logging out a data object containing an `ObservableQuery` class from the Apollo GraphQL client, which has a `map` method.

However, when electron-log calls this `map` method it doesn't do it correctly (because how could it know?) which results in creating a new `ObservableQuery` that errors in the constructor because of bad constructor arguments.

Somewhat related to #176

**Comment by megahertz** [comment]
Thanks for the report, will investigate a bit later
