### ISSUE TITLE
Hide irrelevant source location from chrome developer tools in renderer process logging

### ISSUE THREAD

**Issue by vazra** [megahertz/electron-log#207]
I use electron-log in renderer process using a preload. the log can be viewed in the chrome developer console, but it shows the source line number as `url:/Users/username/path/to/project/node_modules/electron-log/src/transports/console.js:91` always, which have no relevance and takes up a significant screen space. Is there any option to remove it?

<img width="441" alt="Screenshot 2020-07-26 at 10 03 33 AM" src="https://user-images.githubusercontent.com/7609895/88471689-a958cf80-cf29-11ea-82d2-b367a07e7755.png">

**Comment by vazra** [comment]
@megahertz any idea?

**Comment by megahertz** [comment]
Unfortunately, it's not possible to fix that, #29

**Comment by vazra** [comment]
yeah I've seen https://github.com/megahertz/electron-log/issues/29 , but is there any way to hide it, even if its not showing the correct line number? will [this](https://stackoverflow.com/a/34763151) work?

**Comment by megahertz** [comment]
Thank you, I'll think on it, but can't promise I can implement it soon

**Comment by vazra** [comment]
thanks, it's fine. If you find any work workaround that can be used with the current version(with setTimeout or so), please update here.

**Comment by megahertz** [comment]
Currently, the only way is to use a custom console transport in a renderer process.

**Comment by vazra** [comment]
> Currently, the only way is to use a custom console transport in a renderer process.
any sample code?

**Comment by megahertz** [comment]
https://github.com/megahertz/electron-log/blob/master/docs/extend.md#transport

**Comment by vazra** [comment]
Thanks @megahertz ! 

for anyone else who is facing this issue, you can use a custom transport with something like 
```
function consoleWithNoSource(...params) {
  setTimeout(console.log.bind(console, ...params));
}
```
to hide the source entry from console.

**Comment by vazra** [comment]
@megahertz I crated a PR with this change in the console transport, please have a look - https://github.com/megahertz/electron-log/pull/209

**Comment by megahertz** [comment]
@vazra Sorry, I have no time at this moment. Will try to check the PR on this week.

**Comment by vazra** [comment]
👍

**Comment by megahertz** [comment]
Solved
