### ISSUE TITLE
Why electron app.getName is not used

### ISSUE THREAD

**Issue by develar** [megahertz/electron-log#21]
Why [app.getName](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetname) is not used to get app name? To package.json loading.

**Comment by megahertz** [comment]
Because sometimes it's used without electron.

**Comment by develar** [comment]
Let's just check https://github.com/electron/electron/issues/2288#issuecomment-123226816 ;)?

**Comment by megahertz** [comment]
Thanks for the information, I didn't know about this. But there is one problem - how to require electron and don't break a non-electron project which uses webpack.

**Comment by develar** [comment]
`require` only after check that it is electron.  `require` is not restricted to be only on top file level. For ES6 as well (as yarn or electron-builder uses https://github.com/zertosh/babel-plugin-transform-inline-imports-commonjs).

**Comment by megahertz** [comment]
I thinked that webpack/bable doesn't care whether require is called on a top level or not. Thanks for the idea, I'll check it later.

**Comment by develar** [comment]
Thank you for amazing module without tons of questionable dependencies :) This module will be recommended by electron-builder to debug auto-updater.

**Comment by megahertz** [comment]
Now it uses app.getName
