### ISSUE TITLE
Custom format padding around {text}

### ISSUE THREAD

**Issue by alexanderluchs** [megahertz/electron-log#211]
**Context**

I have electron-log configured with a custom format for the file transport:
```json
'{"time": "{iso}", "level": "{level}", "message": "{text}"}'
```
This should output the logs in json format and this works great for the most part.  Unfortunately...

**Observed Behavior**

Here's an example log output:
```json
{"@timestamp": "2020-07-28T21:30:52.503Z", "level": "info", "message": " Starting App. "}
```

There's extra whitespace padding around {text} and I'm not sure where its coming from.

**Expected behavior**

I would expect there to be no whitespace between the quotes and the substitution for {text}.
```json
{"@timestamp": "2020-07-28T21:30:52.503Z", "level": "info", "message": "Starting App."}
```

Please let me know if there's any additional information you need in order to investigate the issue.  Thanks for any time spent looking into it!

**Comment by megahertz** [comment]
For the purpose it's better to use format function instead of string template.

**Comment by alexanderluchs** [comment]
That works and is an acceptable solution.  Thanks for suggesting the alternative.
