### ISSUE TITLE
Multiple log files in the same page/isntance

### ISSUE THREAD

**Issue by alishaz-polymath** [megahertz/electron-log#218]
Hi,
I wanted to create 3 separate log files and identify them by different kinds of logs. Unfortunately, if I try to use the code:
    const log1 = require('electron-log');
    const log2 = require('electron-log');
    const log3 = require('electron-log');

and then identify each by a different file name:

log1.transports.file.resolvePath  = () => path.join(_logDIR, 'log_type1.log');
log2.transports.file.resolvePath  = () => path.join(_logDIR, 'log_type2.log');
log3.transports.file.resolvePath  = () => path.join(_logDIR, 'log_type3.log');

However, now all of them resolve to the last-mentioned filename ('log_type3.log').
So, now if I try to write anything in log1, it ends up being written in log_type3.log file instead of log_type1.log

How can I solve this issue?

**Comment by megahertz** [comment]
Hi, https://github.com/megahertz/electron-log#multiple-logger-instances
