### ISSUE TITLE
Doesn't write a lot to log file

### ISSUE THREAD

**Issue by ir-fuel** [megahertz/electron-log#22]
Hi 
I am using electron-log in an electron app running on Windows. I am also using webpack.

The problem is that the log file gets created, 2 lines are written to it when the app starts, but then I see in my console "electron-log.transports.file: Could not set a log file"

Any idea why this happens? The log file is there, it just stops writing to it.

Thanks!

**Comment by ir-fuel** [comment]
It seems that both `APPDATA` and `USERPROFILE` entries in `process.env` are undefined

**Comment by ir-fuel** [comment]
Some more info: it seems to work when logging from the main process, but not from the render process.

**Comment by megahertz** [comment]
As a temporary solution you can try to import electron-log using  require('electron').remote.require('electron-log')

**Comment by ir-fuel** [comment]
I tried passing it from the main to the renderer process through globals and electron `remote`, but I get an infinite loop somewhere in electron when doing `log.info(newProps)` in a `componentWillReceiveProps` call

**Comment by megahertz** [comment]
Hm... Sorry, I don't know what is the reason. I'm going to create a simple web app using React, webpack and electron in a few weeks and I'll test this scenario.

**Comment by ir-fuel** [comment]
I found something that works for, I have just forked your repo. I'll put the info here, but it's not really something that can be used in general I think as it requires too much setup code.

**Comment by ir-fuel** [comment]
First problem. Env vars not propagated to render process.
Solution.
In my `main.js` I added

```
global.appdata = process.env['APPDATA']
global.userprofile = process.env['USERPROFILE']
global.home = process.env['HOME']
```

In the render process file where I include the `electron-log` package I did:

```
var process = require('process')
const {remote} = require('electron')

process.env['APPDATA'] = remote.getGlobal('appdata')
process.env['USERPROFILE'] = remote.getGlobal('userprofile')
process.env['HOME'] = remote.getGlobal('home')

export const log = require('electron-log')
```


Second problem. Even with this, it still doesn't find the env values.

Solution. In `electron-log` add this add the top of the file
```
var process = require('process');
```

Third problem, main and render process accessing same file.

Solution, in `electron-log` put this
```
  if (dir) {
    if (process.type === 'renderer') {
      return path.join(dir, 'renderer_log.log');
    }
    return path.join(dir, 'log.log');
  } else {
    return false;
  }
```

Fourth problem, logger in render process writes to a file inside the `electron` folder, and not inside the `appName` folder. Logger in main process does write to the correct folder

Solution

Set `appName` explicitly in render process


This works for me, but as you can see, it's not just a one line plug and play thing.

**Comment by megahertz** [comment]
Thank you. I'll solve it in the next version.

**Comment by hepiyellow** [comment]
I am experiencing the same issue.
Logs from main process appear in file, but logs from Renderer process appear only in Console.
I see that in the Renderer process, `log.transports.file.file` is `undefined`.

I am using electron-log version 2.2.1, 
was this resolved?

I tried `devtron` to see if any IPC is used, 
It the first time I use devotion, so I am not sure I did it right,
but I started recording IPC, did something which invokes logs,
and I didn't see any recorded IPC.

Any idea?

**Comment by megahertz** [comment]
@hepiyellow Does `const log = require('electron-log/renderer')` instead of `const log = require('electron-log')` solve your problem?

**Comment by hepiyellow** [comment]
Definitely renderer.js was not `required`, since `process.type` is `undefined.
I am still investigating this.

FYI:
I am working with typescript and webpack.

**Comment by megahertz** [comment]
I have no problems with webpack for both processes. If I have some problem with webpack and electron I usually start from modifying bundle code directly. Sometimes the DefinePlugin makes some problem. Do you use the electron/electron-renderer target?

**Comment by hepiyellow** [comment]
Turns out I am using a very old `electron-builder' (version 2.10.0), which is part of [Cross-Builder](https://github.com/zalmoxisus/crossbuilder) (Which is not updated).
And I don't see that I have even any separate web pack config for main and renderer processes.

Is there some way that you can specify in `electron-log` which `electron` and `electron-builder` versions you work with (peerDependencies?)
