### ISSUE TITLE
no main.log in ~Library/Logs/[AppName]  with webPreferences: {preload: ...} 

### ISSUE THREAD

**Issue by Holybasil** [megahertz/electron-log#220]
My code is like the follow:
```
import log from 'electron-log';

const createWindow = () => {

    log.verbose(`%c${process.env.PATH}`, 'color: red');

    mainWindow = new BrowserWindow({
        show: false,
        width: 1024,
        height: 728,
        webPreferences:
             process.env.NODE_ENV === 'development'
              ? {
                     nodeIntegration: true
                 }
              : {
                     preload: path.join(__dirname, 'dist/renderer.prod.js')
                }
    });
}

createWindow()
```
Then  
```
electron-builder build --mac
```
After installed the app and launched it, there was no file in **~Library/Logs/[AppName]**.

Could anyone help me?

**Comment by megahertz** [comment]
Try to change `log.verbose(`%c${process.env.PATH}`, 'color: red');` to `log.error(`%c${process.env.PATH}`, 'color: red');`. If it's helpful, you need to configure log levels properly.

**Comment by megahertz** [comment]
Please let me know if it doesn't solve the issue

**Comment by Akimotorakiyu** [comment]
@megahertz the question same to me.

**Comment by megahertz** [comment]
@Akimotorakiyu it's not possible to find the exact reason without a sample which reproduces the issue.
