### ISSUE TITLE
Passing console logs depth

### ISSUE THREAD

**Issue by rasgo-cc** [megahertz/electron-log#223]
Currently the console logs have a depth of 2 or 3 I believe. I mean, when printing nested objects, from that depth level they start being printed as `[object Object]`

Any way to pass the depth?

Related: https://nodejs.org/api/util.html#util_util_inspect_object_options

**Comment by megahertz** [comment]
Do you mean console transport?

**Comment by megahertz** [comment]
Currently, util.formatWithOptions used only for file transport, for console direct calling of console.log is used. Currently, I have no plans to change it, but will think about it in the future.

**Comment by megahertz** [comment]
In v5 it's possible to write a custom function for writing to console, eg
```js
log.transports.console.writeFn = ({ message }) => console.log(util.inspect(message.data));
``
