### ISSUE TITLE
disable remote.require call if the remote module has been disabled

### ISSUE THREAD

**Issue by marvinirwin** [megahertz/electron-log#226]
[The remote module is being deprecated and moved to userland](https://github.com/electron/electron/issues/21408)

[loadRemoteModule uses `remote.require` to load itself in the opposite process](https://github.com/megahertz/electron-log/blob/6f94eb73a28e232c8b511edd8c72498472500fe5/src/electronApi.js#L147) 

What would be required to implement this functionality without the `remote` module?  Asking the user to require `electron-log` in their renderer process manually?  Making `electron-log` set up Ipc Channels to call itself?  Would this require that `log` calls from the renderer process be async (To handle the ipcRenderer.invoke)?

**Comment by megahertz** [comment]
Nice question. Currently, I'm going to ask to require 'electron-log' manually. ipc module is necessary only for development and a lot of users don't care about it.

**Comment by Slapbox** [comment]
Hey @megahertz I'm a bit confused. Are there plans to remove the reliance of this library on `remote`?

Is anything going to implode if Electron-Log can't require `remote` and hits this line? https://github.com/megahertz/electron-log/blob/6f94eb73a28e232c8b511edd8c72498472500fe5/src/electronApi.js#L163

**Comment by megahertz** [comment]
@Slapbox There's nothing critical as I mentioned in the previous comment.

**Comment by hhyyrylainen** [comment]
Now with electron 13 each time I reload my app I get this in the browser console (even after updating all places where I used the remote module):
```
(electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
```
And the only line of my code in that warning callstack is this line:
```
const log = require("electron-log");
```
So I think the warning is caused by loading electron-log. I'm using version 4.3.5.

**Comment by megahertz** [comment]
@hhyyrylainen Thanks for informing, I'll try to fix that on the next week.

**Comment by megahertz** [comment]
I removed the code which uses remote module. Unfortunately, I have no idea how to load electron-log automatically in the main process for renderer-to-main ipc transport usage. So, now it requires to do that manually for those who need that feature.

**Comment by hhyyrylainen** [comment]
Thanks for working on this.
It looks like not even electron devs know how to do that as it says on https://github.com/electron/remote#migrating-from-remote
to add the following to the main process script:
```js
require('@electron/remote/main').initialize()
```
