### ISSUE TITLE
Logging works fine until I build my electron app and then log stops showing

### ISSUE THREAD

**Issue by mikeyyyzhao** [megahertz/electron-log#227]
Great library and worked perfectly on local but the moment I built my app and published it, logging stopped working and nothing was showing in our app. Is there a way to keep logging after we've built the app?

**Comment by megahertz** [comment]
Could you provide more details?

**Comment by mikeyyyzhao** [comment]
Sure, while I'm developing (npm run start), I get the logs in inspector. However, after I build the app (Electron build), apps are no longer showing. I've tried manually setting isDev to true but the logs still do not show after I build the app. Maybe there's another config that I need to change?

**Comment by megahertz** [comment]
You need to enable ipc transport for both main and renderer process

**Comment by megahertz** [comment]
Please let me know if it's not solved.

**Comment by andreistreltsov** [comment]
I'm having the same question. How do you actually enable IPC transport? Couldn't find anything.

**Comment by megahertz** [comment]
@andreistreltsov I don't recommended to enable ipc for production. It may impact on performance, also it requires remote module, which will be deprecated in Electron soon.

**Comment by andreistreltsov** [comment]
Thanks for the info. But what is the recommended way to log renderer code then?

**Comment by megahertz** [comment]
A renderer logger instance writes to a log file independently from the main
instance.
