### ISSUE TITLE
Log rotation has a strange behavior

### ISSUE THREAD

**Issue by Wambou** [megahertz/electron-log#228]
Hi,

I am using eletcron-log 4.2.4 and I have a strange behavior for log rotation on Windows 10.
I have overridden the "archiveLog" function so that I can handle multiple rotations and file naming.
But it seems that the size's check is done according to what the logger had to log, and not the actual file size.

Reproduction
-
The scenario is the following one:
- define `maxSize` in the configuration, e.g. 20 MB;
- override `resolvePath`, I needed a specific subfolder for my log files;
- override `archiveLog`, it only adjust the filename and does a `fs.renameSync`;
- create a file with 21 MB, I used `fsutil file createnew` for that;
- start the application and make a log => the file is rotated properly;
- recreate the 21 MB file to try to trigger another rotation;
- log something => the rotation function is not called and log is appended in the file.

If I do the same with smaller size, say 200 B, since the log quickly generates more than that, rotation occurs.
That what makes me think it is base on what the instance effectively logs.

Questions
-
Is this behavior expected ?
I do not have much time to dive into the whole library, that’s why I am asking, but I might do that at some point.

Is there a better way to handle log rotation with different name than overriding `archiveLog` function ?

Is there a simple way to test log rotation ?
I ask that because it’s someone from our Test team that found this _strange_ behavior, from our perspective.

Thank you very much for the answer and taking some time for us.
Best regards.

P.S.: I did not see the "discussion" part before posting, sorry for mixing this with real issues... :flushed:

**Comment by megahertz** [comment]
Sorry for the late response, I've missed your question.

> Is this behavior expected ?
- Yes, a log file size is checked only on initialization, so it won't work correctly if another code writes to the same log file.

> Is there a better way to handle log rotation with different name than overriding archiveLog function ?
- Unfortunately, There's no other way to check log rotation and I have no plans for changing it.

> Is there a simple way to test log rotation ?
It depends on your requirements. You can [look at the test](https://github.com/megahertz/electron-log/blob/master/src/transports/file/__specs__/index.spec.js#L28)

**Comment by megahertz** [comment]
One more thing which could be useful for such a test is calling `log.transports.file.getFile().reset()`, which clear the log file and reset counters.
