### ISSUE TITLE
Logs not appearing for packaged app

### ISSUE THREAD

**Issue by johnryan** [megahertz/electron-log#23]
Hi, i'm using electron-log with electron-builder (specifically https://github.com/chentsulin/electron-react-boilerplate). The logs get written perfectly when i'm running it in dev mode but when i package and run it the logs don't seem to be written anywhere. Is there any recommended way to debug this?

One thing to note the app is running from the /Applications folder on my mac

**Comment by johnryan** [comment]
After some more research it appears that `process.env['HOME']` is undefined for some reason

**Comment by megahertz** [comment]
It seems that it's related to #22, I'm going to fix it soon.

**Comment by johnryan** [comment]
Cool, i'm happy to help or test, though i'm not sure what the approach would be if the process.env variables have been stripped out.
