### ISSUE TITLE
maxSize windows

### ISSUE THREAD

**Issue by Dammmien** [megahertz/electron-log#24]
Hi,

I'm doing some tests and I limited the file size to 100ko :

`log.transports.file.maxSize = 1024 * 100;`

On macOS the size is "respected".
It's always a little bit more but it comes from the way you do your check.
You check the file size is under the limit before to write so it's always a little bit more.
Fine.

But on windows the log rotate is done only when the stream starts.
So I start my electron app, its logs and I have a file size of +3000ko.
I restart my app, the log files is renames .old.log.

Is it the expected behavior ?

**Comment by megahertz** [comment]
I'll try to test it on windows tomorrow.

**Comment by Dammmien** [comment]
Is it possible to make log rotation while we are writing logs and not only at stream opening ?
I can make a pull request if needed.

**Comment by megahertz** [comment]
Thank you for your code. It's good, but there is on problem - it reads file size on every log write. Also I needed to make a small refactoring.

**Comment by Dammmien** [comment]
Works like a charm on macOSX and windows 👍
