### ISSUE TITLE
Changing path (entire path, not only the file name) for the log (Angular 6 app)

### ISSUE THREAD

**Issue by DmitriKom** [megahertz/electron-log#240]
I'm working on an Angular 6 (with electron) app.
I've successfully integrated with the electron-log, using the following TypeScript code (with the help of ngx-electron) -please check out the following link for more details: https://stackoverflow.com/questions/48988829/save-the-log-in-electron-devtools-to-a-file

Now, everything well and I get my logs into the default path:
C:\Users\[USER]\AppData\Roaming\[process-name]\logs

I want to change this default path, for example, to the following path:
C:\ProgramData\[app-name]\logs

I've found the resolvePath function in the documentation, but couldn't understand how do I use it for an Angular app (TypeScript code). Could you please help me? (If I should move this question into the ngx-electron thread, please inform me)

Thank you,
Dima

**Comment by megahertz** [comment]
Do you mean log.transports.file.resolvePath = () => `C:\\ProgramData\\appName\\logs\main.log`?

**Comment by DmitriKom** [comment]
`  public ngOnInit() {
    this.logger = this._electronService.remote.require('electron-log');
    this.logger.transports.file.resolvePath = () => 'C:\\ProgramData\\myApp\\logs\main.log';
    this.logger.info('*** Test! ***');
  }`
  
  I've written the above code, but couldn't find any main.log file in the directory: 
  C:\ProgramData\myApp\logs
  
  (without the resolvePath, it writes successfully to the default path, as I've mentioned in my first post)

**Comment by megahertz** [comment]
Hardcoded path is a bad idea, I gave you just as an example. You need to build the path programmatically. I think it doesn't work because of missed backslash

**Comment by DmitriKom** [comment]
I've already noticed the missing backslash and it hasn't solved the issue.

The line with the hardcoded path was meant just for testing (not a final code).

Anyways, thank you for clarifying the syntax for me , I will try to solve it (it's probably an issue with the path itself). Thanks!

**Comment by megahertz** [comment]
Also, you can try to set resolvePath in the main process instead of a renderer

**Comment by megahertz** [comment]
Please ping me if you still can't solve the issue or there's a way to reproduce the issue easily.
