### ISSUE TITLE
What is the best practice to configure the logger?

### ISSUE THREAD

**Issue by baruchiro** [megahertz/electron-log#244]
I'm not sure what is the best/default/suggested way to configure the logger, in terms of main/renderer.

Today, I'm creating it in the `main`:

```ts
global.logger = CreateLogger(app);
```

Then in the `renderer` I getting it from the `main`:

```ts
const logger: ElectronLog = electron.remote.getGlobal('logger');
logger.info('The renderer process got the logger');
```

This way I have only one log file.

But from the issues here, I see the way the others use it to create a different instance to the main and renderer. How do you suggest doing that? Are you just creating a module to create the logger, then importing it from anywhere?

Or any other way?

**Comment by megahertz** [comment]
It's better to use separated instances for each process. Electron remote module will be deprecated soon.

There's no best way how it could be initialized, it depends on your requirements. If you change a lot of default options, it's better to create a helper function/class for that which could be called from both processes.

**Comment by baruchiro** [comment]
Thanks!
