### ISSUE TITLE
Promise Rejection with Error that has read-only message loses the original stack.

### ISSUE THREAD

**Issue by oleg-slapdash** [megahertz/electron-log#245]
Repro:

1. Setup error reporting on promise rejection.
2. Run this code 
```typescript

(new Promise(resolve => {setTimeout(resolve, 100)})).then(result => {
	  // @ts-ignore
	  Buffer.from(undefined);
});

```
Expected result: having correct stack reported.
Actual result: 
```
Error [UnhandledRejection TypeError]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at process.onRejection (/node_modules/electron-log/src/catchErrors.js:58:18)
    at process.emit (events.js:315:20)
    at process.emit (/node_modules/source-map-support/source-map-support.js:495:21)
    at processEmit [as emit] (/node_modules/signal-exit/index.js:161:32)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processTimers (internal/timers.js:489:9)
```

Problematic line: https://github.com/megahertz/electron-log/blob/master/src/catchErrors.js#L57

**Comment by megahertz** [comment]
When I experimented with it a few years ago, there was no way to get unhandled rejection stack. Is it changed in the latest Electron version?

**Comment by oleg-slapdash** [comment]
@megahertz I am not if I understand you correctly. I think you are talking about async stacks. However, in this case, we lose the original stack of the exception. In the original stack, it will point to a line where `Buffer.from(undefined);` is called. However, currently, it always points to this line `catchErrors.js:58`.

Please try and see if you can spot the difference by commenting out the line 57-59 of catchErrors.js.

**Comment by megahertz** [comment]
So, you mean that an exception contains rejection stack in latest versions. Ok, I'll play with it later.

**Comment by oleg-slapdash** [comment]
@megahertz The code checks if the error message is writable, and if it is not - it discards the original error with the original stack. `Buffer.from(undefined);` throws an error with a read-only message and the code discards the original error. That should not happen.

**Comment by oleg-slapdash** [comment]
Thanks!
