### ISSUE TITLE
How to change log path

### ISSUE THREAD

**Issue by mathudak** [megahertz/electron-log#246]
```
- [ ] bug report
- [ ] feature request
- [X] question
```

### Versions.

electron-log": "^4.3.1
electron": "^11.1.1
electron-builder": "^22.9.1

### Repro steps.

I have an Electron + Angular application and I want to log FE events and REST errors to the log. With default setup everything works as it should. Problem is we have a requirement to change the client log location to where the back-end application keeps its logs.

Default log path (where it works)
``C:\Users\myself\AppData\Roaming\FeApp\logs\client.log``
Path where I should save the logs
``C:\Users\myself\AppData\Roaming\BeApp\FeApp\client.log``

I'm trying to initialize logger from within the Angular application in a dedicated service.

```typescript
  initLogger(): void {
    if (!this.electronService.isElectronApp) {
      this.initDefaultLogger();
      return;
    }

    this.logger = this.electronService.remote.require('electron-log');

    this.logger.transports.file.fileName = this.changeLogFilePath();
    this.logger.transports.file.maxSize = MAX_FILE_LOG_SIZE;
    this.logger.transports.file.level = 'silly';

    const defaultPath = this.logger.transports.file.getFile().path;
    console.log('defaultPath:', defaultPath); 
    // Retruns default and new path concatenated
    // C:\Users\myself\AppData\Roaming\FeApp\logsC:\Users\myself\AppData\Roaming\BeApp\FeApp\client.log

    this.logger.transports.console.level = false;
  }

  // This is how I try to change the log location, the folder is existent, created by installer
  private changeLogFilePath(): string {
    const name = this.electronService.isWindows ? 'appData' : 'home';
    const basePath = this.electronService.remote.app.getPath(name);
    const path = this.electronService.remote.require('path');

    const logPath = path.join(basePath, 'BeApp', 'FeApp');
    const variables = {
      libraryDefaultDir: logPath,
      fileName: LOG_FILE_NAME,
    };

    const result = this.logger.transports.file.resolvePath(variables);
    console.log('result:', result); // Returns correct path: C:\Users\myself\AppData\Roaming\BeApp\FeApp\client.log
    return result;
  }
```

Is it actually possible to do it in such simple manner? Or how exactly should one use the `resolvePath()` method?

**Comment by megahertz** [comment]
It could be something like that

```js
this.logger.transports.file.resolvePath = (vars) => {
  return path.join(vars.libraryTemplate.replace('{appName}', 'BeApp'), 'FeApp', vars.fileName);
}
```

**Comment by mathudak** [comment]
This `(vars)` parameter is bit confusing. What should I provide there or how can I obtain the current version of it?

**Comment by megahertz** [comment]
You shouldn't call this function directly in most cases. It's just an option which allows to flexible configure config path. It seems that I need to change docs for the option.

**Comment by mathudak** [comment]
I'm sorry but I still have no clue how to use this. So far I was only able to introduce various bug. Can you please provide some demo how should I try to achieve this?

**Comment by megahertz** [comment]
Just replace the line `this.logger.transports.file.fileName = this.changeLogFilePath();` by my example

**Comment by megahertz** [comment]
Let me know you still have an issue with it
