### ISSUE TITLE
No level for file log when remote fails to send due to invalid ssl certificate

### ISSUE THREAD

**Issue by JustMyst** [megahertz/electron-log#248]
OS: Windows 10 x64
electron-log version: 4.3.1
NodeJs version : 12.16.3

I think i found a bug in your `fileTransportFactory {... transform.transform() ...}` function inside `src/transports/file/index.js

Steps to reproduce:
1.  Set remote logs (`log.transports.remote`) and file logs (default)
2.  Set remote path to an HTTPS server with NOT valid ssl certificate
3.  Try to send log to remote server

Expected: 

An warning is thrown and logged into file with `[warn]` level

Actual:

warning is logged without any level:
```
[2021-02-16 08:43:20.929] [{level}] electron-log.transports.remote: cannot send HTTP request to https://192.168.80.182/Backend/debug/log-upload/ Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
```
After some debugging I found that message in `fileTransportFactory` has clearly `warn` level

![image](https://user-images.githubusercontent.com/38665029/108035765-9ded0300-7037-11eb-878e-8b8584113dfa.png)

However after transforming "warn" level is not being set

![image](https://user-images.githubusercontent.com/38665029/108035924-da206380-7037-11eb-848a-25053c9a1130.png)

Could You please check this? Similar logs may happen to be saved without log level.

Workaround for invalid ssl certificate:

If anyone runs into same problem, the workaround may be to set `rejectUnauthorized` in requestOptions to false. For TS users it may require importing `RequestOptions` from `https` :
```
import { RequestOptions } from "https";

log.transports.remote.requestOptions = <RequestOptions>{
        rejectUnauthorized: false
    }
```

**Comment by megahertz** [comment]
Thank you for the detailed report. Will fix the issue a bit later.
