### ISSUE TITLE
Arguments to path.join must be strings when using electron-log with react-scripts 

### ISSUE THREAD

**Issue by rocketsciencenerd** [megahertz/electron-log#249]
About the Error:

Using node version 10.16.0
React-scripts version 4.0.3
Electron-log version 4.3.1

Error displays: 
![Screen Shot 2021-03-10 at 5 13 22 PM](https://user-images.githubusercontent.com/29738804/110711628-7e27a580-81c5-11eb-9bc0-6620667e6088.png)
![Screen Shot 2021-03-10 at 5 21 37 PM](https://user-images.githubusercontent.com/29738804/110711632-7f58d280-81c5-11eb-8d7f-694d8fb7897a.png)
![Screen Shot 2021-03-10 at 5 21 46 PM](https://user-images.githubusercontent.com/29738804/110711635-81229600-81c5-11eb-9bee-ea5a179a6705.png)
![Screen Shot 2021-03-10 at 5 22 04 PM](https://user-images.githubusercontent.com/29738804/110711637-8253c300-81c5-11eb-91e4-b1318d2d9a59.png)

Implementation in my app:

```
import log from 'electron-log';

export default class WebSocketService {

    this.ws = new WebSocket(url);
    this.ws.onmessage = (event) => {
        try {
            const e = JSON.parse(event.data);
        } catch (e) {
            log.error('unable to parse event json');
        }
}
```

Removing `electron-log` from the application fixes the issue. 

Anyone else seeing this error? Thank you for the help!

**Comment by megahertz** [comment]
react-script doesn't allow to use nodejs dependencies, so it requires to use [some workarounds](https://github.com/facebook/create-react-app/issues/3575)

**Comment by rocketsciencenerd** [comment]
Will try the workarounds!

**Comment by j-nakashima-vxc** [comment]
@rocketsciencenerd 
Hi, I am having this same problem with my application.
If you can share your solution with me, it would be very helpful.
Thank you.

**Comment by moltenice** [comment]
@j-nakashima-vxc and anyone else that stumbles upon this. Here's how I did it in Typescript:

main.ts:
```typescript
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  })
```

preload.ts:
```typescript
import log from "electron-log"
import { contextBridge } from "electron"

contextBridge.exposeInMainWorld("log", log.functions)
```

Then once the above are done, the rest is done on the renderer process i.e. your React App:

global.d.ts (create this file if it doesn't exist inside src/ for a create react app project):
```typescript
import ElectronLog from "electron-log"

declare global {
  interface Window {
    log?: ElectronLog.LogFunctions
  }
}
```

Finally, anywhere in your React code you can now do:
```typescript
window.log?.info("Here is a log message")
```

Hope this helps
