### ISSUE TITLE
Asynchronous file logging writes out-of-order entries

### ISSUE THREAD

**Issue by adelphes** [megahertz/electron-log#253]
The implementation of asynchronous (sync = false) file logging doesn't guarantee the logs are written out in order.

The (abbreviated) code looks like this:
```javascript
writeLine(text) {
   ...
  this.asyncWriteQueue.push(text);
  this.nextAsyncWrite();
}

nextAsyncWrite() {
    var text = this.asyncWriteQueue.shift();
   fs.writeFile(..., err => {
         this.nextAsyncWrite();
   });
}

```

When `writeLine()` is called multiple times, it results in multiple in-flight `fs.writeFile()` calls - the order in which these calls complete is not guaranteed (that is, the second `fs.writeFile()` might complete before the first one, depending on I/O scheduling).

This is demonstrated by the following:
```javascript
const logger = require('electron-log');
logger.transports.file.sync = false;

for (let i=0; i < 100; i++) {
  logger.info(`${i}`);
}
```
It should log the numbers in order in the file, but doesn't.

(Also note that the code is quite inefficient - it calls `fs.writeFile()` for every single log line pushed to `asyncWriteQueue` - it should probably just write all the buffered entries in a single write each time `nextAsyncWrite()` is called.)

**Comment by megahertz** [comment]
Thank you. As for buffering, I would prefer slower performance rather than loosing critical log records on crash.

**Comment by xmedeko** [comment]
@megahertz 👍 for the quick fix.
I just do not understand your note: "I would prefer slower performance rather than loosing critical log records on crash." IMO even the current solution would loose logs in queue on crash.

**Comment by megahertz** [comment]
Oh, sorry, I've not paying enough attention to your hint. Yes, it could be improved. Will try to improve it later.

**Comment by xmedeko** [comment]
Note: pino hooks handlers to beforeExit, exit, uncaughtException, SIGHUP, SIGINT, SIGQUIT, SIGTERM to flush async logger, see  https://github.com/pinojs/pino/blob/master/docs/asynchronous.md#caveats (But I do not find it necessary.)

**Comment by ramaralo** [comment]
@megahertz 
Is there any update on this?
Thanks

**Comment by megahertz** [comment]
@ramaralo This task has low priority for me, so it won't be changed quickly
