### ISSUE TITLE
create a readonly file  Unable to log

### ISSUE THREAD

**Issue by zhaoxiaolei519109457** [megahertz/electron-log#254]
When creating an object using create(). Found some computers do not have permission to write. Read-only permission

**Comment by megahertz** [comment]
It's not possible to determine the reason without the actual code. Could you make a sample project which reproduces the issue?

**Comment by zhaoxiaolei519109457** [comment]
oh。Yes. maybe I used it wrong. I found that after using the child_porcess get system registry. The files generated again after the log is deleted are read-only
`
const { spawn } = require('child_process');
function getRegedit(regeditPath, name) {
    return new Promise((resolve, reject) => {
        let chunks = []
        process.umask(0o777);
        const childProcess = spawn("reg", ['query', regeditPath, '/v', name])
  
        let {
            stdout,
            stderr
        } = childProcess
        stdout.on('data', function (data) {
            chunks = chunks.concat(data)
        })
        stdout.on('end', function () {
            let buffer = Buffer.concat(chunks)
            resolve(String(buffer))
        })
        stderr.on('data', function () {
            resolve(0)
        })
        childProcess.on('error', function () {
            resolve(-1)
        })
        childProcess.on('close', function (code, signal) {
            log.info(code, signal)
        })
    })
  }

ipc.on('exit_process', (e, arg) => { 
    const HKCU = "HKCU"
    const microphonekey = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\microphone"
    let usMic = path.join(HKCU, microphonekey);
    getRegedit(usMic, 'Value').then(result => {
        log.info(result);
    })
})`

**Comment by zhaoxiaolei519109457** [comment]
Oh, I already know the problem. Because of the process. The umask (0 o777); The permissions have been increased
