### ISSUE TITLE
Use file-stream-rotator for robust file rotation

### ISSUE THREAD

**Issue by xmedeko** [megahertz/electron-log#255]
Just a suggestion: what about to use [file-stream-rotator](https://github.com/rogerc/file-stream-rotator) for the file rotation. It's used in many other projects, including [winston-daily-rotate-file](https://github.com/winstonjs/winston-daily-rotate-file) .

**Comment by megahertz** [comment]
Thank you for the suggestion, but the lib doesn't use streams. Also, I would prefer to keep only basic functionality for some features with possibility to extend if necessary.
