### ISSUE TITLE
UTF-8 log message causes remote logger's payload to be truncated

### ISSUE THREAD

**Issue by reederz** [megahertz/electron-log#259]
Content-Length header is incorrectly calculated here https://github.com/megahertz/electron-log/blob/master/src/transports/remote.js#L74 . Is is being set to string length of the body, instead of byte length.

Consider this snippet:
```js
var log = require('electron-log');
log.transports.remote.level = 'debug';
log.transports.remote.url = 'http://localhost:5000'
log.debug({'foo': 'bar'});

```

The payload received will be valid as expected:
```
{"client":{"name":"electron-application"},"data":[{"foo":"bar"}],"date":1619172197913,"level":"debug","variables":{}}
```

However, if you have UTF-8 characters in your log message, which can be more than 1 byte in size, the payload will be truncated.

E.g.:
```js
log.debug({'föö': 'bar'});
```

Would result in invalid truncated json like so:
```
{"client":{"name":"electron-application"},"data":[{"föö":"bar"}],"date":1619172226499,"level":"debug","variables":{
```

Notice, how payload is truncated by exactly 2 characters, because each `ö` is 2 bytes in size.

Better way would be not to calculate content-length at all or calculate it something like this:
```js
  options.headers['Content-Length'] = (new TextEncoder().encode(body)).length;
```

We use your module in production, and because of this, we lose quite a few log messages due to server json parsing errors :(

**Comment by megahertz** [comment]
Thank you for the report, I'm going to publish a fix on the next week.

**Comment by reederz** [comment]
Ping. If you wish, I can submit a PR.

**Comment by megahertz** [comment]
Thank you, but it's pretty simple.  I need more time for testing rather than writing code.

**Comment by reederz** [comment]
Thanks @megahertz . Just making sure you didn't forget.

In our usecase, we have english log messages, with user input details. And user input can be in whatever language they choose. That's why we have problem with this.

**Comment by reederz** [comment]
If you don't have time, I can try and write test too, no problem.

1. make sure ascii message passes on mock server without json decode error
2. make sure utf-8 with special chars message passes on mock server without json decode error

At this point, I'm not sure what truncates the message based on byte length - client or server...
