### ISSUE TITLE
Configure log paths

### ISSUE THREAD

**Issue by DominikGuzei** [megahertz/electron-log#26]
Hey there, great package - thanks! 👍 
We would like to be able to configure the paths for the various OSes where the log files are created because there are other processes logging stuff at already defined locations (e.g: in a `Logs` subfolder of the current electron-log locations)

**Comment by megahertz** [comment]
If you need to specify file path manually you just need to set log.transports.file.file option

**Comment by DominikGuzei** [comment]
Thanks, i somehow missed that option in the docs 😉
