### ISSUE TITLE
processType return browser or renderer messages [help wanted]

### ISSUE THREAD

**Issue by ajmasia** [megahertz/electron-log#261]
Hi @megahertz, 

When formatting a log message, the `processType` return `browser` or `renderer` messages. Any way to custom these values? Which of the two correspond to the main electron process? I'm confusing with these values 😞 

Thanks!

**Comment by megahertz** [comment]
Hi @ajmasia 

browser is `synonym` of `main`. For customizing, you can use custom variables, see format section of docs.

**Comment by ajmasia** [comment]
Done!
```js
log.variables.appName = `${appReference}-${
  log.variables.processType === 'browser' ? 'main' : 'renderer'
}`
```
