### ISSUE TITLE
App logs to syslog

### ISSUE THREAD

**Issue by johannesjo** [megahertz/electron-log#262]
Hi there! Not sure if this is the right place to address this, but I was hoping to get some help here.

Since I started using electron-log, my sys-log get's swarmed with messages from my app. It's the same as in the main.log but it seems the same messages are logged many times over by messages from the browser layer. While the main.log is just over an mb the syslog get's bloated to multiple gigabytes in just a few seconds. It seems like it is appending the original log string multiple times (potentially exponential).

In my frontend I am using electron-log like so:
```
        const log = (this.remote as typeof remote).require('electron-log');
        console.error = log.error;
```

First of all I am surprised that it logs to the syslog at all, but then again I don*t know much about linux logging.

**Comment by megahertz** [comment]
Hi, electron-log have no integration with syslog. And I've never seen that Electron app can write to syslog out of box. But Chromium can use syslog. Maybe you've enabled debugging output for Electron. I don't know exactly, but there's a chance Chromium sends debug messages to syslog.

**Comment by johannesjo** [comment]
Thank you for your input. Really not sure what caused this tbh. I replaced all occurrences of console.log with electron loggers log also for the electron layer and now the issue seems to be resolved.
