### ISSUE TITLE
Can't use electron-log in the preload script while global sandbox is turned on

### ISSUE THREAD

**Issue by Willyfrog** [megahertz/electron-log#267]
when trying to import electron-log with global sandbox enabled I get this error in the preload script which is causing it to fail to load.
```
Error: module not found: os
```
removing electrton-log import seems to take care of it, is there a way to prevent electron-log from loading 'os' in for the preload script?

**Comment by megahertz** [comment]
Currently, I have no plans to support sandbox mode. But I'll think on the feature in the next major version.

**Comment by Slapbox** [comment]
@megahertz this isn't just an issue with `sandbox`. It breaks with the less restrictive `contextIsolation` as well. Even after adding fallback entries in Webpack, it continues to throw fatal errors.

Merely the following line crashes everything if put into preload:

```js
import log from 'electron-log';
```

**Comment by eliw00d** [comment]
Given [the recommended practice from Electron is to sandbox](https://www.electronjs.org/docs/latest/tutorial/security#4-enable-process-sandboxing), and that [contextIsolation is on by default](https://www.electronjs.org/docs/latest/tutorial/security#3-enable-context-isolation), I would hope this is a feature that could be added!

**Comment by megahertz** [comment]
@eliw00d I'm already thinking on that.

**Comment by megahertz** [comment]
Done in v5
