### ISSUE TITLE
Cannot detect dev env in renderer process

### ISSUE THREAD

**Issue by zhuhaow** [megahertz/electron-log#268]
The current logic, https://github.com/megahertz/electron-log/blob/master/src/electronApi.js#L114-L127, checks for the `app` first, which would not be defined on renderer process (since `remote` is disabled by default and will be removed in the next major release).

The check then would compare if the process execpath ends with "electron", which on my mac ends with `.../node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS/Electron Helper (Renderer)`, thus it would return `false` for electron renderer process.

**Comment by megahertz** [comment]
Thank you for the provided details, fixed in v4.4.1

**Comment by zhuhaow** [comment]
Thanks for the quick fix
