### ISSUE TITLE
electron-log prints to dev console when called in main process

### ISSUE THREAD

**Issue by waxmoronic** [megahertz/electron-log#269]
My application calls ipcRenderer.send to send data to the main process where it is logged. I'm trying to log only to a file (which works fine) and not the console. I was able to suppress printing to the main console with "log.transports.console.level = false", but for some reason I get prints into the dev console. electron-log is only called from main. This doesn't happen when packaged, only when running from source.

Sample:
apis.js
```
const { ipcRenderer } = window.require("electron");
...
export const loggerHelper = (com, args, json, type) => {
    if (type === "command") {
        ipcRenderer.send("write-application-log-file", [`Command issued: ${com} ${args}`, type]);
    } else {
        ipcRenderer.send("write-application-log-file", [`Response to ${com} ${args}: ${json}`, type]);
    }
}
```

main.js
```
const log = require('electron-log');
...
log.transports.file.maxSize = 5 * 1024 * 1024;
log.transports.console.level = false; // disable main console prints for electron-log
log.transports.file.resolvePath = () => path.join(logFilesFolderPath, logFileName);
...
ipcMain.on('write-application-log-file', (event, args) => {
    if (args[1] === "error") {
        log.error(args[0]);
    } else {
        log.info(args[0]); 
    }
});
```

**Comment by megahertz** [comment]
You need to set the option `log.transports.console.level = false` in a renderer process too.

**Comment by waxmoronic** [comment]
Works great, thank you!
