### ISSUE TITLE
Possible to output logs to Chromium Developer Tools Console?

### ISSUE THREAD

**Issue by karldd** [megahertz/electron-log#27]
I'm trying out electron-log and it looks great.
It seems (on Windows at least) that output goes to the terminal/shell used to launch my (electron) app rather than the Chromium Developer Tools Console inside the app.
Is this something that can be configured?

**Comment by megahertz** [comment]
It's not possible now, but I thought about this feature too. I'll try to add this feature on the next week.

**Comment by karldd** [comment]
Great. The developer tools console has a number of useful features so would be great to have that option.

**Comment by baruchiro** [comment]
Any updates?

**Comment by megahertz** [comment]
@baruchiro It has been implemented in v2. Please create a new issue if you have any problems with it.
