### ISSUE TITLE
contextBridge and how to prevent logs

### ISSUE THREAD

**Issue by xavier7179** [megahertz/electron-log#276]
I wanted to have a log system that makes it possible to turn all logs off when the app is in production mode. I followed the guideline and did something like this in the preload script (which works smoothly, btw...):

```
const log = require("electron-log");

contextBridge.exposeInMainWorld("electronApp", {
	log: log.functions,
	...
});
```
Then if in the main process I add the following two lines:
```
const log = require("electron-log");

log.transports.file.level = false;
log.transports.console.level = false;
```
I still see the logs from the renderer. Did I miss something or is it a bug?

**Comment by megahertz** [comment]
You need to do the same in the renderer process too.

**Comment by Slapbox** [comment]
@megahertz how is this supposed to be used in conjunction with preload? It seems impossible to configure it in any way except to disable it entirely. Every attempt to access `log.transports.____` results in some error or another. 

Attempting to set `log.transports.file.maxSize` gives an object not extensible error. Attempting to set `console.level` or `file.level` to `info` results in: "Path must be a string. Received undefined"

What's the right way to handle this besides disabling the logger for the entirety of our preload-script logic?

**Comment by Slapbox** [comment]
Actually I guess the real issue was that we were importing `electron-log` in the `renderer`.
