### ISSUE TITLE
how to set color to custom logs

### ISSUE THREAD

**Issue by kevinwang930** [megahertz/electron-log#277]
below is my custom log code,  I expect the format can accept a function with level argument, so I can set format based on different levels, but it seems I can not set colors in format string directly, is there any way to achieve this ?
```
let mainLog = electronLog.create('mainLog')
mainLog.transports.file.level = false
mainLog.transports.ipc.level = false
mainLog.transports.console.useStyles = true
mainLog.transports.console.level = process.env.LOG_LEVEL.toLowerCase()
mainLog.transports.console.format = (logMessage)=>{
    if (logMessage.level === "info") {
        return '[{h}:{i}:{s}] [main] [{level}] {text}'
    } else {
        return '[{h}:{i}:{s}] [main] [{level}] {text}'
    }
    }
```

**Comment by megahertz** [comment]
The easiest way of implementing colors in a formatter inside the main process is using [chalk](https://www.npmjs.com/package/chalk) module. In this cases it could be something like
`return chalk.yellow('[{h}:{i}:{s}] [main] [{level}] {text}');`

**Comment by kevinwang89** [comment]
not works, I use below code 
```
mainLog.transports.console.format = (logMessage)=>{
    if (logMessage.level === "info") {
        return chalk.green('[{h}:{i}:{s}] [main] [{level}] {text}')
    } else {
        return '[{h}:{i}:{s}] [main] [{level}] {text}'
    }
    }
```

the console output 
```
[{h}:{i}:{s}] [main] [{level}] {text}
[{h}:{i}:{s}] [main] [{level}] {text}
[{h}:{i}:{s}] [main] [{level}] {text}
[{h}:{i}:{s}] [main] [{level}] {text}
[{h}:{i}:{s}] [main] [{level}] {text}
```

**Comment by megahertz** [comment]
Sorry, I forgot that text in a formatter function should be processed manually. It than is passed to console.log directly

**Comment by kevinwang930** [comment]
spent some time reading the source code, format the string manually seems not a good idea,  it add complexity.
