### ISSUE TITLE
Allow to reinitialize console transport

### ISSUE THREAD

**Issue by clemp6r** [megahertz/electron-log#278]
Currently `console.js` in electron-log makes references to console functions (e.g `console.log`, etc.) during module initialization ([source](https://github.com/megahertz/electron-log/blob/35535062403df2c3ac6e73a5d5d8886adfcab861/src/transports/console.js#L7)).

This can lead to problems if the application (or its libraries) then make replacements of these functions.

For instance, the Sentry library replaces (wraps) console functions when it is initialized (call to `Sentry.init`) ([source](https://github.com/getsentry/sentry-javascript/blob/bdcf13321c0795d3ab31a8bd02f5566b63cb7c86/packages/utils/src/instrument.ts#L113)) so it can intercept all log messages and report them to the Sentry service. As `electron-log` keep reference to the original/unwrapped functions, all messages created with `electron-log` are invisible to Sentry.

As a consequence this makes `electron-log` unusable for projects that uses Sentry or similar libraries.

It would be nice to have a way to tell `electron-log` to reinitialize its console transport.
Or (maybe better) `console.js` would be partially rewritten so it does not keep references to console functions at module initialization and instead uses the `console` object again each time its methods need to be called.

Thanks for any feedback

**Comment by stoefln** [comment]
We would also like to use it in combination with Sentry... @clemp6r  did you find a workaround?

**Comment by clemp6r** [comment]
@stoefln No, we just postponed integration of log files for now.

**Comment by clemp6r** [comment]
Any update? Is there a possibility we have a quick workaround until v5 is out?

**Comment by clemp6r** [comment]
See my PR that fixes the issue: https://github.com/megahertz/electron-log/pull/330

**Comment by megahertz** [comment]
Thank you @clemp6r . Unfortunately, I can't approve this PR. While it solves an issues with Sentry, it breaks the following case: `Object.assign(console, log.functions);`. Please let me know if I missed something.

Anyaway, I'm going to publish v5 beta in the next 2-3 weeks

**Comment by clemp6r** [comment]
Ok, no problem, I will close the PR and keep the change for myself.

**Comment by megahertz** [comment]
In v5 console transport has `writeFn` which allows to override a console call.
