### ISSUE TITLE
Custom serialization for types using file transport

### ISSUE THREAD

**Issue by tomsseisums** [megahertz/electron-log#286]
I like the default file transport, except it doesn't serialize `Set` properly.

Using:
```js
logger.debug('Logging some object', {
  something: "stringy",
  other: 5,
  set: new Set(['a', 'b', 'c'])
})
```

Produces:
```log
[2021-12-23 18:51:05.466] [debug] (scopeName)    Logging some object {
  something: 'stringy',
  other: 5,
  set: {}
}
```

Because `JSON.stringify(new Set(['a', 'b', 'c']))` actually produces: `{}`.

Any way to hook into serialization logic to extend it? `Set` isn't the only one giving me headaches. I looked into using `Set.prototype.toJSON`, but that updates the logic globally which isn't what I need.

**Comment by megahertz** [comment]
That surprises me too. Will add custom map and set serializations
