### ISSUE TITLE
Developer tools: get log origin line number

### ISSUE THREAD

**Issue by vincelwt** [megahertz/electron-log#29]
Hi,
I saw you just recently enabled logging in the developer tools console, thanks for that.

Do you think it would be possible to be able to see from which line the log was emitted ? This is the console.log() behavior, and is very useful during development, especially to find error sources.

Currently, all log produced is showing as origin the js file of the module.

![log](https://cloud.githubusercontent.com/assets/5092466/24871522/21cb8800-1e1a-11e7-8b2e-6a8d3b42aa92.png)

Thanks.

**Comment by vincelwt** [comment]
Maybe this can help: http://stackoverflow.com/questions/13815640/a-proper-wrapper-for-console-log-with-correct-line-number

**Comment by megahertz** [comment]
Hi. Maybe I'll try to experiment with it when I have free time. But for me this task isn't very important, but it requires a lot of time. So, I can't promise anything.

**Comment by vincelwt** [comment]
I understand, thank you.

**Comment by karldd** [comment]
I took a look at this today, as I too would like this feature. After trying a few things (overriding `console.log`, calling console.trace(), generating Errors() and pulling the stack etc...) I couldn't get anything to really replicate the behavior of `console.log` line numbers satisfactorily.

I did come across [stacktracejs](https://www.stacktracejs.com/), but found it to be too slow to use for every log call as it potentially has to delve into the source maps.

Likewise, I noticed Bunyan has a note here about their [`src`](https://github.com/trentm/node-bunyan#src) option that gives you line numbers:

> WARNING: Determining the call source info is slow. Never use this option in production.

**Comment by megahertz** [comment]
I searched a lot how to customize log output in DevTools console, and it seems that it's not possible to replace a default call stack (except for blackboxing manually). 

But if you just want to include line info in log, you can use a hook similar to:
```js
'use strict'

const log = require('electron-log');

log.hooks.push(stackHook);

function stackHook(msg) {
  const stackError = new Error();
  const lines = stackError.stack.split(/^\s+at/m);
  const calledAt = lines[4].trim();

  msg.data.push(`Caller: ${calledAt}`);
  return msg;
}

main();

function main() {
  log.warn('test');
}
```
