### ISSUE TITLE
debug level not shown 

### ISSUE THREAD

**Issue by franz-geiser** [megahertz/electron-log#295]
log.transports.file.level = false;
log.transports.console.level = "silly";
contextBridge.exposeInMainWorld("log", log);

in a component i call
    log.error("error")
    log.warn("warn")
    log.info("info")
    log.verbose("verbose")
    log.debug("debug")
    log.silly("silly")

on the console i get
11:58:28.441 › error
11:58:28.446 › warn
11:58:28.447 › info
11:58:28.448 › verbose
11:58:28.449 › silly

The debug log is missing

**Comment by megahertz** [comment]
Try wherever console.debug works for you. There's a chance it's just hidden by Dev tools settings.

**Comment by franz-geiser** [comment]
> Try wherever console.debug works for you. There's a chance it's just hidden by Dev tools settings.

You are right, also console.debug is not printing on the console:
  console.log('log')
  console.debug('debug')
  console.warn('warn')
  console.error('error')
gives in the console:
  log
  warn
  error

Thank you @megahertz
