### ISSUE TITLE
Handle case where os.homedir() can fail

### ISSUE THREAD

**Issue by bhj** [megahertz/electron-log#300]
Hey, thanks again for this super-useful library.

I ran into an issue when testing my app on a Synology NAS (via Docker), where the best practice is to create a limited user for each container. The problem is that by default, the Synology doesn't actually create a home folder for these users (questionable, I know, but it's been like this since at least 2013 and shows no signs of changing: https://community.synology.com/enu/forum/17/post/62568)

This means [the call to os.homedir](https://github.com/megahertz/electron-log/blob/master/src/transports/file/variables.js#L41) fails wth:
```
code: 'ENOENT',
message: 'no such file or directory',
syscall: 'uv_os_homedir'
```

I think there are two potential easy fixes:

1. Invert the logic so that `process.env.HOME` gets priority if set, avoiding the call to `os.homedir`, or
2. Wrap the `os.homedir` call in a try/catch, then fall back to `process.env.HOME`

Let me know what you think, and happy to submit a PR. Thanks!

**Comment by megahertz** [comment]
Wow, what a rare case. It's possible to wrap the call by a try/catch block, but I'm not sure whether the related issue occurs in another part of code since the path from process.env.HOME still doesn't exist. Please let me know if you found a good workaround which works in the environment.

**Comment by bhj** [comment]
The workaround would be to set `HOME` to a location that exists, so it sounds like #1 might be the best option, and actually more correct behavior since env vars are typically used to override defaults.

(Ideally, none of this code would run at all, but there isn't currently a way to disable the file transport before it gets initialized. An issue for another day though!)

**Comment by megahertz** [comment]
Yes, I have a plan to change this behavior in the next major release since that's no the only issue related to early file transport initialization.

**Comment by bhj** [comment]
Awesome, in the meantime, what do you think about reversing the logic for `HOME` detection? I can't say whether that's a major or minor change, but seems like it'd be more inline with convention?

**Comment by megahertz** [comment]
Do you mean implementing lazy initialization of file transport or HOME detection? TBH, I have no idea what to do in a case HOME doesn't exists.

**Comment by megahertz** [comment]
Under the hood, os.homedir reads HOME and checks whether it exists. So, it works fine when the env is set correctly. If HOME isn't set / path doesn't exists I don't think another code after `os.homedir` can work correctly

**Comment by bhj** [comment]
I thought so too... maybe it has to do with how the problem process is being forked. I'll play with it more and close this for now. Thanks again and happy to test the next major release if needed!
