### ISSUE TITLE
Default logs folder is created on app start

### ISSUE THREAD

**Issue by ronniexue** [megahertz/electron-log#301]
On module load, getPathVariables will call electron API https://github.com/megahertz/electron-log/blob/16b352634887d21d155bc6bcd5af09ac8bb129bc/src/transports/file/variables.js#L103 to get the logs folder which will cause a logs folder to be created before application has a chance to change the logs folder. This is the behavior documented - https://www.electronjs.org/docs/latest/api/app#appgetpathname.

It might be better if we could only do this after application called any electron-log APIs so that application could redirect the logs path.

**Comment by megahertz** [comment]
I'm going to implement lazy initialization for variables in v5

**Comment by megahertz** [comment]
done
