### ISSUE TITLE
[help wanted] Endless writing to log files

### ISSUE THREAD

**Issue by Moon1102** [megahertz/electron-log#302]
I use Electron v14.2.5 + Vue v3.0.0. When renderer process has UI issue, (and Vue.js check it, I guess), then renderer.log file is quickly filled by ```[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead. ``` .  And with endless log writing, the page will get stuck.

**Comment by megahertz** [comment]
I've never seen such an issue before. Are you sure that it isn't called many times?

**Comment by Moon1102** [comment]
请联系我的 QQ726451484

**Comment by megahertz** [comment]
I have no QQ. Please make sure that this isn't called from your code. If that's really a library bug, please try to share a project which reproduces the bug.

**Comment by Moon1102** [comment]
> I've never seen such an issue before. Are you sure that it isn't called many times?

I will try to make a minimized project and put link on next comment

**Comment by Moon1102** [comment]
@megahertz  Hi~ The code is here: [https://github.com/Moon1102/electron-log-test.git](url). <br> Please look at  /[project dir]/src/view/page1/Page1.vue  😿

**Comment by megahertz** [comment]
Thank you. Unfortunately, I'm too busy at this moment, so I can't dive into it right now.

Anyway, it looks like when assign log functions to console object something goes wrong in such an environment.
So, as a temporary workaround it should be avoided.

**Comment by Moon1102** [comment]
Okay, I'm not in a hurry. BTW, If it is an correct page, I mean, If Vue.js did'n check for any problems, assign log functions to console object is ok as well. Actually,it works well on my another page but my project is a co-operation project so it's hard to let everyone make no mistakes😿

**Comment by megahertz** [comment]
There are a lot of things changed in v5, so you can try that build. If it still have the issue, could you update the example and let me know please?
