### ISSUE TITLE
Log writing failed after deleting the log file

### ISSUE THREAD

**Issue by wb-wenbei** [megahertz/electron-log#305]
I add a button to delete the log file,log writing failed after deleting the log file and catch the warning:

[electron-log.transports.file: Can't write to /.../main.log Error: Couldn't write to /.../main.log. ENOENT: no such file or directory, open '/.../main.log']

I do not find the Interface to recreate the log file

**Comment by megahertz** [comment]
Have you deleted the directory too?

**Comment by wb-wenbei** [comment]
yes ,like 'logger/2022/4/1/main.log',delete them all

**Comment by megahertz** [comment]
The directory isn't recreated on writing, only on initialization. So you could delete files only or recreate the directory in your code.

**Comment by wb-wenbei** [comment]
I find the interface to createFile, but it is not open. It is recommended to open the create file interface. 
'FileRegistry.prototype.createFile'

**Comment by megahertz** [comment]
Thanks for the feedback. I'm not sure about that but I'll think on it in the next major release.
