### ISSUE TITLE
onRendererError got a null error from error event

### ISSUE THREAD

**Issue by axetroy** [megahertz/electron-log#310]
![截屏2022-07-13 11 23 53](https://user-images.githubusercontent.com/9758711/178644173-6548c877-58d5-4940-9ddd-7d25aa0978db.png)

Therefore, it is strange to print null in the Console

**Comment by megahertz** [comment]
So, it looks like in some cases event.error is null and it makes sense to create a new error from event.message instead?

**Comment by axetroy** [comment]
> So, it looks like in some cases event.error is null and it makes sense to create a new error from event.message instead?

Yes, I think this is in line with expectations

**Comment by megahertz** [comment]
Fixed in v5
