### ISSUE TITLE
help wanted: display realtime logs in a div of browserwindow

### ISSUE THREAD

**Issue by dewiweb** [megahertz/electron-log#314]
I want to use electron-log display realtime main+renderer logs in a div of my window electron app but don't know how?
debug Console in a window in depth!
No problem to make electron-log working but after...
If you've got an idea and a quick example...please

**Comment by megahertz** [comment]
Try something like that
```js
const div = document.getElementById('logs');
log.transports.div = (msg) => logs.insertAdjacentText('beforeend', JSON.stringify(msg.data));
log.transports.div.level = 'silly';
```

**Comment by dewiweb** [comment]
Ok, seems to works ! Regards.
