### ISSUE TITLE
Missing dependencies - fs, os, electron

### ISSUE THREAD

**Issue by hepiyellow** [megahertz/electron-log#32]
Hi,

Am I missing something? or do these dependencies really are missing from `package.json`

- main.js and renderer.js require `electron`
- file transport requires : `fs` and `os`

**Comment by megahertz** [comment]
Hi. The build-in modules aren't considered dependencies.

**Comment by hepiyellow** [comment]
Well, 
I have been having `require` issues.
And I am using the [Cross-Builder](https://github.com/zalmoxisus/crossbuilder), which uses a very old version of `electron-builder` (version 2.10.0, while current version is 17.0.0).

So I guess, it might be the electron-builder, or wrong web pack config.

But generally, when you say "built-in" you mean included in the `electron` npm package?
If so, shouldn't `electron` be a peerDependency?

**Comment by megahertz** [comment]
Actually, it uses this config https://github.com/zalmoxisus/crossbuilder/blob/master/webpack/electron.config.js

I can't include electron as peerDependency because sometimes this package is used with nw.js or node.
