### ISSUE TITLE
reverse the logs

### ISSUE THREAD

**Issue by yishayhazan** [megahertz/electron-log#332]
as someone who's trying to read the logs, it's kind of weird that they are sorted "down" by date,
I would expect to see the newest log on the top,

maybe you could add this as optional?

thanks a lot.

**Comment by megahertz** [comment]
Do you mean log files? There's a reason why nobody doing that - in that case you should overwrite the whole file once new line is added. It's expensive, it may lead to data loss, impact on battery consumption and SSD health.

So it's much better to reverse lines using js code or `tac` command
