### ISSUE TITLE
Optionally add process id to logs

### ISSUE THREAD

**Issue by uSkizzik** [megahertz/electron-log#334]
Hi! I'm working on an electron application (obviously) and as far as I can see it's not possible to add the process id to the logs.  
It would be beneficial for multi-process apps to add this as a formatter option.  

I personally need to log PIDs because I use a second elevated process when downloading files in my app so that it can store these files in folders that require elevated permissions. However, when downloading I'd like to log the progress to the same file the main process is logging to and this can be quite confusing... unless the process id is also logged.

**Comment by megahertz** [comment]
You can set custom variables for that https://github.com/megahertz/electron-log/blob/master/docs/transports/format.md

**Comment by uSkizzik** [comment]
Ahh mb, I missed that part. Thanks!
