### ISSUE TITLE
When console transport is enable, `addLevel` will cause error. `consoleMethod is not a function`

### ISSUE THREAD

**Issue by pouriamoosavi** [megahertz/electron-log#336]
Hi hope you are well.

When I don't disable the console transport and add a costume new level and call it, it will throw below error:
> Unhandled TypeError: consoleMethod is not a function

It seems that it is trying to call my new method on original NodeJS console. (Maybe here? [console.js#L44](https://github.com/megahertz/electron-log/blob/c040fecb71c69cb4c3dcb0bef4e03a07ed2f3e06/src/transports/console.js#L44))

My complete code:
```
const electronLog = require("electron-log")
// ...
app.on('ready', () => {
  electronLog.initialize({preload: true}) // Deleting this line won't fix the error
  electronLog.addLevel('notice', 2); // Changing 'notice' or the level to another number won't fix the error
  electronLog.notice("App started");
}
```

**Comment by pouriamoosavi** [comment]
I think new methods that are added by `addLevel` should also be added to `consoleMethods` object. [(console.js#L10)](https://github.com/megahertz/electron-log/blob/c040fecb71c69cb4c3dcb0bef4e03a07ed2f3e06/src/transports/console.js#L10)

**Comment by megahertz** [comment]
Thank you for the report, should work fine now

**Comment by pouriamoosavi** [comment]
Works great.
Thanks for the quick fix!
