### ISSUE TITLE
Can't get log.infos to work

### ISSUE THREAD

**Issue by benjam1n** [megahertz/electron-log#34]
Sorry this is probably super dumb questions but how do I force it to write logs not only for log.error/warn but also for log.info?

I tried something like this but no luck.
```
var log = require('electron-log')
log.transports.console.level = 'info'
```

**Comment by megahertz** [comment]
Maybe you need to set the info level to file transport instead of console?

**Comment by benjam1n** [comment]
@megahertz Maybe, yes, maybe... stupid me. Thanks! :)
`log.transports.file.level = 'info'` is what I needed.
