### ISSUE TITLE
Log files not getting created in a regular interval of time.

### ISSUE THREAD

**Issue by monica-muthukumaran** [megahertz/electron-log#340]
I was trying to create logfiles with UTC_Timestamps as their file name. 
Expectation: A new log file has to be created in regular interval of time.

Tried out : 
![image](https://user-images.githubusercontent.com/98094574/213514766-2685883d-01d3-48c0-bfd0-3302c0610712.png)

Log files are not getting generated

**Comment by megahertz** [comment]
Which electron-log version do you use?

**Comment by monica-muthukumaran** [comment]
v4.4.8 @megahertz

**Comment by megahertz** [comment]
Try v5 beta

**Comment by monica-muthukumaran** [comment]
It didn't work:
![image](https://user-images.githubusercontent.com/98094574/213651144-80d9af25-3373-48cb-a2f3-86dc487dfa37.png)
![image](https://user-images.githubusercontent.com/98094574/213651381-a2f4dece-003e-4a7c-92f6-71290982d3dc.png)
And the LOG Folder:
![image](https://user-images.githubusercontent.com/98094574/213651457-734ab965-e942-4267-b596-b888ad657d5f.png)
@megahertz , "check-on-interval" is getting consoled.

**Comment by megahertz** [comment]
Will check later. Currently, you can try to make a log path using path.join instead of direct concatenating, maybe that's the reason

**Comment by monica-muthukumaran** [comment]
Path.join() gives me a log file **only once.** 
![image](https://user-images.githubusercontent.com/98094574/213655776-35c2c04f-2032-4707-81cd-81ae4ce1f5fe.png)

![image](https://user-images.githubusercontent.com/98094574/213655924-b956c11f-a63a-4f8f-894e-2557ad38f2cd.png)

**Comment by monica-muthukumaran** [comment]
Got it working!.

**Comment by agnel-inveox** [comment]
I was working on something similar. What I'm thinking is archiving current log file when the day changes and use a new log file.

Any suggestions @monica-muthukumaran and @megahertz ?

**Comment by megahertz** [comment]
@agnel-inveox  `resolvePathFn` from the last monica-muthukumaran's example should work

**Comment by agnel-inveox** [comment]
> @agnel-inveox `resolvePathFn` from the last monica-muthukumaran's example should work

@megahertz 
ok. let me give it a try.
