### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by monica-muthukumaran** [megahertz/electron-log#341]
Hey! I was trying to handle errors in electron-log.
Scenario: If a user tries to log in an un-authorized location exception to be caught and handled accordingly.

`logger.transports.file.resolvePath = () => 'C:/Users/Administrator/Logs' + `\\main_${Date.now()}.log`
  logger.transports.file.resolvePath(); 
logger.catchErrors();`

the below error is not handled by try catch aswell
![image](https://user-images.githubusercontent.com/98094574/213935733-d39f5456-2ee6-4b56-a17a-58d5ee620647.png)

**Comment by megahertz** [comment]
Log functions shouldn't throw errors, otherwise it may break the whole app since such a call is widely used across the whole app in most cases. A custom log path should be used carefully.

**Comment by monica-muthukumaran** [comment]
Is there any alternative way atleast a one-time catch, later we could play around with flags.?

**Comment by megahertz** [comment]
The only way is checking whether a file is writable before initializing a logger.
