### ISSUE TITLE
resolvePathFn doesn't use the path specified when logging from the renderer process

### ISSUE THREAD

**Issue by gurvancampion** [megahertz/electron-log#343]
Hi,

I'm building an electron app with nuxt 3 and added electron-log `5.0.0-beta.15`
I'm using the logger inside the main process and the renderer process. I added a custom `format` and `resolvePathFn` to have the log files saved by day. 

Below is my class Logger:

```ts
import path from 'path'
import type { Logger as LoggerType } from 'electron-log'
import electronLog from 'electron-log'

class Logger {
  private static instance: Logger
  private logger: LoggerType

  constructor() {
    // Create logger
    this.logger = electronLog.create({ logId: 'my-app' })
    this.logger.transports.console.format
    = this.logger.transports.file.format
    = '[{y}-{m}-{d} {h}:{i}:{s}.{ms}] [{level}] {text}'
    // Set the log file name to the current date YYYY-MM-DD
    this.logger.transports.file.resolvePathFn = (variables) => {
      return path.join(variables.libraryDefaultDir, `${new Date().toLocaleDateString('en-CA')}.log`)
    }
    this.logger.initialize() // Init for renderer process
  }

  public static getInstance(): Logger {
    if (!Logger.instance) {
      Logger.instance = new Logger()
    }

    return Logger.instance
  }

  info(...params: any[]) {
    return this.logger.info(...params)
  }

  warn(...params: any[]) {
    return this.logger.warn(...params)
  }

  error(...params: any[]) {
    return this.logger.error(...params)
  }

  debug(...params: any[]) {
    return this.logger.debug(...params)
  }

  verbose(...params: any[]) {
    return this.logger.verbose(...params)
  }
}

export default Logger.getInstance()

```

How I use it in the main process
```ts
import Logger from '../core/Logger'

Logger.info('Log from main process')
```

How I use it in the renderer process
```ts
import log from 'electron-log'

log.info('Log from renderer process')
```

When I log information from the main process, logs are correctly saved in the log file with the path specified but when I log from the renderer process they are saved in the default log file `main.log`:
![image](https://user-images.githubusercontent.com/32047986/215532282-5e277353-9521-4544-9402-a390fde6fa2e.png)

A workaround I found is to redeclare resolvePathFn as below so logs from the renderer process are correctly saved in the correct log file:

```ts 
import path from 'path'
import type { Logger as LoggerType } from 'electron-log'
import electronLog from 'electron-log'

// Somehow we need to redefine resolvePathFn here
// Otherwise the logs from the renderer process are saved in the wrong file
electronLog.transports.file.resolvePathFn = (variables) => {
  return path.join(variables.libraryDefaultDir, `${new Date().toLocaleDateString('en-CA')}.log`)
}

class Logger {
...
```

**Comment by megahertz** [comment]
Since you created a custom logger ('my-app') in the main process, there are two logger instances. To use a custom instance, you need to set logId in the renderer process too.

**Comment by gurvancampion** [comment]
@megahertz Thanks for your quick reply! 
So if I understand correctly either I don't create any instance and it would use the same config for resolvePathFn? Or I need to make as well an instance in the renderer process with the same `logId`?

**Comment by megahertz** [comment]
Yes. Both ways are possible. But I can't recommend using multiple logger
instances until you really need that, especially while it's still a beta.

вт, 31 янв. 2023 г., 23:28 Gurvan ***@***.***>:

**Comment by gurvancampion** [comment]
Thanks, I used only one instance
