### ISSUE TITLE
Error: preload file ... doesn't exist  at initializePreload (package version, Mac, arm64)

### ISSUE THREAD

**Issue by bladerunner2020** [megahertz/electron-log#344]
When I user electron-log under dev-environment it works, but in packaged version I got this error:

```
[2023-02-01 22:51:52.406] [warn]  Error: Preload file /Users/a.pivovarov/projects/electron-log-test/release/build/mac-arm64/ElectronReact.app/Contents/Resources/app.asar/dist/renderer/preload.js doesn't exist
    at initializePreload (/Users/a.pivovarov/projects/electron-log-test/release/build/mac-arm64/ElectronReact.app/Contents/Resources/app.asar/dist/main/webpack:/node_modules/electron-log/src/main/initialize.js:33:11)
    at /Users/a.pivovarov/projects/electron-log-test/release/build/mac-arm64/ElectronReact.app/Contents/Resources/app.asar/dist/main/webpack:/node_modules/electron-log/src/main/initialize.js:16:11
```
Node: v14.21.1
Electron: "^20.0.2"
electron-log: "^5.0.0-beta.15"

How to reproduce:
- Clone [Electron React Boilerplate](https://electron-react-boilerplate.js.org/)
- Update to the latest version of electron-log (npm install electron-log@beta)
- Add initialisation to main.ts
- Add log.info to renderer

**Comment by megahertz** [comment]
Thanks for the report. I'll try to investigate that in the next week.

electron-log expect that [this file](https://github.com/megahertz/electron-log/blob/master/src/renderer/preload.js) is induced to a packaged app archive.

Temporary workarounds:
- use `log.initialize({ preload: PATH_TO_PRELOAD_FILE });`
- if you use a custom preload script, add `import 'electron-log/src/renderer/preload')` there.

**Comment by znnan** [comment]
I have encountered the same issue, the first workaround doesn't work because the path is loaded at the runtime, after compiling the electron-log in node_module can't be found anymore.

Regarding the second workaround, where should it be imported? 

Thanks

**Comment by megahertz** [comment]
@znnan Somewhere in your preload script.

**Comment by bladerunner2020** [comment]
> @znnan Somewhere in your preload script.

I was not able to figure out how to add a customer preload script and get it bundled...
As workaround implemented my own ipc channel ))

**Comment by megahertz** [comment]
Added a workaround for that case. Should work fine without code change
