### ISSUE TITLE
Default Directory

### ISSUE THREAD

**Issue by monica-muthukumaran** [megahertz/electron-log#345]
![image](https://user-images.githubusercontent.com/98094574/216256430-3bc1ccf5-9de0-4540-863d-a030abdba0dd.png)
Hey, I'm wondering, is there a way at which I get and store this default path is a variable. So that I can use if for access checks and so on.

**Comment by megahertz** [comment]
`log.transports.file.getFile().path`

**Comment by monica-muthukumaran** [comment]
Thank you.

**Comment by monica-muthukumaran** [comment]
Hey, There is a mis-match
![image](https://user-images.githubusercontent.com/98094574/216308173-98dbe550-54f8-4e0d-80cc-d3df2a374da5.png)
The above is the console.

But I have the files logging in C://user/Desktop/Code-Directory
The is the line responsible for logging 
`setInterval(electronLog.transports.file.resolvePath = () => "Folder/" + `\\main_${moment().format(this.LOG_FILE_FORMAT)}.log`, this.LOG_TIMER)`

**Comment by megahertz** [comment]
Looks like you've configured logger in the main process but logs from a renderer. It should be configured in both process. Anyway, maybe it's better to update to v5 beta, since it uses different configuration approach.

**Comment by monica-muthukumaran** [comment]
![image](https://user-images.githubusercontent.com/98094574/216319966-ffc7519e-cf94-4c65-989f-b853a074674c.png)
Logging happens from main process itself.

**Comment by megahertz** [comment]
You shouldn't wrap resolvePath setter to setTimeout
