### ISSUE TITLE
`undefined` is logged as `null`

### ISSUE THREAD

**Issue by stefansundin** [megahertz/electron-log#347]
Hello,

I tried to search and see if this is intended/documented, but I couldn't find any issue that mentioned it.

When I log `undefined`, it comes out as `null` like this:

```javascript
const log = require('electron-log');

console.log(undefined);
console.log = log.log;
console.log(undefined);
```

Output in my terminal:

> undefined
> 17:08:28.211 › null

This happens in both 4.4.8 and 5.0.0-beta.16.

Any explanation for this or is it a bug? It threw me for a real loop trying to debug something. 😵‍💫

I made this electron fiddle if you want to test it easily: https://gist.github.com/stefansundin/18ab5af281e820ce15927e126df8712d

Thanks!

**Comment by megahertz** [comment]
It's converted to null when JSON stringified. It would be nice to fix that, but it's a low-priority task currently.

**Comment by megahertz** [comment]
Now, undefined values are processed properly
