### ISSUE TITLE
Error object output empty [renderer console transport]

### ISSUE THREAD

**Issue by karldd** [megahertz/electron-log#35]
I'm using the new renderer console transport and finding that the error information sent to `log.error()` gets stripped out.  For example:

```javascript
log.error(new Error('This is an error Object'));
log.error('This is an error');
log.error('This is an error message', new Error('This is an error Object'));
```

Gives the following output: 
```
{ data: [ {} ], date: 2017-04-27T00:34:01.286Z, level: 'error' }
{ data: [ 'This is an error' ], date: 2017-04-27T00:34:01.287Z, level: 'error' }
{ data: [ 'This is an error message', {} ], date: 2017-04-27T00:34:01.287Z,level: 'error' }
```

When I directly pass `msg` to `console.log()` like so:
```javascript
log.transports.rendererConsole.format = (msg) => {
  console.log(msg);
};
```

As you can see the `Error` object turns into an empty object `{}`. Any ideas what is going on here?
Ideally `data` would contain the original `Error` object so the error message and stack trace can be displayed.

I'm using v2.2.2.

**Comment by megahertz** [comment]
I think Error isn't converted correctly due to passing through IPC. I'll try to fix it on the next week.
