### ISSUE TITLE
TypeError: path.join is not a function

### ISSUE THREAD

**Issue by caidongwei** [megahertz/electron-log#356]
hello, this is a problem in my project
TypeError: path.join is not a function
"electron-log": "^5.0.0-beta.21"

I also can't find logs in C:\Users\%USERPROFILE%\AppData\Roaming\{app name}\logs\main.log

**Comment by megahertz** [comment]
Could you provide more details? It would be nice to make a tiny sample project which reproduces the issue.

**Comment by caidongwei** [comment]
![image](https://user-images.githubusercontent.com/42203922/230303766-3b5eed47-e2eb-4f79-957e-7073acda1ea5.png)

this is my log.ts

import log from 'electron-log'
import { app } from 'electron'
log.transports.file.maxSize = 50 * 1024 * 1024

log.transports.file.format = `[{ y }-{ m }-{ d } { h }:{ i }:{ s }.{ ms }] [{ level }]{ scope } { test } `

const date = new Date()

const filePath =
  date.getFullYear() + '-' + date.getMonth() + 1 + '-' + date.getDate()

log.transports.file.resolvePath = () =>
  app.getPath('userData') + '\\logs\\' + filePath + '.log'

export default {
  info(params: any) {
    log.info(params)
  },
  warn(params: any) {
    log.warn(params)
  },
  error(params: any) {
    log.error(params)
  },
  debug(params: any) {
    log.debug(params)
  }
}

and then i import the logger in my page
when i run my project, it make the 'Uncaught TypeError: path.join is not a function'

**Comment by megahertz** [comment]
That code shouldn't be executed on a renderer side. Try to import 'electron-log/renderer' instead.

**Comment by caidongwei** [comment]
![020230406-172511](https://user-images.githubusercontent.com/42203922/230334555-b005c808-0b3d-40fd-aac0-d04d6d675fb9.jpg)
that means i should install  'electron-log/renderer'?
like this?

can't find electron-log/renderer

**Comment by caidongwei** [comment]
i try to import 'electron/renderer' instead  but also 'error: path.join is not a funtion'

import { app } from 'electron'
import log from 'electron-log/renderer'
log.transports.file.maxSize = 50 * 1024 * 1024

log.transports.file.format = `[{ y }-{ m }-{ d } { h }:{ i }:{ s }.{ ms }] [{ level }]{ scope } { test } `

const date = new Date()

const filePath =
  date.getFullYear() + '-' + date.getMonth() + 1 + '-' + date.getDate()

log.transports.file.resolvePathFn = () =>
  app.getAppPath('userData') + '\\logs\\' + filePath + '.log'

export default {
  info(params: any) {
    log.info(params)
  },
  warn(params: any) {
    log.warn(params)
  },
  error(params: any) {
    log.error(params)
  },
  debug(params: any) {
    log.debug(params)
  }
}

**Comment by caidongwei** [comment]
i use vite to create my project.  or it makes error because vite?

**Comment by megahertz** [comment]
Try 5.0.0-beta.22

**Comment by caidongwei** [comment]
current version is 5.0.0-beta.22, but also the error

**Comment by megahertz** [comment]
I can't help you anymore without a test project which reproduces that issue.

I have e2e test with vite and there's no such an error. You can check [its config](https://github.com/megahertz/electron-log/blob/master/e2e/vite-isolation-context-sandbox/vite.config.ts).

**Comment by caidongwei** [comment]
thanks，i find the problem when i check my config
i can find the log on the terminal  but can't find logs in C:\Users%USERPROFILE%\AppData\Roaming{app name}\logs\main.log

**Comment by caidongwei** [comment]
![image](https://user-images.githubusercontent.com/42203922/230578340-9ec6f438-6f33-4d75-a109-2fb08bc72792.png)
this is the prints, i can't find log.transport.file  object.
![image](https://user-images.githubusercontent.com/42203922/230578674-62807490-5715-4b16-bffc-b89f14bb0b46.png)

**Comment by megahertz** [comment]
You need to configure file transport in the main process only

**Comment by caidongwei** [comment]
if i want to use in renderer process, how to use

**Comment by megahertz** [comment]
Check the README. renderer logger is depend on the main logger and its config
