### ISSUE TITLE
rendererConsole messages appear in console erroneusly

### ISSUE THREAD

**Issue by djpereira** [megahertz/electron-log#36]
If you set the rendererConsole.level to a more verbose level than the console.level, all the messages from the rendererConsole leak into the console.

Example:
```
log.transports.console.level = 'verbose';
log.transports.rendererConsole.level = 'debug';
```

**Comment by megahertz** [comment]
I can't reproduce this problem. Maybe you set transports level after some messages have been sent?

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
