### ISSUE TITLE
official release v5

### ISSUE THREAD

**Issue by arunbansal-cpi** [megahertz/electron-log#360]
when can we expect v5 official release so tha we can do:
npm update electron-log

**Comment by jamesmontalvo3** [comment]
Any update on this?

**Comment by megahertz** [comment]
@jamesmontalvo3 If there are no new bugs found, I'm going to to publish it in the beginning of September.

**Comment by jamesmontalvo3** [comment]
Thanks!

**Comment by megahertz** [comment]
There were a few new issues found. I'm going to wait 10 more days and publish when no new reports.

**Comment by Stoyvo** [comment]
@megahertz any update?

**Comment by megahertz** [comment]
@Stoyvo There's one potential [blocker](https://github.com/megahertz/electron-log/issues/369). I will ignore that if there is no response by the next Wednesday.

**Comment by megahertz** [comment]
done
