### ISSUE TITLE
no logs from renderer process

### ISSUE THREAD

**Issue by tripower** [megahertz/electron-log#361]
using
v5.0.0-beta.23

in electron-quick-start project
I have inserted in main.js
const log = require('electron-log');
log.initialize({ spyRendererConsole: true});

and hoped that so in a log file the
console.log from renderer would be written
like console in Dev Tools
but nothing happen

bug or wrong code from me?

https://github.com/megahertz/electron-log/discussions/333#discussioncomment-5905074

**Comment by megahertz** [comment]
So, logs from the main process are written to file, but nothing from a renderer process?

Could you try this code in a renderer?

```js
setInterval(() => console.warn('log from renderer'), 300);
```

**Comment by tripower** [comment]
seams that it works, also without your setInterval
don't know why yesterday I saw no logs 

thx
