### ISSUE TITLE
getFile on FileTransport throws an error

### ISSUE THREAD

**Issue by louisparks-sta** [megahertz/electron-log#364]
I was trying to find out the full path to where the logs are stored, this used to work.
const file = (someLog.transports.file as electronLog.FileTransport).getFile();

but with 5.0.0-beta.24 results in....
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

**Comment by megahertz** [comment]
Thank you for the report, just reproduced it. I'll try to publish a fix on this week.
