### ISSUE TITLE
Empty log dir at default location for Electron with ESM

### ISSUE THREAD

**Issue by raphaelmenges** [megahertz/electron-log#368]
Hello 👋

I am using Electron in an ESM environment (which is soon to be available [without workaround](https://github.com/electron/electron/issues/21457)) together with `electron-log`. I need to change the location of the log file. However, I cannot prohibit `electron-log` from creating an empty directory with the `name` from my `package.json`. I guess it has something to do with how `import` works differently from `require`, because a similar issue [had been resolved](https://github.com/megahertz/electron-log/issues/230) for the latter. I have created a minimal reproduction of the bug here: <https://github.com/raphaelmenges/electron-log-empty-dir-bug>.

This is how the `Logs` directory looks on my Mac after execution:
<img width="981" alt="Screenshot 2023-09-25 at 09 33 11" src="https://github.com/megahertz/electron-log/assets/4311739/b6c4c5ca-04a1-40a8-9be8-fe3348a02de3">

Here is where I create the app:
<https://github.com/raphaelmenges/electron-log-empty-dir-bug/blob/main/packages/main/src/app.ts>

Here is where I setup the log:
<https://github.com/raphaelmenges/electron-log-empty-dir-bug/blob/main/packages/main/src/log.ts>

Here is where I combine both:
<https://github.com/raphaelmenges/electron-log-empty-dir-bug/blob/main/packages/main/src/index.ts>

It does not hurt the UX but feels weird to have an empty directory created with no use!

**Comment by megahertz** [comment]
Thank you for the sample. That dir is created automatically when `app.getPath('logs')` is called. Now it's called lazily to prevent that.

**Comment by raphaelmenges** [comment]
Thank you very much @megahertz for the quick fix and release of [5.0.0-rc.1](https://www.npmjs.com/package/electron-log/v/5.0.0-rc.1). Can confirm it fixes the issue for me as well!
