### ISSUE TITLE
The "initialize" method encountered an error in main process！

### ISSUE THREAD

**Issue by WangJM001** [megahertz/electron-log#369]
### Error Info
Error occurred in handler for '__ELECTRON_LOG__': Error: No handler registered for '__ELECTRON_LOG__'

### Reason
I checked the code and found that it's caused by 'process.type' being 'undefined' in the development environment.
```js
function getIpc() {
  if (process.type === 'browser' && electron?.ipcMain) {
    return electron.ipcMain;
  }

  if (process.type === 'renderer' && electron?.ipcRenderer) {
    return electron.ipcRenderer;
  }

  return null;
}
```

Can it be adjusted?

```js
function getIpc() {
  if (process.type === 'renderer' && electron?.ipcRenderer) {
    return electron.ipcRenderer;
  }

  return electron.ipcMain;
}
```

**Comment by megahertz** [comment]
Thanks @WangJM001. Does it solve the issue or that's just an assumption? Could you provide more information about your bundler and the related environment?

**Comment by johannesjo** [comment]
I have a similar error with electron 28.0.0. When using the initialize function in the main process I get the following error:
```
Cannot read properties of undefined (reading 'initializeFn')
    at initialize (/home/johannes/www/super-productivity/node_modules/electron-log/src/core/Logger.js:120:10)
```

**Comment by megahertz** [comment]
This part was rewritten entirely in v5.1.0, so I think it should be fixed.
