### ISSUE TITLE
Always output logs with time zone

### ISSUE THREAD

**Issue by slhck** [megahertz/electron-log#370]
I would suggest to change the default log format to always output timestamps with time zone information, i.e.

```
 '[{y}-{m}-{d} {h}:{i}:{s}.{ms}{z}] [{level}]{scope} {text}';
```

Otherwise, logs will always carry ambiguous timestamps when created from systems with different time zones.

Alternatively, it would be good to allow logging in UTC times only.

**Comment by megahertz** [comment]
I agree, but I'm not sure whether it makes sense to do such a change, since it could be unexpected for some users. It makes sense to thing about it in the next major release.

As for ISO, it's currently supported with `{iso}`

**Comment by slhck** [comment]
Oh, that'd be a good solution. Where can I find a list of template variables?

**Comment by slhck** [comment]
Oh, sorry, I completely missed that part of the docs. Thanks!

**Comment by slhck** [comment]
I see you marked this as complete, but the default format did not change, correct?

(I am fine with specifying ISO manually of course!)

**Comment by megahertz** [comment]
Yes. I decided to keep it as is since it can be an unexpected behavior for some users who already use the library.
