### ISSUE TITLE
warning electron-log@5.0.0: The engine "electron" appears to be invalid.

### ISSUE THREAD

**Issue by kylekirkby** [megahertz/electron-log#372]
We're getting this warning when running `yarn install`. 

```
warning electron-log@5.0.0: The engine "electron" appears to be invalid.
```

However, we've got the latest `electron` version as a dependency in our `package.json` file. 

I looked at the package.json for electron-log and can see the engine version for electron is set to `>= 13`. So, by my understanding, this warning should not be displayed.

Thoughts?

**Comment by megahertz** [comment]
Thanks. Previous versions of npm haven't considered it as an error. Currently, only `node` and `npm` keys are allowed for the `engine` section.
