### ISSUE TITLE
Filter Multiple Log Levels

### ISSUE THREAD

**Issue by monica-muthukumaran** [megahertz/electron-log#373]
Hi, 
I see that 
```
logger.transports.file.level = "error";
logger.transports.console.level = "error";
```
will filter out that specific level. 
But is there a way which i filter out few levels only.

For example "error" and "verbose" only

**Comment by megahertz** [comment]
When you set the "warn" level it also includes any upper levels ("error" and "warn" in that case). If you would like to include different levels such as "error" and "verbose", you can write a custom hook for that.

**Comment by monica-muthukumaran** [comment]
Thank you

**Comment by monica-muthukumaran** [comment]
Also, Can you please help me on understanding the hierarchy of the log levels.

**Comment by megahertz** [comment]
There is nothing special. There are five levels: error, warn, info, verbose, debug, silly. Each next level has a lower priority. So, when a log level is set for a transport it means to process logs which level is >= the specified level
