### ISSUE TITLE
Electronforge + Webpack + preload.js script rise an error

### ISSUE THREAD

**Issue by xavier7179** [megahertz/electron-log#383]
Due to some issues with the logs working in the renderer with an electronforge-based app, I moved from version 4 to 5. Unfortunately, with the current setup, I cannot start the application because I always get the following error:

```
Error: electron-log isn't initialized in the main process. Please call log.initialize() before. Error invoking remote method '__ELECTRON_LOG__': No handler registered for '__ELECTRON_LOG__'
```
I though the problem was that the app was starting with a preload.js script to export some IPC to the renderer, but I checked all available documentation but needed help finding a working solution.

**Comment by megahertz** [comment]
It should work fine with default settings; the only known case when it doesn't work is when using a custom session. Could you create a sample project that reproduces the issue?

**Comment by megahertz** [comment]
Try to use the latest version. If that isn't helpful, please provide an example that reproduces the issue, and I'll reopen the issue.
