### ISSUE TITLE
Error with electron 28.0.0. When using the initialize function in the main process I get the following error:

### ISSUE THREAD

**Issue by johannesjo** [megahertz/electron-log#384]
I get an error with electron 28.0.0, when using the initialize function in the main process:
```
Cannot read properties of undefined (reading 'initializeFn')
    at initialize (/home/johannes/www/super-productivity/node_modules/electron-log/src/core/Logger.js:120:10)
```

_Originally posted by @johannesjo in https://github.com/megahertz/electron-log/issues/369#issuecomment-1859164807_

**Comment by megahertz** [comment]
I think you import this lib as 'electron-log' instead of 'electron-log/main'

**Comment by johannesjo** [comment]
> I think you import this lib as 'electron-log' instead of 'electron-log/main'

Just tried using
`import { initialize } from 'electron-log';`
There is no difference in the outcome unfortunately.

**Comment by megahertz** [comment]
Named import isn't supported since `initialize` is an instance method.

**Comment by johannesjo** [comment]
Thank you for the explanation! That solved the problem!
