### ISSUE TITLE
Background Process

### ISSUE THREAD

**Issue by akshaygarg834** [megahertz/electron-log#39]
I have made a background process using hidden window in electron. In that process console.log() or electron-log dosn't print anywhere. What should I do. Also is there a way to redirect every output of console.log to electron-log?

**Comment by megahertz** [comment]
I haven't tested multiple browser processes. Sorry, I'm very busy on this week, but I'll try on the next.

As for console.log, I'm not going to include redirection to the library, but it's pretty easy to override console.log function.

**Comment by megahertz** [comment]
I see no problems with multiple browser windows. There is the test project which writes logs from two renderer process https://github.com/megahertz/electron-log/tree/master/test-projects/electron-log-test-simple

**Comment by megahertz** [comment]
Make sure that:
- You have the latest library
- Log level is set correctly

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
