### ISSUE TITLE
Main process IPC transport is not initialised

### ISSUE THREAD

**Issue by BTMorton** [megahertz/electron-log#395]
I've just updated to electron-log v5 and noticed that the main process logs aren't being forwarded to the renderer. I tried setting the log level as per the docs using:
```typescript
log.transports.ipc.level  = 'silly';
```
but I get an undefined error:
```
TypeError: Cannot set properties of undefined (setting 'level')
```

I noticed that the IPC factory is [not set when creating the default logger](https://github.com/megahertz/electron-log/blob/4e33575098738ddb4336f976c844d0988034b83a/src/main/index.js#L18-L22), so I tried manually instantiating the IPC transport explicitly and setting the level:
```typescript
import * as ipcTransport from 'electron-log/src/main/transports/ipc';
...
log.transports.ipc = ipcTransport(log, log.dependencies);
log.transports.ipc.level  = 'silly';
```
which does forward the main process logs correctly, but also results in the renderer logs being printed twice. as the renderer logs are re-forwarded back to the renderer as a main process log.

I guess I have two questions:
1. Is the IPC transport main -> renderer still supported or has there been a decision to deprecate it?
2. How does the IPC forwarding of server logs work and is there something that can be done on my side to resolve the duplicate log issue?

**Comment by megahertz** [comment]
That will be fixed in v5.1, which I'm going to release soon.
