### ISSUE TITLE
How to check when log.error() is called

### ISSUE THREAD

**Issue by 3s-ThangLD** [megahertz/electron-log#396]
Hi!

I was trying to handle log process to file. For case log file have been block permission (write, modify,..), function log.error() will not update this file contents and not emit error.

How i can check this process? Or check when any log.error() function have been call in application?. Thanks!

![image](https://github.com/megahertz/electron-log/assets/124142887/b63f5a11-a603-4692-a51a-287e549733a2)

**Comment by megahertz** [comment]
Under the hood, it calls the console transport directly. The only way to handle such a case outside is to overwrite log.transports.console.writeFn function.

**Comment by 3s-ThangLD** [comment]
> Under the hood, it calls the console transport directly. The only way to handle such a case outside is to overwrite log.transports.console.writeFn function.

It is useful for me. Thank you for your reply!
