### ISSUE TITLE
Color and text disappear when using custom console transport format.

### ISSUE THREAD

**Issue by NotLazy** [megahertz/electron-log#397]
When I use the default console transport format, I get color and my logged messages:
<img width="411" alt="image" src="https://github.com/megahertz/electron-log/assets/12667538/7c1767fb-2f5a-43de-a827-0336ab956a9b">

But when I use a custom console transport format:
<img width="340" alt="image" src="https://github.com/megahertz/electron-log/assets/12667538/ed74bd9c-6aa0-45de-b539-cd51f1bdc3b6">

Here's my custom format: `%c{h}:{i}:{s}.{ms}%c {sender} › {text}`
sender is defined using `log.variables.sender = currentContext;` before calling log.silly() or log.info() (the two levels shown in screenshots)

**Comment by megahertz** [comment]
```js
  log.hooks.push((msg, _, transportName) => {
    if (transportName === 'console') {
      msg.data.unshift('color: blue', 'color: unset');
    }

    return msg;
  });
```

**Comment by NotLazy** [comment]
> ```js
>   log.hooks.push((msg, _, transportName) => {
>     if (transportName === 'console') {
>       msg.data.unshift('color: blue', 'color: unset');
>     }
> 
>     return msg;
>   });
> ```

This works for console but causes file and remote handlers to have this text in them, even though specifically locking it with transportName

in the log file:
```
[2024-02-05 22:09:11.408] [info] (main) color: cyan color: unset App is ready and has been initialized
[2024-02-05 22:09:11.998] [info] (app) color: cyan color: unset Loading 15
[2024-02-05 22:09:12.145] [info] (app) color: cyan color: unset Loading 17
[2024-02-05 22:09:12.961] [info] (app) color: cyan color: unset loaded
[2024-02-05 22:09:12.967] [info] (app) color: cyan color: unset loaded
```

**Comment by megahertz** [comment]
Ok, try clonning msg object instead
```js
log.hooks.push((msg, _, transportName) => {
  if (transportName === 'console') {
    return {
      ...msg,
      data: ['color: blue', 'color: unset', ...msg.data],
    }
  }

  return msg;
});
```

**Comment by NotLazy** [comment]
> Ok, try clonning msg object instead

This worked. I had tried only cloning msg or only cloning msg.data but, cloning both was the answer here. Thanks!
