### ISSUE TITLE
Log renderer console.log to file and dev console

### ISSUE THREAD

**Issue by alexcroox** [megahertz/electron-log#40]
I am looking to this library as the developer tools in a packed/production app don't show console logs (when they do during development).

I would like to log console.log from the renderer to both dev console and a file.

Is there a way to override console.log to achieve this? Also should this configuration only be done inside the main script, since no configuration can take place in the renderer if I read correctly?

**Comment by megahertz** [comment]
```js
console.log = log.info
```
both in renderer and browser processes

**Comment by alexcroox** [comment]
Thank you!

**Comment by alexcroox** [comment]
This works in dev but as soon as a build my app with electron builder only logs from main, not renderer, appear in the log files.

**Comment by megahertz** [comment]
I'll check in a few days. Maybe there is a problem with the latest electron

**Comment by alexcroox** [comment]
@megahertz turned out this was my fault: https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js#L156

**Comment by disarticulate** [comment]
Nice find, this was confusing me also. For the lazy using simulatedGREG
```
    new BabiliWebpackPlugin({
      removeConsole: false,
      removeDebugger: false
    }),
```
