### ISSUE TITLE
when i use function addLevel, it indeed work but TypyScript reports type error

### ISSUE THREAD

**Issue by FlyBooks** [megahertz/electron-log#406]
Hello,  
log.initialize();
  log.addLevel("critical", 0);
  const modbusLog = log.scope("modbus");
  modbusLog.info('Log from the main process');
  modbusLog.error('Oops, something ');
  modbusLog.critical("urgent!");
![image](https://github.com/megahertz/electron-log/assets/36462422/1fc338e6-3115-4bc7-a1f6-45dc01924938)

Thanks a lot in advance!

**Comment by megahertz** [comment]
https://github.com/megahertz/electron-log/blob/master/docs/extend.md#log-levels
