### ISSUE TITLE
Error: Attempted to register a second handler for '__ELECTRON_LOG__'

### ISSUE THREAD

**Issue by FlyBooks** [megahertz/electron-log#408]
Hello~,
Could you please give me some hints ?
logging-util/index.ts:
```
import log from 'electron-log/main';
import "./electron-log.d.ts";

  log.initialize({ preload: true });
  log.addLevel("critical");
  log.addLevel("warning", 1);
  log.addLevel("information", 3);
  
console.log(log.levels,'level');
const modbusLog = log.scope("modbus");
  

export { modbusLog };
```

```
import { modbusLog } from "../logging-util/index";
ipcMain.handle("modbusLoggingRecord", (_, level, logging) => {
    modbusLog[level](logging);
});
```

Those code will be executed in file preload.js.

But it always runs failed with error: **Error: Attempted to register a second handler for '__ELECTRON_LOG__'**
    at IpcMainImpl.handle (node:electron/js2c/browser_init:2:105646)
    at ElectronExternalApi.onIpcInvoke (C:\projects\Hummingbird\dist-electron\main\index.js:523:94)
    at Object.<anonymous> (C:\projects\Hummingbird\dist-electron\main\index.js:2060:13)

Thanks a lot in advance!
Eva

**Comment by FlyBooks** [comment]
Really appreciated for your hint！
So i just use the __ELECTRON_LOG__ in the ipcRenderer
```
 electronLoggingRecord: (logContent: string) => { 
      ipcRenderer.send('__ELECTRON_LOG__', {
        data: [logContent],
        level: 'information',
        scope: "user"
      });
    }
```

main.ts:

```
app.whenReady().then(() => {
  createWindow();

  // electron-log
  log.initialize();
  log.addLevel("critical");
  log.addLevel("warning", 1);
  log.addLevel("information", 3);
});

```
It works and is that a recommended way in electron-log?

**Comment by megahertz** [comment]
Yes, that's fine. The only hint is to call the code directly on the main without waiting for the ready event.
