### ISSUE TITLE
Seems to be not working on Windows 

### ISSUE THREAD

**Issue by s-KaiNet** [megahertz/electron-log#41]
Hi Alex, 

I'm trying to print a message in a main process. I've started with a very (very) basic sample - cloned `https://github.com/electron/electron-quick-start`, put console.log and run `electron .` - nothing showing.  
Then I installed your module, added `log.warn` and run `electron .` - same result, no console output (besides file output is present).   
Am I doing something completely wrong, or may it's not possible at all to show console logs from `main.js` on Windows?   
My environment:   
```bash
electron 1.6.11
node 6.10.1
windows server 2012R2 (can be considered as Windows 10)
```

**Comment by megahertz** [comment]
The console transport of electron-log uses console[level]() for logging internally. So if console.log doesn't print to console, electron-log doesn't print too. Sorry, I don't know what is the reason.

**Comment by s-KaiNet** [comment]
Ok, np, I thought I missed something simple.

**Comment by megahertz** [comment]
Is it works? `process.stdout.write('test');`

**Comment by s-KaiNet** [comment]
nope

**Comment by megahertz** [comment]
do you run the code from the main process or from renderer?

**Comment by s-KaiNet** [comment]
I'm running from the main process

**Comment by megahertz** [comment]
Did you solve the problem?
I can also recommend to try:
- run electron with --enable-logging flag
- try newer electron version
If nothing works than try to check if a simple node (not electron) script can write to console correctly

**Comment by s-KaiNet** [comment]
Yes, I was able to make it work by running `node_modules\electron\dist\electron.exe full/path/to/main.js`  
As far as I understand when running just `electron main.js` it spawns the process thus making communication between input\output impossible (at least on windows).   
`electron main.js --enable-logging` also doesn't produce any output. Only approach with full path to electron executable works for me.
