### ISSUE TITLE
log.transport.file not accessible in Angular app

### ISSUE THREAD

**Issue by holo05** [megahertz/electron-log#416]
Hi,

in my Electron-Angular app i cant access to "log.transports.file".
But 'log.info" writes correctly to console and the "main.log" file

Angular 17.3.6
Electron 30.01
Node 20.12

Thanky ou for any hints!

![image](https://github.com/megahertz/electron-log/assets/41048494/e27132fa-0f21-4aac-b65e-bc920b48a51c)
![image](https://github.com/megahertz/electron-log/assets/41048494/38a48706-d1c6-4b8a-8517-414a8168fba2)

**Comment by megahertz** [comment]
You need to do that in the main process, not in a renderer.
