### ISSUE TITLE
"electron-log: logger isn't initialized in the main process" error in browser console

### ISSUE THREAD

**Issue by vibhorgupta-gh** [megahertz/electron-log#428]
I'm running my electron app (v31.1.0) and electron-log (v5.1.2) in it, with the following config:

`main.ts`
```
log.initialize()

log.transports.file.format = '[{h}:{i}:{s}] - [{d}-{m}-{y}] - [{processType}] -> {text}'
log.transports.console.format = '[{h}:{i}:{s}] - [{d}-{m}-{y}] - [{processType}] -> {text}'

const mainLogger = log.scope('main')
console.log = mainLogger.log
console.debug = mainLogger.debug
console.info = mainLogger.info
console.warn = mainLogger.warn
console.error = mainLogger.error

log.transports.file.resolvePathFn = (vars, message) => {
	if (message.scope === 'main') return path.resolve(vars.libraryDefaultDir, 'main.log')
	else return path.resolve(vars.libraryDefaultDir, 'render.log')
}
```

`render.ts`
```
import log from 'electron-log/renderer';

const renderLogger = log.scope('render')

console.log = renderLogger.log
console.debug = renderLogger.debug
console.warn = renderLogger.warn
console.error = renderLogger.error
```

this writes my main thread logs to my terminal, also writes my render thread logs to browser console, but it doesn't:
1. Write render logs to terminal
2. Write render logs to `render.log` file

<img width="683" alt="Screenshot 2024-07-11 at 4 52 19 PM" src="https://github.com/megahertz/electron-log/assets/29275810/3d1e770f-5ac2-4035-9bf7-824fcb699e43">

What am i doing wrong?

**Comment by megahertz** [comment]
These fragments look fine. Could you share a whole project that reproduces the issue? It may be related to a bundler.

**Comment by megahertz** [comment]
This library tries to support different bundler environments, but some environments still make it impossible to initialize the logger correctly in a renderer process. If you use any preload script, you may try to `import 'electron-log/preload'` instead of running `log.initialize()`

**Comment by vibhorgupta-gh** [comment]
1. A simple `import 'electron-log/preload'` will suffice?
2. This import is to placed in `main.ts` or `preload.ts`?

**Comment by megahertz** [comment]
Yes, you can add this import statement to preload.js. It's an alternative way to do the same as the `log.initialize()` statement does.

**Comment by vibhorgupta-gh** [comment]
This seemed to work, thanks a lot for the help! Will reach out to you if I face any further issues.
