### ISSUE TITLE
[Node] File transport - variables not interpolated?

### ISSUE THREAD

**Issue by bhj** [megahertz/electron-log#429]
Hi and thanks again for all your work! I just upgraded a Node project from electron-log 4.4.8 to 5.1.5, and modified the import to `electron-log/node`. The console transport works normally, e.g.

```
23:22:13.153 (server)        › Brandon (gJAbndvThzOWt6sGAAAB) connected from ::ffff:10.0.1.4
```

However the file transport seems to not be interpolating the variables:

```
[2024-07-14 23:22:13.153] [verbose] (server)        %s (%s) connected from %s Brandon gJAbndvThzOWt6sGAAAB ::ffff:10.0.1.4
```

This is [pretty much with the default settings](https://github.com/bhj/KaraokeEternal/blob/v2-logger/server/lib/Log.js). Am I missing anything? Thanks.

**Comment by megahertz** [comment]
Thanks for the report. I'll try to fix that in a few days.
