### ISSUE TITLE
Chrome dev tools renderer console transport is not working

### ISSUE THREAD

**Issue by qual** [megahertz/electron-log#43]
Node js and file transport is working well. but some how renderrer console logs are not getting visible Does the console log get visible by default or do we have to perform some configuration. An simple example of electron would be helpful.

const electron = require('electron')
// Module to control application life.
const app = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

const path = require('path')
const url = require('url')
const fs = require('fs');

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow() {
  // Create the browser window.
  mainWindow = new BrowserWindow({ width: 800, height: 600 })
  
  // and load the index.html of the app.
  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
  // Open the DevTools.
  mainWindow.webContents.openDevTools()
  
  **var log = require('electron-log');
  log.info('in create window');
  log.transports.rendererConsole.level = 'info';**
 

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

**Comment by megahertz** [comment]
You call log.info when BrowserWindow is still creating. If you would like to see this log record in dev tools you should wrap this code into setTimeout with timeout 300-500ms.

**Comment by qual** [comment]
I have tried that as well. Its not working. I have tired putting that post window creation as well where its giving me error. 

Could you please check if there is issue in my code. Here is the link to my code: https://gist.github.com/qual/61907d22db5956014055890b88e473c4

**Comment by megahertz** [comment]
You shouldn't configure logger inside timeout. Try this:
```js
let i = 0;
setInterval(() => {
  log.info(`Logging from the main process #{i}`);
}, 300);
```

**Comment by qual** [comment]
Just tried. Its still not working. Node console logs are working properly. But not a single log has appeared in in chrome renderer console. 
JFYI, I am using electron-prebuilt-compile and react js. Can this cause any issue to renderer logs ?

**Comment by megahertz** [comment]
Do you require electron-log in a renderer process?

2017-07-29 17:15 GMT+05:00 Omkar K <notifications@github.com>:

**Comment by qual** [comment]
Not sure if I understand what you are saying. If your asking about whether I have included require statement in my renderer.js files, then I am actually exposing the global log object to all the renderer processes.

**Comment by megahertz** [comment]
Pls show me a part of your renderer code

**Comment by qual** [comment]
Sure. Here is my renderer code. 
1) ReactHome.js: https://gist.github.com/qual/698b34fb065c0ce531ed46f383f2a442
2) engine.js: https://gist.github.com/qual/35c42cc4f1bc13085cf037a902379fde

1) Just to summarize I am declaring and exporting log module in main process as follows:
let log = require('electron-log');
console.log('hello from main');
global.logger = log; //export

2) I am importing the same log module in renderer process as follows
let log = require('electron').remote.getGlobal('logger');
console.log('hello from renderer');

Any issue in above code ?

**Comment by megahertz** [comment]
That's why it doesn't work. You need to import electron-log directly, not through remote

**Comment by qual** [comment]
Oh. My bad. I incorrectly assumed that I will have to share the same log instance across renderer processes using remote. But looks like it is taking the same log instance across main and renderer.

Now I have fixed the code. Now its working as a charm !

This library is extremely useful ! Thanks a lot @megahertz for your prompt help !
