### ISSUE TITLE
Unable to restrict the log file permissions

### ISSUE THREAD

**Issue by benji** [megahertz/electron-log#430]
Hello!

I am trying to change the file permissions from: `-rw-r--r--` to `-rw-r-----`, so I'm using `writeOptions` like so:

`log.transports.file.writeOptions = { flag: "a", mode: 0o640 };`

However the file permissions remain unchanged. I am suspecting that I'm not initializing the logger or transport properly.

I've created a Electron Fiddle Gist here: https://gist.github.com/benji/c8d74654cef2876a33414ba467651d01.

Versions:
- electron-log: 5.1.6
- electron: 32.0.0

Thanks for the help!

**Comment by megahertz** [comment]
Thanks for the report and the gist
