### ISSUE TITLE
electron-vite从1.0.29升级到2.3.0之后，启动electron-vite dev后会出现无法找到和导入electron-log

### ISSUE THREAD

**Issue by 24Hoursss** [megahertz/electron-log#435]
App threw an error during load
Error: Cannot find module 'electron-log/src/main/transforms/object'
Require stack:
- C:\Users\PC\Desktop\project\out\main\index.js
- C:\Users\PC\Desktop\project\node_modules\electron\dist\resources\default_app.asar\main.js
- C:\Users\PC\Desktop\project\out\main\index.js
- C:\Users\PC\Desktop\project\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Module.<anonymous> (C:\Users\PC\Desktop\project\out\main\index.js:14:16)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)

报错出现在：C:\Users\PC\Desktop\project\out\main\index.js:14:16即以下代码
const object = require("electron-log/src/main/transforms/object");

已经包的环境：
"dependencies": {
    "@codemirror/lang-python": "^6.1.5",
    "@electron-toolkit/preload": "^2.0.0",
    "@electron-toolkit/utils": "^2.0.0",
    "@electron/remote": "^2.1.2",
    "@vueuse/core": "^10.11.0",
    "better-sqlite3": "^9.6.0",
    "codemirror": "^6.0.1",
    "electron-log": "^5.1.7",
    "electron-store": "^8.2.0",
    "electron-updater": "^6.1.1",
    "element-plus": "^2.4.4",
    "html2canvas": "^1.4.1",
    "interactjs": "^1.10.26",
    "jstat": "^1.9.6",
    "lodash": "^4.17.21",
    "mathjs": "^12.4.1",
    "mitt": "^3.0.1",
    "ml-levenberg-marquardt": "^4.1.3",
    "mxgraph": "^4.2.2",
    "patch-package": "^8.0.0",
    "path-browserify": "^1.0.1",
    "pinia": "^2.1.7",
    "plotly.js-dist-min": "^2.32.0",
    "python-shell": "^5.0.0",
    "redis": "^4.6.14",
    "rxjs": "^7.8.1",
    "tsc": "^2.0.4",
    "vite-plugin-electron-renderer": "^0.14.5",
    "vue-codemirror": "^6.1.1",
    "vue-router": "^4.3.0",
    "vue3-eventbus": "^2.0.0",
    "vuedraggable": "^4.1.0"
  },
  "devDependencies": {
    "@electron-toolkit/eslint-config": "^1.0.1",
    "@electron-toolkit/eslint-config-ts": "^1.0.0",
    "@electron-toolkit/tsconfig": "^1.0.1",
    "@element-plus/icons-vue": "^2.3.1",
    "@iconify-json/bxs": "^1.1.10",
    "@iconify-json/carbon": "^1.1.27",
    "@iconify-json/cil": "^1.1.8",
    "@iconify-json/circum": "^1.1.10",
    "@iconify-json/clarity": "^1.1.12",
    "@iconify-json/codicon": "^1.1.43",
    "@iconify-json/eos-icons": "^1.1.10",
    "@iconify-json/ep": "^1.1.14",
    "@iconify-json/fluent": "^1.1.49",
    "@iconify-json/fluent-mdl2": "^1.1.6",
    "@iconify-json/fontisto": "^1.1.8",
    "@iconify-json/grommet-icons": "^1.1.10",
    "@iconify-json/icon-park-outline": "^1.1.15",
    "@iconify-json/iconamoon": "^1.1.4",
    "@iconify-json/iconoir": "^1.1.33",
    "@iconify-json/la": "^1.1.8",
    "@iconify-json/material-symbols": "^1.1.69",
    "@iconify-json/material-symbols-light": "^1.1.16",
    "@iconify-json/mdi": "^1.1.64",
    "@iconify-json/memory": "^1.1.9",
    "@iconify-json/octicon": "^1.1.52",
    "@iconify-json/ph": "^1.1.12",
    "@iconify-json/radix-icons": "^1.1.14",
    "@iconify-json/streamline": "^1.1.8",
    "@iconify-json/system-uicons": "^1.1.12",
    "@iconify-json/tdesign": "^1.1.3",
    "@rushstack/eslint-patch": "^1.3.3",
    "@types/better-sqlite3": "^7.6.9",
    "@types/node": "^18.17.5",
    "@unocss/preset-attributify": "^0.58.0",
    "@unocss/preset-uno": "^0.58.0",
    "@unocss/transformer-directives": "^0.58.0",
    "@vitejs/plugin-vue": "^4.3.1",
    "@vue/eslint-config-prettier": "^8.0.0",
    "@vue/eslint-config-typescript": "^11.0.3",
    "electron": "^25.6.0",
    "electron-builder": "^24.6.3",
    "electron-rebuild": "^3.2.9",
    "electron-vite": "^2.3.0",
    "eslint": "^8.47.0",
    "eslint-plugin-vue": "^9.17.0",
    "less": "^4.2.0",
    "prettier": "^3.0.2",
    "rimraf": "^5.0.7",
    "sass": "^1.69.5",
    "typescript": "^5.4.3",
    "unocss": "^0.58.0",
    "unplugin-auto-import": "^0.17.2",
    "unplugin-icons": "^0.18.1",
    "unplugin-vue-components": "^0.26.0",
    "vite": "^4.4.9",
    "vue": "^3.3.4",
    "vue-tsc": "^1.8.8",
    "wait-on": "^7.2.0"
  }

当我升级所有的electron相关包，也会出现类似错误，无法导入electron-log

**Comment by megahertz** [comment]
It looks like you have a few different versions of electron-log. Run `npm ls electron-log` to check that.
