### ISSUE TITLE
When electron is started with --inspect console transport does not output debug level

### ISSUE THREAD

**Issue by alexstrat** [megahertz/electron-log#44]
When app started with `--inspect`, due to https://github.com/electron/electron/issues/10260, `console.debug` is defined but does nothing. Therefore, the console transport does not output debug level.

**Comment by megahertz** [comment]
You could override console transport. See readme for the example.

**Comment by alexstrat** [comment]
I used this as temporary fix:
```js
if (console.debug) console.debug = console.log;
``

**Comment by magne4000** [comment]
Here is a more global solution to this kind of problem : 
```js
import format from 'electron-log/lib/format';

log.transports.console = Object.assign(msg => {
  console.log(format.format(msg, log.transports.console.format));
}, log.transports.console);
```

@megahertz  This snippet keeps `format` and `level` intact. You could use it in the README to replace https://github.com/megahertz/electron-log#override-transport.
