### ISSUE TITLE
Electron React app not getting same instance of the logger as the main process?

### ISSUE THREAD

**Issue by nikb747** [megahertz/electron-log#48]
In my main.js for electron i'm bringing in electron log with:
import log from 'electron-log';

I configure the transport formats in main.js.
I log a message from main.js and it appears in the log file and the console with the correct format.
When I log from my react application, it only shows up in the console with the default format.
Am I missing something in my config?

**Comment by megahertz** [comment]
I'll investigate it a bit later

**Comment by nikb747** [comment]
Yes, I had to make some changes to the way I build electron to support import statements.  Both the electron main.js and my app's index.js use "import log from 'electron-log'"

**Comment by megahertz** [comment]
Sorry, I didn't find time to deep into this problem, I can try to help you only after two weeks. While I'm not avaiable, you can check https://github.com/megahertz/electron-log/tree/master/test-projects/electron-log-test-webpack

**Comment by megahertz** [comment]
Try to import 'electron-log/renderer' instead of 'electron-log' in a renderer process

**Comment by 1-14x0r** [comment]
I had a similar issue with my electron react project. The renderer process was not picking up my configuration i set in my main process, and therefore not logging properly into my console or file. I solved this by using `remote.require('electron-log)` and not with an `import` statement like so:

```
const { ipcRenderer, remote } = window.require("electron");
const log = remote.require("electron-log");
```

**Comment by megahertz** [comment]
@1-14x0r Yes, sometimes this approach works, but it depends on the webpack config.

**Comment by spenoir** [comment]
@1-14x0r Your answer should be added to the documentation for webpack, thanks

**Comment by megahertz** [comment]
@spenoir It won't be actual in the next major version of electron-log

**Comment by clem91** [comment]
Same problem with the same environment adn none of the tips are working 😿 . When I try a `log.error() ` it works on devtools console but when I try a lower level like debug it doesn't work despite my previous configuration in the main process.
``` javascript
log.transports.file.level = false;
log.transports.console.level = 'error';
log.transports.rendererConsole.level = 'debug';
log.transports.rendererConsole.format = '{level} {text}';
```

**Comment by megahertz** [comment]
@clem91 Make sure debug messages are enabled in chrome dev tools. It's disabled (by filter) by default.

**Comment by clem91** [comment]
It works! With this last tips I think the issue is well documented. Thank you @megahertz for your quick answer

**Comment by megahertz** [comment]
@aguynamedben 

If nothing works for you, you could add electron-log to the externals section of webpack.

Sorry, but I can't answer your question about v3 exactly. I'm waiting for a period when I'll have much more free time. Maybe in the beginning of September, but I can't promise.

**Comment by megahertz** [comment]
Feel free to reopen if v3.0.0-beta2 doesn't solve your problem.

**Comment by jailsonpaca** [comment]
> I had a similar issue with my electron react project. The renderer process was not picking up my configuration i set in my main process, and therefore not logging properly into my console or file. I solved this by using `remote.require('electron-log)` and not with an `import` statement like so:
> 
> ```
> const { ipcRenderer, remote } = window.require("electron");
> const log = remote.require("electron-log");
> ```

Thanks you! God bless you

**Comment by SandhyaR1007** [comment]
I am using electron logger with electron-react app but whenever my app logs an information , app gets reloaded. I am not sure how to tackle this.

**Comment by megahertz** [comment]
@SandhyaR1007 That's not possible to detect the reason without extended information. Firstly, I would start from wrapping the problem code to try/catch block to check whether some exception thrown.
