### ISSUE TITLE
log.transports undefined?

### ISSUE THREAD

**Issue by bingqiao** [megahertz/electron-log#50]
Here attached is the screenshot of all the properties on log which is imported via:
`import * as log from 'electron-log';`

I also tried `var log = require('electron-log');` but that made no difference.

Any comments?

Many thanks

![image](https://user-images.githubusercontent.com/26798622/31133404-43241180-a857-11e7-8125-239c70ff2f1a.png)

**Comment by bingqiao** [comment]
OK I guess property transports is only available in main process?

**Comment by megahertz** [comment]
Yes, you're right
