### ISSUE TITLE
Docs : what are the possible streamConfig flags

### ISSUE THREAD

**Issue by 1-14x0r** [megahertz/electron-log#51]
I couldn't find any references in the source code... like an enum object or symbol map with some commments on the possible values. I assume these stem from the possible flags you can pass into a `fs`

digging around api documents i found this link
https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback

is it safe to assume you can pass any one of these into the streamConfig?

here is a brief overview

> Asynchronous file open. See open(2). flags can be:
> 
> 'r' - Open file for reading. An exception occurs if the file does not exist.
> 
> 'r+' - Open file for reading and writing. An exception occurs if the file does not exist.
> 
> 'rs+' - Open file for reading and writing in synchronous mode. Instructs the operating system to bypass the local file system cache.
> 
> This is primarily useful for opening files on NFS mounts as it allows skipping the potentially stale local cache. It has a very real impact on I/O performance so using this flag is not recommended unless it is needed.
> 
> Note that this doesn't turn fs.open() into a synchronous blocking call. If synchronous operation is desired fs.openSync() should be used.
> 
> 'w' - Open file for writing. The file is created (if it does not exist) or truncated (if it exists).
> 
> 'wx' - Like 'w' but fails if path exists.
> 
> 'w+' - Open file for reading and writing. The file is created (if it does not exist) or truncated (if it exists).
> 
> 'wx+' - Like 'w+' but fails if path exists.
> 
> 'a' - Open file for appending. The file is created if it does not exist.
> 
> 'ax' - Like 'a' but fails if path exists.
> 
> 'a+' - Open file for reading and appending. The file is created if it does not exist.
> 
> 'ax+' - Like 'a+' but fails if path exists.
> 
> mode sets the file mode (permission and sticky bits), but only if the file was created. It defaults to 0o666, readable and writable.
> 
> The callback gets two arguments (err, fd).
> 
> The exclusive flag 'x' (O_EXCL flag in open(2)) ensures that path is newly created. On POSIX systems, path is considered to exist even if it is a symlink to a non-existent file. The exclusive flag may or may not work with network file systems.
> 
> flags can also be a number as documented by open(2); commonly used constants are available from fs.constants. On Windows, flags are translated to their equivalent ones where applicable, e.g. O_WRONLY to FILE_GENERIC_WRITE, or O_EXCL|O_CREAT to CREATE_NEW, as accepted by CreateFileW.
> 
> On Linux, positional writes don't work when the file is opened in append mode. The kernel ignores the position argument and always appends the data to the end of the file.
> 
> Note: The behavior of fs.open() is platform-specific for some flags. As such, opening a directory on macOS and Linux with the 'a+' flag - see example below - will return an error. In contrast, on Windows and FreeBSD, a file descriptor will be returned.

Maybe creating a config object to store these values could be helpful? Thanx :)

**Comment by megahertz** [comment]
Thank you for the suggestion. I'm going to add links to node documentation and add the corresponding type definitions.

**Comment by 1-14x0r** [comment]
okay cool. thank you for your work on this project, i enjoy working with it. i found it a pleasure to configure and use. If only log4j was this nice and simple.
