### ISSUE TITLE
Unable to set level for transports

### ISSUE THREAD

**Issue by loopmode** [megahertz/electron-log#53]
Hi

using:
```
electron-log@^2.2.9:
  version "2.2.9"
  resolved "https://registry.yarnpkg.com/electron-log/-/electron-log-2.2.9.tgz#e0484cb1a8a84593095e3b69f47361ae15d73bdf"
```

it seems something has changed in the electron-log API, or I have some really weird issue.
The docs say we should do this:
```
const log = require('electron-log');
log.transports.file.level = process.env.JBM_LOG_LEVEL || 'info';
log.transports.console.level = process.env.JBM_LOG_LEVEL || 'info';
```
But there is no `transports` on the log object. Am I missing something?

![image](https://user-images.githubusercontent.com/623225/31829195-dfb92ab8-b5bc-11e7-957c-04cc19a89a69.png)

**Comment by megahertz** [comment]
You can't change transports in a renderer process

**Comment by loopmode** [comment]
Ah right. I made it conditional, thanks.
