### ISSUE TITLE
Why set log.transports.file.file doesn't work?

### ISSUE THREAD

**Issue by K-Wen** [megahertz/electron-log#55]
Hello.

In my project(use electron & vue), I configure the transport formats in main.js like this.

    ```
    const logFormat = '{h}:{i}:{s}:{ms} {text}'
    log.transports.console.format = logFormat
    log.transports.console.format = (msg) => util.format.apply(util, msg.data);

    const appDataDir = path.join(app.getPath('appData'), 'my-project')
    log.transports.file.level = 'info'
    log.transports.file.format = logFormat
    log.transports.file.maxSize = 5 * 1024 * 1024
    log.transports.file.file = path.join(appDataDir, 'log.log')
    log.transports.file.streamConfig = { flags: 'w' }
    log.transports.file.stream = fs.createWriteStream('log.log')
```

1. This works in dev mode, except the log file does not in the path of configuration(appDataDir/log.log), but the project folder in my desktop.

2.When I build my app with electron builder and run, it shows me an error of 
"**Uncaught Exception:
Error: EACCES: permission denied, open 'log.log**'"

Am I wrong with something? How can this be fixed please.

**Comment by megahertz** [comment]
In most cases, the application directory is not writable after installation. That's why default log path is inside appData directory.

**Comment by Luzhanglei** [comment]
Thank you very much for quick response.

app.getPath('appData') in document is:
%APPDATA% on Windows
$XDG_CONFIG_HOME or ~/.config on Linux
~/Library/Application Support on macOS

Would you give me some suggestions about another good place of log file?

**Comment by megahertz** [comment]
yes, but this library saves logs to ~/Library/Logs on macOS. I see no reason to use another locations. Maybe you want to save logs to the temp folder. It depends on your application.

**Comment by K-Wen** [comment]
As you know, electron with vue is good at making cross platform applications. So I want to log to a suitable path and offer a menu of show log in finder. So if my application act abnormal,  they can use it and send application log to me to fix it.
Sorry of my poor English， hope make it clear.

**Comment by megahertz** [comment]
I think, in this situation it's better to use default electron-log paths. When a user needs to see logs (for example, through menu Help -> Show logs), you can open the log file or it's directory through shell.openItem

**Comment by K-Wen** [comment]
I found the reason, in my configurations, I set both file and stream property. Really stupid.
```
log.transports.file.file = path.join(appDataDir, 'log.log')
log.transports.file.streamConfig = { flags: 'w' }

log.transports.file.stream = fs.createWriteStream('log.log')
```

When I deleted the last line, it works perfectly good. 
Thank you!

**Comment by megahertz** [comment]
no problem)
