### ISSUE TITLE
Could not rotate log Error

### ISSUE THREAD

**Issue by mark-micallef** [megahertz/electron-log#59]
Hi, 

  We've been using eletron-log but we sometimes get the following error:

Could not rotate log Error: ENOENT: no such file or directory, rename 'c:\<app-dir-here>\log.log' -> 'c:\<app-dir-here>\log.old.log'

  An idea what it could be please?

Mark

**Comment by megahertz** [comment]
Hi. Do you change default file transport settings in your app?

**Comment by megahertz** [comment]
Feel free to reopen if v3.0.0-beta2 doesn't solve your problem.
