### ISSUE TITLE
Default appName should prefer productName instead of name from package.json

### ISSUE THREAD

**Issue by mattzuba** [megahertz/electron-log#6]
Per Electron's [documentation](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetname):

> You should usually also specify a productName field, which is your application's full capitalized name, and which will be preferred over name by Electron.

Electron's userData path utilizes the value returned from `app.getName()`, so with this module's default of using name, when packageName exists, there would end up being two data directories for the app.

**Comment by mattzuba** [comment]
Awesome!  Thanks for a great module and a fast fix!

**Comment by megahertz** [comment]
You are welcome!
