### ISSUE TITLE
Nothing Happening

### ISSUE THREAD

**Issue by purplekrayons** [megahertz/electron-log#60]
Electron: 1.7.9
Nodejs: 9.2.0
OS: Windows 10

I have installed electron-log

`npm install --save electron-log`

I have included the module

`var log = require('electron-log');`

Yet upon attempting to log something

`log.info('Hello, log - info');`
`log.warn('Hello, log - warning');`

Absolutely nothing is happening. No errors are occuring, no log messages in console, and no file is being created where the documentation suggests it should be created:

`%USERPROFILE%\AppData\Roaming\<app name>\log.log`

Are you able to confirm this is working in node 9.2.0?

**Comment by purplekrayons** [comment]
Okay so through some testing I've discovered few things -- I will admit your documentation is a little misleading -- but maybe thats just my interpretation of it. Posting the default behavior in the event this helps anyone else:

To use this in main.js, you must include as:

`var log = require('electron-log');`

Outside of main.js, include as such:

`var log = require('electron-log/renderer');`

By default, only `.error` and `.warn` will result in output to the local file.

```
log.error('this is an error');
log.warn('this is a warning');
```

To help showcase where each log level gets written by default, I used the following test block:

```
log.error('test');
log.warn('test');
log.info('test');
log.verbose('test');
log.debug('test');
log.silly('test');
```

If used _within_ the main process:

main console: `error, warn, info, verbose, debug, silly`
render console: `-none-`
local file: `error, warn`

If used _outside_ the main process:

main console: `error, warn, info, verbose, debug, silly`
render console: `error, warn, info, verbose`
local file: `error, warn`

You can disable logging to console, from the main process, as such:

`log.transports.console.level = false;`

However, if you attempt to disable console level logging within a render process, it breaks.

Personally, I find it odd that logs within the render process, are also logged to the main process console. This module feels messy to me, but that's again -- within the scope of my project. If anyone else feels like they are in the same boat, check out [Winston](https://github.com/winstonjs/winston).

**Comment by megahertz** [comment]
Thank you for the report. Yes, I think some parts of the documentation should be improved.

**Comment by drdgvhbh** [comment]
I'm unable to get logs produced in the renderer. Only works in the main process for me using the solution provided above.

**Comment by wjljack** [comment]
Nothing Happening +1

**Comment by wjljack** [comment]
run on mac,log.warn and log.error do not create log.log file in Library/Log/

**Comment by megahertz** [comment]
@wjljack I'll try to run tests on mac a bit later

**Comment by wjljack** [comment]
@megahertz  thank you , any result?

**Comment by megahertz** [comment]
@wjljack Sorry, it's hard to find time now. I'll try to fix this problem on this week. Could your provide me more information to reproduce the problem? Like electron version, is webpack used, do you change some transport settings and so on?

**Comment by wjljack** [comment]
electron version is 1.7.9 ,and i use electron-react-boilerplate on mac,i have run your test suite ,and everything is ok (include main and render log),but when i use electron-react-boilerplate, i can only write log file in main.js , renderer file is nothing happen,I use ipcRenderer send log and ipcMain to write log instead now.

**Comment by megahertz** [comment]
@wjljack You need to import electron-log in the main process. Without it, electron-log doesn't works in a renderer process.

**Comment by wjljack** [comment]
thank you , i'll try.

**Comment by nicosang** [comment]
Hi,

I'd like to use the function log.debug in electron renderer process. Unfortunately, nothing is shown in the node console despite a call to log.transports.console.level = 'debug';

any idea?

Thanks,
Nico

**Comment by megahertz** [comment]
Hi Nico. Does `log.warn` work for you?

**Comment by nicosang** [comment]
Yes, with the same console level as described just before (log.transports.console.level = 'debug') if I replace log.debug by log.warn, it works.

**Comment by megahertz** [comment]
@nicosang Maybe you have the same problem #44?

**Comment by nicosang** [comment]
I don't think so because if I call a console.debug, I can see the result in the chrome devtools console...

**Comment by megahertz** [comment]
@nicosang By default, devtools doesn't show debug messages. Set the filter inside devtools to Verbose.

**Comment by nicosang** [comment]
Thanks for your answer @megahertz. I have no problem to see console.debug messages in devtools console. My problem is that I can't see messages written by electron-log.debug in node console while I can see electron-log.info....

**Comment by megahertz** [comment]
I can reproduce the problem. I've replaced all calls in https://github.com/megahertz/electron-log/tree/master/test-projects/electron-log-test-simple from log.warn to log.debug, here is the console output:
```bash
> electron ./main.js

[20:54:11.266] [debug] log from the main process
[20:54:11.763] [debug] log from a renderer process
[20:54:11.992] [debug] log from the second renderer process
```

**Comment by nicosang** [comment]
Many thanks @megahertz for your help! I finally understood what was happening. My application is an electron app that use electron-vue, so it starts electron with option '--inspect=5858' as it is decribed in #44. So, in order to see electron-log.debug messages, I only have to open the node inspector chrome-devtools.  Sorry to have disturbed you :-(
