### ISSUE TITLE
App crash / freeze sending multiple logs from renderer

### ISSUE THREAD

**Issue by bendroptask** [megahertz/electron-log#61]
**Background**
Using electron log to log for both main process and renderer and logging quite a bit but not ridiculous amounts either (~1.5MB for half an hour of usage). Potential for logs to be sent in quick succession.

**Issue**
Crash and freezing of Electron (1.7.9) app using when using electron-log (2.2.11) and creating multiple log events in a short space of time from the renderer. The issue was isolated to `electron-log` as the app stability returned when logging was disabled. 

**Usage**

Main Process
```
var log = require('electron-log');

log.transports.file.level = 'info';		
log.transports.console.level = 'info';		
log.transports.file.maxSize = 10 * 1024 * 1024;
```

Renderer
```
var log = require('electron-log');	
console.log = log.info
```

**Comment by megahertz** [comment]
Thank you for the report. I'll try to write the corresponding test in a week. Which OS do you use when this problem appears?

**Comment by bendroptask** [comment]
Thanks @megahertz! I replicated on both Windows 10 and macOS Sierra

**Comment by bendroptask** [comment]
Thanks again for the responsiveness. I spend some time debugging it this afternoon and it seems like the issue is with transport of more complex objects in the IPC. 

More specifically this function in Electron's remote: https://github.com/electron/electron/blob/8736a41cfbc9aec4ba2ecde6788a7afccb426e40/lib/renderer/api/remote.js#L15

It seems like there is nothing to do here so it can be closed up. If anyone else stumbles into here, if you are having a similar issue and Electron has not added any safety precautions, you can try reducing or normalising some of the data being transported through the IPC.

**Comment by megahertz** [comment]
Thank you for the information. I knew that sync IPC calls are not very stable, but I didn't know that async IPC calls too.
