### ISSUE TITLE
undefined error in "transports" of Electron-log

### ISSUE THREAD

**Issue by rharish100193** [megahertz/electron-log#62]
Hi,
In my Application. I am using electron-log in a Util file and followed as per the Documentation. I am getting the below error

`
Uncaught (in promise) TypeError: Cannot read property 'file' of undefined.
`
I tried printing the Electron-log Object and **`transports`** property is not present.

NOTE: I am loading this file from the preload JS file of the BrowserWindow.

**Comment by megahertz** [comment]
Hi. Transports can be configured only inside the main process.

**Comment by rharish100193** [comment]
Thanks. Handled it through IPC.
