### ISSUE TITLE
log.transports.file.appName isn't changing log location on Windows

### ISSUE THREAD

**Issue by jlgreen2012** [megahertz/electron-log#66]
Hi, I have this as the first line in my main.js: `log.transports.file.appName = 'Some other name';`

I am using electron-builder to package the app as a Windows nsis installer. I've installed on a Windows 7 and Windows 10 machine. On both, the log.log file is created in %APPDATA%\Roaming\<my package.json productName>. Based on the docs, I was expecting the log.log file to be created in %APPDATA5\Romaing\Some Other Name.

Other log configurations defined in the same file, such as level, are respected. I did uninstall and delete all relevant directories from my appdata before running the updated installer. 

electron-log v 1.3.0

Thanks!

**Comment by megahertz** [comment]
Hi. Make sure that you set appName before the first logging.

**Comment by jlgreen2012** [comment]
@megahertz Hey i have it as the very first line in my main.js, which, to my knowledge, is the file used by default when starting the node application, right? I did try copy/pasting the statement all around the application (ie. in my updater.js file which handles updates, in my routes, etc). I do reference electron-log from several places, so if this is the only known cause, I will start removing those and working to narrow this down.

**Comment by megahertz** [comment]
```js
const log = require('electron-log');

console.log('before logging', log.transports.file.file);

log.transports.file.appName = 'tmp1';
log.warn('test');

console.log('after logging', log.transports.file.file);
```

If it's configured correctly before the first logging call, It should write to console something similar to:
```
before logging undefined
[07:35:30.479] [warn] test
after logging /home/megahertz/.config/tmp1/log.log
```

**Comment by jlgreen2012** [comment]
I am running a Windows executable, so, to my knowledge, console.log does not write anywhere once installed. Unfortunately, I cannot test using that code sample unless the console output can be viewed somewhere.

I did remove electron-log from my code base except in main.js. The very first lines of code I have are 
```
log.transports.file.appName = 'tmp1';
log.warn('test'`)
```

I removed every other log.* statements. It is still creating the %APPDATA%\<Product Name> directory with log.log file. Any other suggestions?

**Comment by megahertz** [comment]
You can run the main executable of installed application from console directly using `AppData\Local\{app name}\{app version}\{app name}.exe` (if I remember the path correctly)

**Comment by megahertz** [comment]
Feel free to reopen if v3.0.0-beta2 doesn't solve your problem.

**Comment by shivarkarimi** [comment]
I have the same problem. I'm on  "electron-log": "4.1.1",
```
    log.transports.file.appName = LOG_NAMINGS.APP_NAME;
    log.transports.file.fileName = LOG_NAMINGS.FILE_NAME;
```
only updates `filename` but not `appName`

so I had to do something like:

   ```
 log.transports.file.resolvePath = (variables) => {
      const s = variables.libraryTemplate.replace('{appName}', LOG_NAMINGS.APP_NAME);
      return path.join(s, LOG_NAMINGS.FILE_NAME);
```
it was all fine before I upgraded to v4 - I was on 3.0.2 before
