### ISSUE TITLE
If console transport is disabled or has a greater level than file logging, file transport does not run

### ISSUE THREAD

**Issue by mattzuba** [megahertz/electron-log#7]
Looks to be caused by [Lines 89-94](https://github.com/megahertz/electron-log/blob/6da953f/index.js#L89-L94).  

```javascript
    if (!transports.hasOwnProperty(i) || typeof transports[i] !== 'function') {
      return;
    }
    if (!compareLevels(transports[i].level, level)) {
      return;
    }
```

These should probably be `continue;` statements.  I changed these locally to `continue;` and I get the expected result (no console log, but `info` level logging to file, as setup in my app config)

**Comment by megahertz** [comment]
You're right, thank you
