### ISSUE TITLE
How to implement new log levels?

### ISSUE THREAD

**Issue by Miw0** [megahertz/electron-log#70]
As the title says, I would like to add more log levels. How can I do that?
The default ones `error, warn, info, verbose, debug, silly` are not enough for our manager ;)

Also, what does the log level `silly` stand for?

Thank you!

**Comment by megahertz** [comment]
It's impossible in this time. I'm going to make it possible in version 3, which will be release in the next few months.

**Comment by megahertz** [comment]
in v3.0.0-beta2 you can add a new level using 
```js
const log = require('electron-log');
const logFunction = require('electron-log/lib/log');

log.levels.push('custom');
log.custom = logFunction.bind(null, log, 'custom');
```

**Comment by Slapbox** [comment]
@megahertz thanks for adding this great feature! Quick question, how would one control where this custom level is logged to, eg, `file` or `console`. These instructions indeed setup an additional log level, but it doesn't seem like I can output it to anywhere. Am I overlooking something obvious?

Thanks again!
