### ISSUE TITLE
Log file missing

### ISSUE THREAD

**Issue by declanvk** [megahertz/electron-log#71]
Hello,

I'm using `electron-log` on Mac and I'm running into an issue where the log file is not being created.
Here is the code that is generated from Typescript into the top of my `main.js`, which is the Electron entrypoint.
```js
var electron_1 = require("electron");
var electron_log_1 = require("electron-log");
var isDevMode = process.m
ainModule.filename.indexOf('app.asar') === -1;
if (isDevMode) {
    electron_log_1.default.transports.console.level = 'info';
    electron_log_1.default.transports.file.level = 'info';
    electron_log_1.default.info('In development mode');
}
else {
    electron_log_1.default.transports.console.level = false;
    electron_log_1.default.transports.file.level = 'info';
    electron_log_1.default.info('In production mode');
}
```

When I run `npm start` it outputs:
```
15:24 $ npm start

> jupyterlab_app@0.1.1 start /Users/dev/ExternalProjects/jupyter/jupyterlab_app
> electron .

[15:25:22.041] [info] In development mode
```

However, when I look in `~/Library/Logs/` there is no folder with either the name of my application or `Electron`.

Thanks,
Declan

**Comment by megahertz** [comment]
Hi. What's the output of `log.transports.file.findLogPath()` ?

**Comment by declanvk** [comment]
`/Users/dev/Library/Logs/jupyterlab_app/log.log` which also does not appear.

**Comment by declanvk** [comment]
I'm so sorry, some how I just spent this whole time look at `/Library` and didn't realize. Rather embarrassed now, thank you for your help.
