### ISSUE TITLE
Clear logs

### ISSUE THREAD

**Issue by techeverri** [megahertz/electron-log#73]
Hey @megahertz,

Is there any `clear()` method available internally to delete the `log.old.log` and clear the content of `log.log`? I checked the code, but couldn't find anything.
If no, Would it be possible to implement that using the file transport?

Thank you and all the contributors for maintaining this useful module 😃

**Comment by megahertz** [comment]
Hi @techeverri 

There is no a such method. I'll think about adding this method in v3

**Comment by megahertz** [comment]
Resolved, v3.0.0-beta2

**Comment by techeverri** [comment]
Thanks @megahertz :+1:
