### ISSUE TITLE
how to append to log file

### ISSUE THREAD

**Issue by SebastianDettmann** [megahertz/electron-log#74]
Hi megahertz,

when my electron app restarts, it's overriding the old log file.
I want append the new logging data to the old log file. How can I do this?

I'm using ubuntu 14.04.

here is my code:

```
const electron = require('electron');
const log = require('electron-log');
const app = electron.app;
const ipcMain = electron.ipcMain;
...
log.transports.file.level = 'debug';
log.transports.file.maxSize = 15 * 1024 * 1024;
log.transports.file.file = __dirname + '/app.log';
log.transports.file.streamConfig = { flags: 'w' };
log.transports.file.stream = fs.createWriteStream(log.transports.file.file);
log.transports.console.level = 'debug';
...
app.on('ready', function() {
    log.info('start app');
...
}
```
I read this: 
"Modifying a file rather than replacing it may require a flags mode of r+ rather than the default mode w"
at:  https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options

and tried this:

`log.transports.file.streamConfig = { flags: 'r+' };`

and 'a'  too

but it dosn't solved the problem.
What have I to do, to make it work?

Thank you for your help

**Comment by megahertz** [comment]
Hi @SebastianDettmann, use 'a' flag

**Comment by SebastianDettmann** [comment]
thanks a lot

**Comment by pbmzero** [comment]
@SebastianDettmann  Did you solve this? I used 'a' in the streamConfig and it overwrites. I also tried not setting the flags at all so it would use the 'a' flag (which was suggested as the default). The file is overwritten each time the app starts up.

**Comment by megahertz** [comment]
@pbmzero Could you provide your config?

**Comment by pbmzero** [comment]
@megahertz Thanks for the help. I'm using electron-log 2.2.14 pulled from npm.

    logger.transports.file.level = 'info';
    logger.transports.file.maxSize = 5 * 1024 * 1024;
    logger.transports.file.file = __dirname + '/log.log';
    logger.transports.file.streamConfig = {flags: 'a'};
    logger.transports.file.stream = fs.createWriteStream(logger.transports.file.file);

It does appear that you use 'a' in the library in the transports\file\index.js if i don't pass streamConfig, i've tried both with and without and yielded the same result which is a new file each time.

**Comment by megahertz** [comment]
@pbmzero If you create a stream by youself, you should pass the flags directly to createWriteStream, not through electron-log config.

**Comment by SebastianDettmann** [comment]
@pbmzero 
I did it in this way:

`log.transports.file.stream = fs.createWriteStream(log.transports.file.file, { flags: 'a' });`

in your case, maybe this is better (to not repeat your self):

`log.transports.file.stream = fs.createWriteStream(log.transports.file.file, log.transports.file.streamConfig);`

**Comment by pbmzero** [comment]
@SebastianDettmann  That's it -- thank you!!

**Comment by megahertz** [comment]
Be aware that the stream option is deleted in v3.

**Comment by JessicaIpo** [comment]
Thanks a lot  !
