### ISSUE TITLE
Not Save the file log

### ISSUE THREAD

**Issue by jempis** [megahertz/electron-log#76]
Hi, (sorry for my english)
i explain my situation:
First  have implemented the electron-log in the main process, and the module print the log in the console and save in file (in the default path --> Windows: %USERPROFILE%\AppData\Roaming\<app name>\log.log)
So everything is ok.

After i have remove the log in the main process and it use in the renderer process and not save in the file, but only print in the console.

After a few days, i have remove in the renderer process the module and reported in the main process, but the log file is not saved.
I have tested with all levels...

What i wrong? 
What should I do to get back to the beginning??

Thanks
J

**Comment by megahertz** [comment]
Hi, have you changed some electron-log settings?

**Comment by jempis** [comment]
Hi,
i have set only this 
log.transports.file.level = 'info';

**Comment by megahertz** [comment]
Unfortunately, IDK

Try:
- set 'silly' to log.transports.file.level
- make sure that this level is set before first logging call
- check whether %USERPROFILE%\AppData\Roaming<app name>\log.log has correct permissions
- after logging call, try `console.log(log.transports.file.file)` Does it print the same path as above?

**Comment by jempis** [comment]
Perfect,
now save the file...
the path is the same......

i have reinstall all library too, maybe it was also this?

Anyway, 
thanks
J

**Comment by megahertz** [comment]
Nice. So, can we close the issue?
Actualy, it's hard to determine what was the reason. And yes, `rm -rf node_modules && npm i` usually solves a lot of problems :)
