### ISSUE TITLE
Option to ignore duplicate messages

### ISSUE THREAD

**Issue by ChrisK2** [megahertz/electron-log#79]
Hi,

I have a difficult to avoid case where my application logic will log the same error message multiple times in a row. A simple option to just discard a log message if it is identical to the previous one would help a lot.

**Comment by megahertz** [comment]
Hi @ChrisK2.
Sorry, but I always try to keep this library as simple as possible. But you can easily make it possible to filter duplicate messages by overriding transport function.

**Comment by megahertz** [comment]
You can use hooks to implement this feature, available in v3.0.0-beta2
