### ISSUE TITLE
Electron-log Typescript : Property 'stream' does not exist on type 'IFileTransport'.

### ISSUE THREAD

**Issue by jhondavila** [megahertz/electron-log#80]
I have next error:

electronLog.transports.file.level = 'debug';
electronLog.transports.file.format = '{h}:{i}:{s}:{ms} {text}';

electronLog.transports.file.maxSize = 5 * 1024 * 1024;

// electronLog.transports.file.file = __dirname + '/log.txt';
// electronLog.transports.file.streamConfig = { flags: 'a' };
electronLog.transports.file.stream = fs.createWriteStream("log.txt", { flags: 'a' });

ERROR in D:\Dev\Wx\src\wx\core\log\ElectronLog.ts
./src/wx/core/log/ElectronLog.ts
[tsl] ERROR in D:\Dev\Wx\src\wx\core\log\ElectronLog.ts(11,29)
      TS2339: Property 'stream' does not exist on type 'IFileTransport'.

**Comment by megahertz** [comment]
Thank you, will fix in a few days.

**Comment by D4rkness** [comment]
I think the Problem here is also, that you have a typo -> probably you mean "stream" not "steam"
