### ISSUE TITLE
Log not saved in Mac OS X

### ISSUE THREAD

**Issue by firepol** [megahertz/electron-log#82]
Hi,

I'm new to electron, and I tried your logger v2.2.15 in my macOS HighSierra 10.13.5 (17F77).

In my main.js, at the top I added: `var log = require('electron-log')`
Inside an ipc event (button click) I added: `log.info('test')`
In the terminal I can see: `[16:55:06.806] [info] test`

But if I browse to ~/Library/Logs there is no folder and no log file for my app.

I was expecting to find a folder called `my-app` and a file called log.log inside, as you wrote in the docs... can you help?

In my package.json:
```
  "name": "my-app",
  "version": "0.1.0",
  "main": "src/main/main.js",
  "scripts": {
    "start": "electron ."
  },
...
```

**Comment by megahertz** [comment]
Hi. By default, only warning and error level messages are written to log file.

**Comment by firepol** [comment]
Yeah I just figured it out ;) I think it would be a good idea to mention it (read it as feature request for the readme) just before or after the usage example for noobs like me, so it would be crystal clear from the beginning, thx ;)

**Comment by megahertz** [comment]
Thank you. Actually, it's mentioned in readme, but it seems I need to improve this hint a bit.

**Comment by tombolala** [comment]
Hi,

I figured this out, but I do not understand to change the default. I am quite new to typescript, angular, etc. - I tried following: var log = require('electron-log');
then log.transports.file.level = false result in transports being undefined

Any idea how to set this up correctly?

Best regards,
Thomas

**Comment by megahertz** [comment]
@tombolala If you just want to enable file logging for all situations, `log.transports.file.level = 'silly';`

**Comment by tombolala** [comment]
Hi megahertz,

thanx for the answer. Problem is that transports being undefined:
RROR TypeError: Cannot read property 'file' of undefined
    at new Logger (logger.ts? [sm]:30)
    at /Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:1556
    at _callFactory (/Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:8457)
    at _createProviderInstance (/Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:8415)
    at resolveNgModuleDep (/Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:8390)
    at NgModuleRef_.get (/Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:9083)
    at resolveDep (/Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:9448)
    at createClass (/Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:9322)
    at createDirectiveInstance (/Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:9205)
    at createViewNodes (/Users/tom/code/KleinePraxis/node_modules/@angular/core/bundles/core.umd.js:10425)

Any idea?

import { Injectable } from '@angular/core';

var log = require('electron-log');

@Injectable({
    providedIn: 'root',
})
export class Logger {
    logInfo(msg: string) {
        console.log(msg)
        log.info(msg)
    }

    logWarning(msg: string) {
        console.log(msg)
        log.warn(msg)
    }

    logError(msg: string) {
        console.log(msg)
        log.error(msg)
    }

    logDebug(msg: string) {
        console.log(msg)
        log.info(msg)
    }

    constructor() {
        log.transports.file.level = 'silly'
    }
}

Removing that will still not log anything, even an error - at least nothing in ~/Library/Logs/<app name> on my Mac.

Thanx in advance
Thomas

**Comment by megahertz** [comment]
@tombolala You should configure transports in the main process, not in renderer.

**Comment by tombolala** [comment]
Sorry for stupid questions. Got it working now!

Thanx
Thomas
