### ISSUE TITLE
Log file not generated in linux ubuntu

### ISSUE THREAD

**Issue by soubhikchatterjee** [megahertz/electron-log#83]
The following is my code

`const log = require("electron-log");`
`log.warn('test');`

But when i run it, no log file is available at /home/soubhik/.config/eisen-sync

> soubhik@chatterjee:~/.config/eisen-sync$ ls -la
total 52
drwx------  5 soubhik soubhik  4096 Jun 27 14:19 .
drwxr-xr-x 51 soubhik soubhik  4096 Jun 27 15:00 ..
drwx------  2 soubhik soubhik  4096 Jun 27 13:51 Cache
-rw-r--r--  1 soubhik soubhik 28672 Jun 27 13:51 Cookies
-rw-r--r--  1 soubhik soubhik     0 Jun 27 13:51 Cookies-journal
drwx------  2 soubhik soubhik  4096 Jun 27 13:51 GPUCache
drwx------  3 soubhik soubhik  4096 Jun 27 14:18 Local Storage
-rw-------  1 soubhik soubhik   900 Jun 27 14:19 Preferences

Please help.

**Comment by matthewcummings** [comment]
I'm seeing the same behavior on Ubuntu 18.04.  The value `log.transports.file.file` is undefined for me.

**Comment by matthewcummings** [comment]
Ahh, OK.  Thanks!
