### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined in renderer.js:34

### ISSUE THREAD

**Issue by jarrodek** [megahertz/electron-log#92]
With the last version of electron and electron-log I have this wired error:

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at EventEmitter.<anonymous> (/home/pawel/workspace/advanced-rest-client/arc-electron/node_modules/electron-log/renderer.js:34)
    at emitThree (events.js:141)
    at EventEmitter.emit (events.js:217)
```
It is happening each time I use any electron-log function in the renderer process.

I tacked what it is doing and I have noticed that:

- in renderer process the log data is send properly, as an array where first item is a level and second is the data (here I am using simple string as a message)
- in the main process the `onRendererLog` function for some reason receives data with a transport object already applied to it.

So when `onRendererLog` is called in line 45 of `main.js` the first item of the array is a transport object. Therefore when you call `data.unshift(transports);` it adds another transport and the log function breaks as the level argument becomes an object.

I am not sure how it this possible that data sent to main process are different to the ones received. Also I don't know why it contains the transport object even if it wasn't yet pushed to the array.
Also I am not using any transport configuration so it is set to default.

**Comment by jarrodek** [comment]
Also I have noticed that each log is printed twice. That would explain why data already contained transport but I am not sure why.

![image](https://user-images.githubusercontent.com/3320020/44056928-9c130ece-9efe-11e8-94e0-087aab77cdf4.png)

**Comment by megahertz** [comment]
Thank you for the report. I'll try to fix it in a few days.

**Comment by jarrodek** [comment]
My project is here: https://github.com/advanced-rest-client/arc-electron/tree/polymer-2-upgrade where is have problem with the libray. I will spend more time on this later this week as I have a lot of code to write right now :)

**Comment by megahertz** [comment]
`npm dedupe` solves your problem

**Comment by jarrodek** [comment]
I've updated modules and everything works now and can't reproduce the problem anymore.
I don't know what it was and apparently now it's no way to know.

**Comment by megahertz** [comment]
@jarrodek you had duplicated modules
