### ISSUE TITLE
Distributed Mac OSX app binary gets permission errors creating log.txt

### ISSUE THREAD

**Issue by renegadeandy** [megahertz/electron-log#93]
Hi,

I have electron-log in my app, works fine in dev. When I package the app for dist, and install onto macosx, when the app starts I see the following error:

![image](https://user-images.githubusercontent.com/831013/44583322-b0ef2700-a79c-11e8-8c2c-34634ef96814.png)

All of the log file paths etc are default. So does this mean, the app is failing to write a file to this directory:

~/Library/Logs/<app name>/log.log? If this is the case, how can I catch this error, and attempt to create the log somewhere else? Why would this error actually be happening, surely the home dir of the user in this path should be writeable?

The odd thing is, when I navigate to : ~/Library/Logs, I see a folder in there for my app name, but it has no log file inside.....so it's made the directory but not the log file? How can I debug what is happening here?

Additionally, on a windows binary, I am checking directory : %USERPROFILE%\AppData\Roaming\<app name>\log.log for the log, however the folder is there, it is also empty. 

When I check the installed directory of the app on windows, I then see my log.txt correctly populated with logs! Is the doc wrong? Perhaps I made a configuration mistake somewhere, see my config below:

```
function setupLogging(){
// Log level
logger.transports.file.level = 'info';
logger.transports.file.level = true;
// Same as for console transport
logger.transports.file.format = '{h}:{i}:{s}:{ms} {text}';
 
// Set approximate maximum log size in bytes. When it exceeds,
// the archived log will be saved as the log.old.log file
logger.transports.file.maxSize = 5 * 1024 * 1024;
 
// Write to this file, must be set before first logging
logger.transports.file.file = __dirname + '/log.txt';
 
// fs.createWriteStream options, must be set before first logging
// you can find more information at
// https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options
logger.transports.file.streamConfig = { flags: 'w' };
 
// set existed file stream
logger.transports.file.stream = fs.createWriteStream('log.txt');

})
```

**Comment by megahertz** [comment]
Hi @renegadeandy. Just remove this code. You don't need to configure any parameters (while you have no some special requirements).

**Comment by renegadeandy** [comment]
Hi! Well I do want some of those lines , but I commented out:

```
//logger.transports.file.file = __dirname + '/log.txt';
//logger.transports.file.streamConfig = { flags: 'w' };
//logger.transports.file.stream = fs.createWriteStream('log.txt');
```

and now the log is created successfully 👍

**Comment by renegadeandy** [comment]
I wonder if you could update the example in the readme.MD and perhaps remove this:

`logger.transports.file.file = __dirname + '/log.txt'; `

I am not sure why somebody would want this and for a new user to the package like me, I thought it was needed and it was responsible for my confusion and error!

**Comment by megahertz** [comment]
Yes, this example is only for some special cases, so I'm going to change this part of documentation later.
