### ISSUE TITLE
Slow logging performance.

### ISSUE THREAD

**Issue by burtonator** [megahertz/electron-log#94]
As soon as I enable logging using electron-log in my app, it's much much slower.

100ms loading time down to 2500ms .. roughly.

I'll keep updating this bug but I wanted to provide feedback. I'm going to try disabling disk logging too but that was the main point of wanting to use electron-log.

Maybe some sort of queue that gets drained via a web worker might be a fix.

**Comment by burtonator** [comment]
Just disabled both delegates.  File and console. No messages are written but it's still very very slow.

**Comment by megahertz** [comment]
It seems that you write a lot of logs, otherwise it doesn't impact on performance too much. Currently, electron-log uses IPC, so it's pretty slow. In v3 i'm going to stop using IPC.

**Comment by burtonator** [comment]
Yeah. I've noticed that IPC is a bit slow.  What are you going to use other than IPC?

**Comment by megahertz** [comment]
Nothing. I'm going to make main and renderer parts more independant.

**Comment by burtonator** [comment]
I'm going to take your file implementation that works in the main and re-implement it to use atomic append.

Apparently on NTFS it works fine up to 1k which I think is more than enough for log operations.

If it works I'll post the code back here so you could run with it if you want.  No IPC would be required in that use case.

**Comment by megahertz** [comment]
Thank you. I know there is no performance problem when appending content to a file. I ran a lot of test for another library when deciding whether to use IPC or append to a single file from multiple processes.

**Comment by megahertz** [comment]
Try v3.0.0-beta2. It disables IPC calls for a packaged application.
