### ISSUE TITLE
No logs for apps with spaces in name

### ISSUE THREAD

**Issue by bradydowling** [megahertz/electron-log#96]
Version: 1.3.0 and 2.2.17
Platform: macOS (10.12.6)
Packager: Electron

Logging does not work if there is a space in the app name. It will create the log directory but not the log file itself. No logs are actually written anywhere. Once the space is removed, log files are written as expected.

**Comment by bradydowling** [comment]
Forgot to mention that this is all using default logging levels and then logging with `log.warn("something");`. I've guess that single/double quotes makes no difference but I'm using double.

**Comment by megahertz** [comment]
So, still no log.log file? I've just tested a simple app with productName set to 'el test' on macOS, and it works as expected. Could you tell me the name of your app? Maybe there are some other special chars in name?

**Comment by jdoubleu** [comment]
Can't reproduce neither.
My app which has spaces in it works fine.

It seems more like a different error.
Did you require the logger inside your main process?

**Comment by manast** [comment]
ok, the problem was that info and debug do not get stored in the file... I wonder, why such a behaviour?

**Comment by megahertz** [comment]
@manast In most cases, you don't need verbose logs in a file. But I know, sometimes it confuses. I've changed this behavior in v3.

**Comment by manast** [comment]
@megahertz yeah, too opinionated in my opinion :)

**Comment by megahertz** [comment]
Default log level is changed in v3.
