### ISSUE TITLE
Log should be written to path "userData" instead of "appName"

### ISSUE THREAD

**Issue by bingqiao** [megahertz/electron-log#97]
I suppose in most cases, there is no difference between userData is appData plus appName. But userData can be changed as in our application, which means the log still gets written to the "default" location.

Thanks

**Comment by megahertz** [comment]
Thank you, I'll think about it.

**Comment by bingqiao** [comment]
Thanks for looking into this.

Here is an example of the change I was referring to:
```
const newAppName = 'newAppName';
app.setName(newAppName);
app.setPath('userData', app.getPath('userData') + sep + app.getName());
```
So let's say the app name was 'oldAppName', then after changing app name and user data, the new user data becomes:
{appData}/oldAppName/newAppName

The use case is so that a group of electron apps can have their respective user data located in the same parent directory (the old app name).

Thanks

**Comment by megahertz** [comment]
You can try 3.0.0-beta

сб, 13 окт. 2018 г., 12:44 Bing Qiao <notifications@github.com>:

**Comment by bingqiao** [comment]
Thanks this works well on Windows.

And just realized reading the code change, it's a bit complicated on MacOS given logs are normally placed in Library/logs instead of Application Support.

So on Windows, I now have the log in {appData}/oldAppName/newAppName while on MacOS, homeDir/Library/Logs/newAppName. It would be better to have it in homeDir/Library/Logs/oldAppName/newAppName but I see how this can't be done via userData alone.

The results are definitely good enough for our application. On the other hand, would it be not much of use to allow override of log path? And when will 3.0.0 be released?

Thanks for the help

**Comment by megahertz** [comment]
In your situation, it's better to override log.transports.file.file on macOS by yourself.

As for v3, I'm not going to release it soon. Maybe in November. It's pretty stable now, but still requires more tests and feedback.

**Comment by koalalorenzo** [comment]
Any update for this?

**Comment by megahertz** [comment]
@koalalorenzo You can use beta. The final version will be released in January (but I'm not sure).

**Comment by koalalorenzo** [comment]
what is blocking from delivering small changes? it has been in beta for long time :O

**Comment by megahertz** [comment]
There are huge changes in the internals, so I can't make a final releases without proper testing.
